### ISSUE TITLE
Failing tests - gem loading issue(s)

### ISSUE THREAD

**Issue by grimen** [activeadmin/inherited_resources#10]
<pre>
$ rake test --trace                                                                                                                                                           (09-04 03:44)
(in /Users/Jonas/Development/examples/inherited_resources)
** Invoke test (first_time)
** Execute test
/opt/local/bin/ruby -I"lib" "/opt/local/lib/ruby/gems/1.8/gems/rake-0.8.7/lib/rake/rake_test_loader.rb" "test/aliases_test.rb" "test/association_chain_test.rb" "test/base_test.rb" "test/belongs_to_test.rb" "test/class_methods_test.rb" "test/customized_belongs_to_test.rb" "test/defaults_test.rb" "test/flash_test.rb" "test/has_scope_test.rb" "test/nested_belongs_to_test.rb" "test/optional_belongs_to_test.rb" "test/polymorphic_test.rb" "test/redirect_to_test.rb" "test/respond_to_test.rb" "test/singleton_test.rb" "test/url_helpers_test.rb" 
DEPRECATION WARNING: has_scope :key is deprecated, use :as instead. (called from has_scope at /Users/Jonas/Development/examples/inherited_resources/lib/inherited_resources/class_methods.rb:131)
/opt/local/lib/ruby/gems/1.8/gems/activesupport-2.3.3/lib/active_support/dependencies.rb:105:in `const_missing': uninitialized constant Test::Unit::TestResult::TestResultFailureSupport (NameError)
    from /opt/local/lib/ruby/gems/1.8/gems/test-unit-2.0.2/lib/test/unit/testresult.rb:28
    from /opt/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
</pre>

While searching for info on this I found:

_You can't use Test::Unit 2.0 with old Test::Unit.
Call 'gem "test-unit"' before 'require "test/unit"._

**Comment by josevalim** [comment]
Fixed!
