### ISSUE TITLE
.each issue for empty list on nested resources

### ISSUE THREAD

**Issue by ardavis** [activeadmin/inherited_resources#100]
In our CommentsController, we have:

<code>nested_belongs_to :project, :task</code>

In our new.html.erb, we want to show objects associated with our tasks

<code>
<% @task.comments.each do |comment| %>
  <%= comment.body %>
<% end %>
</code>

This iterator is trying to display elements even when there are no comments for this task. The element displayed is of type "Comment".

**Comment by dalton** [comment]
Is it possible that InheritedResource is adding the comment to @task in the new action of the CommentsController?

Possibly related to this code?

<code>
     def build_resource
        get_resource_ivar || set_resource_ivar(end_of_association_chain.send(method_for_build, params[resource_instance_name] || {}))
      end
</code>

Tracing through, it looks like that will call 

<code>
@comment = @task.build
</code>

Which does indeed appear in @task.comments.each despite still returning 0 for @task.comments.count.

**Comment by josevalim** [comment]
Yes. Exactly.
For new.html.erb, Inherited Resources will do @tasks.comments.build. Just overwrite your action if this is not what you intend to do.
