### ISSUE TITLE
Default redirects on all actions

### ISSUE THREAD

**Issue by activestylus** [activeadmin/inherited_resources#103]
NOTE: This is not an issue at all, in fact it is a question I posted on the google group but it appears that the group is not very active and is riddled with spam

Very simple:

How can I override the default redirect behavior on all controllers? To give you an idea of what I am trying to do:

```
def return_to_or_default( default )
  if params[:return_to]
    redirect_to params[:return_to]
  else
    redirect_to default
  end
end

def update
  update! do |success, failure|
    success.html { return_to_or_default project_url(@project) }
  end
end
```

I'd like to get this behavior out of the box instead of having to declare it on all my controllers. What would be the best method to accomplish this?

Thanks in advance!

**Comment by josevalim** [comment]
No option. Or you write your own responder or you overwrite all actions.

**Comment by activestylus** [comment]
Ok cool , I suspected as much. Time to write a custom responder...
