### ISSUE TITLE
ActiveResource validation errors with JSON

### ISSUE THREAD

**Issue by andyw8** [activeadmin/inherited_resources#104]
By default, inherited_resources returns the following JSON when the validations on an object fail:

```
{"name":"can't be blank", "city":"can't be blank"}
```

However, it seems that ActiveResource expects the errors to be formatted like this:

```
{:errors => ["Name can't be blank", "City can't be blank"]}
```

As far I know, there is no universally accepted way of representing validation errors, but it would seem logical to follow the ActiveResource convention.

I'm using Rails 3.0.3 and inherited_resources 1.1.2

**Comment by andyw8** [comment]
Actually, I think this may be an issue with the ActiveResource client. The serialisation is discussed here: https://rails.lighthouseapp.com/projects/8994/tickets/5616-activeresource-error-parsing-support-for-new-json-errors-serialization-format

**Comment by andyw8** [comment]
And here shows that Rails expects an :errors key (the from_json method):

https://github.com/rails/rails/blob/master/activeresource/lib/active_resource/validations.rb

**Comment by josevalim** [comment]
Inherited Resources does not do anything special, it just calls errors.to_json, the errors object in ActiveModel shuold know how to serialize itself. Therefore, if there is a bug, it is in Rails.
