### ISSUE TITLE
dependency issue with Rails 2.3 support

### ISSUE THREAD

**Issue by joemsak** [activeadmin/inherited_resources#106]
Maybe it's not a huge deal, but:

I was trying to get an old project running and I kept getting these uninitialized constant Rails::Railties issues and finally sniffed it out to:

inherited_resources-1.0.2 depends on [responders (>= 0.4.2)]

that should be ~ 0.4.2, because 0.5+ breaks in rails 2.3

**Comment by joemsak** [comment]
this is also an issue when using bundler -- 0.6.2 is pulled in automatically, crashes the app

**Comment by josevalim** [comment]
This has been fixed in later 1.0.x releases.

**Comment by joemsak** [comment]
cool thanks :)
