### ISSUE TITLE
Destroying nested record via accepts_nested_attributes_for doesn't update collection

### ISSUE THREAD

**Issue by jpzwarte** [activeadmin/inherited_resources#108]
When i destroy a nested object via the _destroy parameter as specified in the accepts_nested_attributes_for method, inherited_resources fails to update the collection on the resource object:

  def update
    update!
    p @product.items.try(:inspect)
    @product.reload
    p @product.items.try(:inspect)
  end

The first outputs an array with a single item. The second call outputs an empty array.

So the problem here is that inherited_resources doesn't update the collection. Everything else works fine in rails (deleting the record etc).

**Comment by jpzwarte** [comment]
Perhaps a patch something along these lines? (code is untested): https://gist.github.com/771915

**Comment by josevalim** [comment]
I would expect it to automatically call reload. This is something you should handle in your controller, maybe by customizing update_resource action.
