### ISSUE TITLE
Not picking up POST parameter

### ISSUE THREAD

**Issue by sirupsen** [activeadmin/inherited_resources#109]
I have a model that looks like this:

```
class Forum::ThreadsController < InheritedResources::Base
  defaults resource_class: ForumThread, collection_name: 'threads', instance_name: 'thread'
  respond_to :html
end
```

I send the request, but InheritedResources#create doesn't seem to pick them up and save them correctly:

 Parameters: {"utf8"=>"✓", "authenticity_token"=>"eaFOiFDywt9PoNaXBQqMOzcvQu+MBWIrA9rpOlzqPxY=", "forum_thread"=>{"title"=>"daf", "body"=>"adf"}, "commit"=>"Create Forum thread"}
  AREL (0.2ms)  INSERT INTO "forum_threads" ("title", "user_id", "body", "created_at", "updated_at") VALUES (NULL, NULL, NULL, '2011-01-12 19:49:17.418332', '2011-01-12 19:49:17.418332')

Or am I doing something wrong here?

**Comment by josevalim** [comment]
Maybe you are using attr_accessible in the model or attr_protected?

**Comment by sirupsen** [comment]
Thanks for such a quick update. My models are rather default, so this wouldn't be it.

I tested it out further, the weird thing is that this works:

  class Forum::ThreadsController < InheritedResources::Base
    defaults resource_class: ForumThread, collection_name: 'threads', instance_name: 'thread'
    respond_to :html

```
def create
  ft = ForumThread.new(params[:forum_thread])
  ft.user = current_user
  ft.save

  redirect_to forum_threads_path
end
```

  end

However, this doesn't:

  class Forum::ThreadsController < InheritedResources::Base
    defaults resource_class: ForumThread, collection_name: 'threads', instance_name: 'thread'
    respond_to :html

```
def create
  ft = ForumThread.new(params[:forum_thread])
  ft.user = current_user
  create!
end
```

  end

**Comment by josevalim** [comment]
In the second case, Devise is creating another resource and trying to find params[:thread] because this is the instance name you gave. You need to use instance variables as defined in the readme or don't call create! as you did in the first example.
