### ISSUE TITLE
Ruby 1.9 mime responder issues (together with AuthHelpers)

### ISSUE THREAD

**Issue by grimen** [activeadmin/inherited_resources#11]
<pre>
TypeError ({:with=>#<Account id: nil, login: nil, email: nil, crypted_password: nil, password_salt: nil, persistence_token: nil, single_access_token: nil, perishable_token: nil, confirmed_at: nil, confirmation_sent_at: nil, login_count: 0, failed_login_count: 0, last_request_at: nil, current_login_at: nil, last_login_at: nil, current_login_ip: nil, last_login_ip: nil, country: nil, time_zone: nil, locale: nil>} is not a symbol):
  /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/inherited_resources-0.9.1/lib/inherited_resources/legacy/respond_to.rb:100:in `block in retrieve_response_from_mimes'
  /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/inherited_resources-0.9.1/lib/inherited_resources/legacy/respond_to.rb:100:in `each'
  /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/inherited_resources-0.9.1/lib/inherited_resources/legacy/respond_to.rb:100:in `retrieve_response_from_mimes'
  /Users/jonas/.ruby_versions/ruby-1.9.1-p129/lib/ruby/gems/1.9.1/gems/inherited_resources-0.9.1/lib/inherited_resources/legacy/respond_to.rb:56:in `respond_to'
  ...
</pre>

Note: I run a slightly modified version of InheritedResources, but only touched rake/tests so far.

**Comment by grimen** [comment]
GitHub stripped parts of the output, but it's an instance of a Account that is returned (while calling confirmations_controller/new in my case):

<pre>
Processing Accounts::ConfirmationsController#new (for ::1 at 2009-09-11 03:31:30) [GET]
  Parameters: {"controller"=>"accounts/confirmations", "action"=>"new"}
 ...
</pre>

**Comment by josevalim** [comment]
Is this still alive?

**Comment by grimen** [comment]
I believe so; I never got it to work but I'm not running Ruby 1.9 in production anyway so can't tell - was some time ago I was exploring this. I remember I didn't do any hocus-pocus, it was kinda easy to raise that error with Authlogic + AuthHelpers.

**Comment by josevalim** [comment]
ok, so closing :)
