### ISSUE TITLE
InheritedResources and DataMapper 1.x aren't playing nicely together

### ISSUE THREAD

**Issue by contentfree** [activeadmin/inherited_resources#111]
A simple setup:

`application_controller.rb`
    class ApplicationController < ActionController::Base; end

`things_controller.rb` 
    class ThingsController < InheritedResources::Base
      respond_to :html
    end

`routes.rb` contains:
    resources :things

When I run webrick and go to `/things` I get the error:

```
Started GET "/things" for 127.0.0.1 at 2011-01-13 12:04:57 -0800

ActionController::RoutingError (You have a nil object when you didn't expect it!
You might have expected an instance of Array.
The error occurred while evaluating nil.[]=):
  app/controllers/base_resources_controller.rb:1:in `<top (required)>'
  app/controllers/things_controller.rb:1:in `<top (required)>'
```

The expectation is to get the index page of things. 

This is Rails 3.0.3 with DataMapper ~> 1.0 on Ruby 1.9.2

**Comment by josevalim** [comment]
Yes, it won't work with datamapper.

**Comment by contentfree** [comment]
Ouch. Why not?

**Comment by josevalim** [comment]
Inherited Resources has AR methods hardcoded. You can check it out (and change it) by checking InheritedResources::Actions in the source code. Other places may use AR specific methods as well.

**Comment by contentfree** [comment]
It ought to work if it was changed to be just ActiveModel-compatible though, right?
