### ISSUE TITLE
{{resource_name}} not replaced in flash messages

### ISSUE THREAD

**Issue by johnmichaelbradley** [activeadmin/inherited_resources#114]
As the title says, the resource name is not being inserted into any flash messages generated from classes using Inherited Resources. For example, an update generates "{{resource_name}} was successfully updated." I have tried explicitly setting resource_name by overwriting interpolation_options as the Responders source documentation suggests, but no luck.

Versions: Inherited Resources 1.0.6, Responders 0.4.7, Rails 2.3.10, Ruby 1.8.7 (Enterprise Edition 2010.02), Ubuntu 8.04 Server. Thanks for any help in advance.

**Comment by josevalim** [comment]
I18n 0.5 deprecates {{resource_name}}, you need to use %{resource_name} instead of go back to i18n 0.4.x
