### ISSUE TITLE
Default collection uses all() instead of scoped()

### ISSUE THREAD

**Issue by amw** [activeadmin/inherited_resources#115]
Currently default index action executes the load query inside it's body instead of where the collection rows are first used - inside the view. Model.all or Model.-finder-.all cause the default or current scope to be transformed into an Array object with result's rows.

Instead one can use Model.scoped or Model.-finder-.scoped to return the collection as ActiveRecord::Relation object. This is the same object that is returned by finders like Model.where().limit().offset() etc.. This way the rows won't be fetched until later. There are two benefits of this.

First this will be particularly important if automatic flushing gets implemented and released with Rails 3.1 (I don't know the status of that feature, but Katz wrote about it once). By postponing query execution we allow the layout's header to be sent to user's browser earlier.

Second you get a chance to add additional finders inside the view. I.e:
    <% @accounts.limit(5).each do |account| %>

The fix:

```
   def collection
-    get_collection_ivar || set_collection_ivar(end_of_association_chain.all)
+    get_collection_ivar || set_collection_ivar(end_of_association_chain.scoped)
   end
```

**Comment by josevalim** [comment]
Hey, could you please send a pull request with this patch plus one test? Thanks a lot!

**Comment by amw** [comment]
There's no problem with the patch, but the tests are an issue. I've noticed you're using fake model objects instead of real ActiveRecord objects. I could create a fake object with "scoped" method that would return fake relation, but it's a pointless running around.

Also I have to update current tests which produce some errors with my patch and I'm not sure how to do that. Take this as an example:
       Employee.expects(:all).returns([mock_employee])
Now I could change this to:
       Employee.expects(:scoped).returns([mock_employee])
And the test would pass, but that's not how the real "scoped" works. The real "scoped" returns ActiveRecord::Relation object instead of an Array. It can be used as an array or converted to an array with scoped.all, but it has other methods too.

Your thoughts?

**Comment by amw** [comment]
Accidentally closed the issue, but it's ok - there will be a new one with pull request.

Note to self: next time read the whole button, not just it's first word.

**Comment by kelso** [comment]
Thank you, I was searching some method like `set_collection_ivar`. Thanks for mentioning!
