### ISSUE TITLE
:collection_name key does not works in belongs_to

### ISSUE THREAD

**Issue by AskarZinurov** [activeadmin/inherited_resources#119]
:collection_name key does not works in belongs_to in controllers.

```
class CustomerUploadingSettingsController < InheritedResources::Base
   belongs_to :customer_uploading, :collection_name => :related_setting, :singleton => true
```

Still tries to find or create resource by customer_uploading_setting

**Comment by josevalim** [comment]
Yes, you should use resource_name. collection_name is used only on the index action (which is not available for singletons).

**Comment by AskarZinurov** [comment]
Seems like there are no such key for belongs_to association. 
    ArgumentError (Unknown key(s): resource_name)

**Comment by samwgoldman** [comment]
I can confirm that resource_name does not exist.

**Comment by mdub** [comment]
The documentation for #belongs_to suggests that :collection_name is a valid option, so this appears to be a valid bug (in the doco, if nothing else).

Unlike the Askar, my association is not a singleton:

```
belongs_to :program, :collection_name => "components"
```

but I cannot get :collection_name (or :resource_name) to work:

```
undefined method `program_components' for #<Program:0x000001075f1268>
```

**Comment by abecciu** [comment]
+1 this doesn't work for me either.

**Comment by paradoja** [comment]
Exactly the same for me. :collection_name key does not work and resource_name is not a valid key.

I'm also not using a singleton.

**Comment by voondo** [comment]
why closed ? I'm still encounter this bug

**Comment by joelmoss** [comment]
Can you confirm that this still occurs in the latest version?

**Comment by voondo** [comment]
yes I do (with the current master version).

Example : 

``` ruby
class Sellers::Catalog::VariantsController < InheritedResources::Base
  belongs_to :seller, collection_name: 'catalog' do
    belongs_to :product
  end
end
```

I get _undefined method `products' for Seller..._. But maybe I missed something ?

**Comment by voondo** [comment]
my bad... _collection_param: 'catalog'_ should be in the product's belongs_to
you can re-close, sorry and thanks for your quick answer
