### ISSUE TITLE
Firefox 3.5

### ISSUE THREAD

**Issue by paulca** [activeadmin/inherited_resources#12]
Hi,

I was trying out inherited_resources today and got it working really well with a test controller in an admin/ namespace ... The controller worked great in Safari, but not so much in Firefox (3.5) ... claiming that the template was not present...

... appending ".html" to the URL makes it work, so I suspect that there's no defaulting to .html in the plugin, perhaps a reliance on the Accept header?

Paul

**Comment by paulca** [comment]
Same behaviour when I use respond_to :html within the controller ... I'm using Rails 2.3.4

**Comment by josevalim** [comment]
Could you please reproduce the error in the test suite or through a sample app?

**Comment by paulca** [comment]
Hmmmm ... it works fine with a similar arrangement in a fresh app ... I'll have to dig about and figure out what's different in this case.

**Comment by paulca** [comment]
Been using and loving the plugin on a few other projects since this. I'm really not sure what was causing it in the other app, I'll come back to it if it crops up again.

**Comment by josevalim** [comment]
Thanks for the update! :)
