### ISSUE TITLE
Mongoid Incompatibility

### ISSUE THREAD

**Issue by shingara** [activeadmin/inherited_resources#122]
Hi,

Since commit https://github.com/josevalim/inherited_resources/commit/7fb9e76e5f48fdc8f507c5165881db66c0d10c14 There are a incompatibility with Mongoid. Mongoid doesn't have the #scoped method.

Using this #scoped method can explain some problem with incompatibility with differente ORM/ODM.

**Comment by josevalim** [comment]
Sorry, but it is not Inherited Resources current goals to support several ORMs. IR can eventually support it, but not in the current version. You can either monkey patch Mongoid and define scoped or include a module in InheritedResources base that changes collection to use a Mongoid compatible form. The second one is the most appropriate in my opinion.
