### ISSUE TITLE
NoMethodError "undefined method `build_"

### ISSUE THREAD

**Issue by panyamin** [activeadmin/inherited_resources#125]
Hello,

I've got this error : 

```
undefined method `build_servers_hardware_information' for #<Server:0x7f044f9a2bd0>
```

I don't understand why this happens..

Here is my controllers & models :

```
class ServersController < InheritedResources::Base
end

class ServersHardwareInformationsController < InheritedResources::Base
  belongs_to :server, :singleton => true
end

class Server < ActiveRecord::Base
  has_one :server_hardware_information
end

class ServersHardwareInformation < ActiveRecord::Base
end
```

Routes are :

```
  resources :servers do
    resource :servers_hardware_information
  end
```

Could you help me?

Thanks

**Comment by josevalim** [comment]
When you say:

class ServersHardwareInformasetionsController < InheritedResources::Base
  belongs_to :server, :singleton => true
end

It will do the following in new actions:

  Server.find(params[:server_id]).build_servers_hardware_information

You can overwrite build_resource to change this behavior. More info the README.

**Comment by vladhilko** [comment]
Yeah, you need to override `resource` and `build_resource` 
https://github.com/activeadmin/inherited_resources/blob/e5d75a42f4846fbd1b418e3c6f0bd4a203469d2c/lib/inherited_resources/singleton_helpers.rb#L19-L33
