### ISSUE TITLE
begin_of_association_chain  : A small issue, but it's bugging me.

### ISSUE THREAD

**Issue by paulca** [activeadmin/inherited_resources#13]
Shoot me down if I'm being pedantic, but this is Ruby!

I'm wondering if there's any reason for naming "begin_of_association_chain" as such ... it's not correct English, and I feel it sticks out in an otherwise very solid implementation.

I'd hazard that it should be 'beginning_of_association_chain" or "start_of_association_chain"

What do you think? Is this too anal?

Paul

**Comment by josevalim** [comment]
My bad! :P

Of course it has low priority, but I will change for end_of_association_chain when I have some time! ;)

**Comment by croaky** [comment]
begin_association_chain, end_association_chain would make sense in Ruby. It's the "ofs" that make it awkward. An alias of start_of_assocation_chain would also make sense.

**Comment by paulca** [comment]
@dan Agreed, but I think "begin_association_chain" changes the meaning sufficiently to hide the intent ... specifically that this is the first item in the association chain. I think it's just a coincidence that 'end' is a verb and 'beginning' isn't!

to me 'beginning_of_association_chain' is more expressive than 'start_of_assocation_chain' ....

@jose I think it would be wise to alias it as Dan suggests, or at least deprecate for a point release!

**Comment by josevalim** [comment]
Hey Paul, I've tried to do the change, non trivial. I will give up on this, unless you want to provide a patch yourself. Thanks!

**Comment by paulca** [comment]
Cool, no worries!
