### ISSUE TITLE
Problem with smart redirects

### ISSUE THREAD

**Issue by simonc** [activeadmin/inherited_resources#131]
Hi,

Strange issue here. When I use this

```
class AliasesController < ApplicationController
  inherit_resources
  belongs_to :host
  actions :all, :only => [:new, :create, :destroy]
end
```

I'm redirected to /hosts/42/aliases after a call to destroy but when I use this

```
class AliasesController < ApplicationController
  inherit_resources
  belongs_to :host
  actions :all, :except => [:index, :show, :edit, :update]
end
```

It works just fine and redirects me to /hosts/42

**Comment by josevalim** [comment]
Uo-oh :( Maybe you could provide a patch fixing the issue?

**Comment by simonc** [comment]
Ok, my bad. Using :all, :only => ... is just a non sense...
actions :new, :create, :destroy   works well.

Sorry :/
