### ISSUE TITLE
Model with to_param set isn't mapping correctly with ID in edit

### ISSUE THREAD

**Issue by sbwoodside** [activeadmin/inherited_resources#132]
I have a model `Product` with `to_param` defined to return, in this case, the UPC code of a product. I have overridden the `show` method and in this case `@upc = params['id']` gives me the UPC code as I would expect, rather than the `id` field from the database.

The `edit` method is not defined in my controller, so it should be falling back on the default inherited_resources method. However, when I try it, I get this error: `Couldn't find Product with ID=[SOME UPC CODE]`. I think this means that inherited_resources is not recognizing the `to_param` when it does the find. Is that possible?

**Comment by josevalim** [comment]
There is no way inherited resources can know that your to_param value comes from a given column. You need to customize the action.

**Comment by sbwoodside** [comment]
Yes, I understand, that makes sense.

I wonder if this is a common case, that people are using to_param or other methods for aliasing their objects in the URLs. Perhaps I could write a patch to inherited_resources that would allow me to specify the alias column? Where would I look for that code?

**Comment by josevalim** [comment]
You can simply overwrite the resource method. And there is a configuration option for associations. Pls check te readme!

**Comment by sbwoodside** [comment]
Thanks. Here's what I did:

<pre>  def edit
    @product = Product.find_by_upc(params['id'])
    edit!
  end
</pre>
