### ISSUE TITLE
Associated resource creation fails for has_many_through relation

### ISSUE THREAD

**Issue by uhees** [activeadmin/inherited_resources#133]
Hello,

I am using inherited_resource 1.0.6 with rails 2.3.11 and found that creating a resource that is associated via a has_many_through relation did not get a connection to its parent resource.

What I have is:

class Category < ActiveRecord::Base
  has_many :document_categorisations, :autosave => true, :dependent => :destroy
  has_many :documents, :through => :document_categorisations
end

class Document < ActiveRecord::Base
  has_many :document_categorisations, :autosave => true, :dependent => :destroy
  has_many :categories, :through => :document_categorisations
end

class Admin::DocumentsController < Admin::ControllerBase
  inherit_resources
  belongs_to :category, :optional => true
end

When I do a DocumentsController#create with a category_id param, the document resource is created but no join model record. The problem is that the create action assumes that
  object = end_of_association_chain.build
  object.save
is the same as 
  end_of_association_chain.create
which is _not_.

As a workaround I have setup a specific create_resource method in my controller:

def create_resource(object)
  @document = end_of_association_chain.create params[:document]
end

But I have to do that for each affected model. It would be better, if you could implement it more generical in inherited_resource.

Best Regards,
Uwe Hees

Oh, please tell me, if I have got something wrong!

**Comment by josevalim** [comment]
You are right, there is not much we can do here. It is rather an ActiveRecord bug. :(

**Comment by uhees** [comment]
What if we had:

def create_resource(object)
   get_resource_ivar ||  
set_resource_ivar(end_of_association_chain.send(:create,  
params[resource_instance_name] || {}))
end

Am 22.03.2011 um 09:54 schrieb josevalim:

**Comment by josevalim** [comment]
Then you would have to specify that the association is a through
association. That would just increase complexity. Besides, calling create
directly is not a solution that would work for everyone mainly because it is
a common pattern to access and change the resource before passing it to
create_resource. If there will be some effort here, I would put on fixing
ActiveRecord.

**Comment by martinstreicher** [comment]
Was there ever a fix in AR that permitted this to work?
