### ISSUE TITLE
release on rubygems

### ISSUE THREAD

**Issue by dmitry-a-l** [activeadmin/inherited_resources#134]
wanted 
also new release of has_scope wanted 

Thank you, José

**Comment by josevalim** [comment]
Which commit do you find relevant in has_scope for a new release? I don't see anything special there. :)

**Comment by dmitry-a-l** [comment]
oops, stupid me :) yes has_scope is relevant

**Comment by josevalim** [comment]
Sorry, I don't follow. :) Which gems do you want me to release and why?

**Comment by dmitry-a-l** [comment]
I need [latest changes of IR](https://github.com/josevalim/inherited_resources/commit/e1a46c1727b8ab8d4e7436690607a8b82136e618), but  I don't like :git => 'git://github.com/....' in Gemfile. So I want new IR release
