### ISSUE TITLE
singelton and optional on polymorphic_belongs_to doesnt work together

### ISSUE THREAD

**Issue by quorak** [activeadmin/inherited_resources#136]
I have a controller which i want to use as optional and a singelton for a polymorphic_belongs_to relation.

Making it

``` ruby
class Customer::CustomersController < AdminController
  inherit_resources
  polymorphic_belongs_to :ticket_ticket, :parent_class => ::Ticket::Ticket, :singleton=>true, :optional=>true
  polymorphic_belongs_to :customer_order, :parent_class => ::Customer::Order, :singleton=>true, :optional=>true
end
```

gives me a 

``` ruby
  undefined method `customer' for #<Class:0x00000107c74540>
```

when calling 
http://localhost:3000/admin/customer_customers/2

singelton calls are working fine e.g.:
http://localhost:3000/admin/customer_orders/3/customer_customer

changing resource as followed made it working:

``` ruby
def resource
  get_resource_ivar || set_resource_ivar(end_of_association_chain.is_a?(Class) ? end_of_association_chain.find(params[:id]) : end_of_association_chain.send(resource_instance_name))
end
```

best

**Comment by josevalim** [comment]
Could you please try a patch with tests?

**Comment by pirtlj** [comment]
did this ever get resolved, i have the same issue

**Comment by josevalim** [comment]
No. And it likely won't until someone provides a test reproducing the issue or, even better, a pull request.
