### ISSUE TITLE
Problem with rspec and mock_model

### ISSUE THREAD

**Issue by lucassus** [activeadmin/inherited_resources#137]
I'm trying to stub models in my rspec tests for InheritedResource controller and I'm getting the following error:

```
  1) Admin::BranchesController on POST to :create with invalid attributes it should behave like unsuccessful InheritedResources :create action 
     Failure/Error: Unable to find matching line from backtrace
     NoMethodError:
       undefined method `school_branches_url' for #<Admin::BranchesController:0x000000041b7e80>
     Shared Example Group: "unsuccessful InheritedResources :create action" called from ./spec/controllers/admin/branches_controller_spec.rb:61
     # ./spec/controllers/admin/branches_controller_spec.rb:58:in `block (4 levels) in <top (required)>'
```

Instead school_branches_url it should be admin_school_branches_url
With real models it work without any problems. More details you can be found at https://gist.github.com/936947

**Comment by josevalim** [comment]
If it works with real models, isn't this rather an rspec mock_model bug? Can you provide a failing test case to INherited Resources suite?
