### ISSUE TITLE
custom get_by_id

### ISSUE THREAD

**Issue by janlimpens** [activeadmin/inherited_resources#138]
Hello,

I am assuming, that the (scoped) get/:id action calls model.get_by_id, right?

Is it somehow possible to tell ir to use another action, based on the model?

I have mongoid documents and they use mongoid::slug, which also passes the slug as id to the routes. So instead of a working /model/123 I get a /model/some-slug, but now my inherited resources stopped working, because it (supposedly) uses get_by_id, instead of the supplied get_by_slug. I probably could monkey patch my models to alias get_by_id with get_by_slug, but I am sure there are dozens of edge cases, which I would not want to take care of, if someone else more talented than I already did...

**Comment by dbkbali** [comment]
Try this override in the inherited resource controller:
 protected
    def resource
      @activity ||= end_of_association_chain.find_by_slug(params[:id])
    end
If you need further information suggest you look at lines 29 to 46 of lib/inherited_resources/base_helpers.rb file!

I dont think this is a bug! or an issue that cannot already be addressed by an override

**Comment by janlimpens** [comment]
Very cool, thanks!

I did not think this was a bug either, but this is the correct channel for
this kind of questions, right?

On Sun, May 1, 2011 at 12:50 PM, dbkrett <
reply@reply.github.com>wrote:

> Try this override in the inherited resource controller:
>  protected
>    def resource
>      @activity ||= end_of_association_chain.find_by_slug(params[:id])
>    end
> If you need further information suggest you look at lines 29 to 46 of
> lib/inherited_resources/base_helpers.rb file!
> 
> I dont think this is a bug! or an issue that cannot already be addressed by
> an override
> 
> ## 
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/josevalim/inherited_resources/issues/138#comment_1083502

## 

Jan

http://limpens.com

**Comment by AndreiMotinga** [comment]
dbkbali's solution almost worked for me, just had to add call to `super`, and only use this for models that need it. 
```
    def resource
      if resource_class.included_modules.include?(Sluggify)
        @activity ||= end_of_association_chain
          .any_of({slug: params[:id]}, {id: params[:id]}).first
      end
      super
    end
```
