### ISSUE TITLE
methods exposed to web

### ISSUE THREAD

**Issue by jo** [activeadmin/inherited_resources#14]
make_resourceful adds many methods as action_methods, that is public methods available via web.

I forked this project (http://github.com//jo/make_resourceful/) with a commit to hide those methods (http://github.com/jo/make_resourceful/commit/68e3e4a229e9363eba04388540818e68220194db)

Maybe on finds a better solution for that.

**Comment by josevalim** [comment]
Sorry. Are you sure that you are on the right issue tracking?

**Comment by jo** [comment]
The Sorry is mine. You're right!
this one belongs to make_resourceful.

Excuse,
Johannes

**Comment by josevalim** [comment]
Closing ;)
