### ISSUE TITLE
Inherited controllers not inheriting ApplicationController methods

### ISSUE THREAD

**Issue by strangeement** [activeadmin/inherited_resources#144]
I'm sure I'm doing something wrong here but I noticed similar issues with InheritedResources controllers not being able to properly use ApplicationController methods or blocks. I'm still pretty new to Rails but here it goes.

Specifically, I'm implementing CanCan and trying to use rescue_from for AccessDenied exceptions. If I put the rescue_from block in ApplicationController, it is ignored. The exact same block works if I put it instead in the controller with load_and_authorize_resource.

Since InheritedResources::Base inherits from ApplicationController, it should be able to work with the rescue_block from ApplicationController, right?

**Comment by thedarkone** [comment]
Hey, just a shot in the dark... have you tried restarting the server?

**Comment by StrangeElement** [comment]
That's it! ApplicationController is not reloaded on page reloads, the server has to be restarted. TIL!

Thanks.

**Comment by thedarkone** [comment]
This is not by design, it's a bug: #95.
