### ISSUE TITLE
make it working with accepts_nested_attributes_for

### ISSUE THREAD

**Issue by pss4281** [activeadmin/inherited_resources#146]

**Comment by virtualfunction** [comment]
Not sure if you've worked round this, but I had to use this 2 days ago.

It should work fine as it is with nested model attributes.

In your views you need to use `form.fields_for :association, :as => :association_attributes do |field|` where "association" is replaced with the association name.

In some cases where you have a 'has_one' relation you might need to have some trickery ... for example:

Where a model `has_many :addresses, :dependent => :destroy`, but `has_one :shipping_address, :class_name => 'Address', :conditions => { :role => 'shipping' }, :dependent => :destroy` (and maybe the same but for billing), you might need to do something like `order.build_shipping_address unless order.shipping_address` before your view is rendered.
