### ISSUE TITLE
Inherited resources not finding documents.

### ISSUE THREAD

**Issue by laspluviosillas** [activeadmin/inherited_resources#147]
I'm having a very strange problem where inherited-resources won't find my mongodb (mongoid as orm) documents. I get the following error:

```
Mongoid::Errors::DocumentNotFound in Sales/adoptionsController#update
Document not found for class Adoption with id(s) 4d7f62867ba3473aae000681.
```

However, my document definitely does exist:

```
ruby-1.9.2-p136 :005 > Adoption.find('4d7f62867ba3473aae000681').fee
 => 500 
```

It gets even weirder:

``` ruby
class Sales::AdoptionsController < Sales::BaseController
  inherit_resources
  actions :all, :except => [:edit, :update]

  def edit
    @adoption = Adoption.find(params[:id])
  end

  def update
    @adoption = Adoption.find(params[:id])
  end
```

Defining a custom edit function without inherit_resources works, but update **always** goes through inherited_resources first (breakpoints placed in the update function are never reached and stack shows inherited_resources methods), despite it being on the excludes list.

I'm using the following gem versions:

``` ruby
'mongoid', '~> 2.0.0.beta.20'
'inherited_resources', '~> 1.2.2'
```

And I'm using standard routes, nothing custom.

``` ruby
namespace :sales do
    resources :adoptions
end
```

Any ideas?

Thanks,
James.

EDIT: I'm using an old beta version of mongoid. I haven't been able to update because updating breaks all of my tests. Could this influence the issue?

**Comment by brentkirby** [comment]
This is a mongoid problem... see here: https://github.com/mongoid/mongoid/pull/1001
