### ISSUE TITLE
Setting :optional => true will always return `parent?` as false

### ISSUE THREAD

**Issue by fredwu** [activeadmin/inherited_resources#148]
``` ruby
class ChildController < ApplicationController
  inherit_resources
  belongs_to :parent
end
```

``` ruby
class ChildController < ApplicationController
  inherit_resources
  belongs_to :parent, :optional => true
end
```

In the second scenario, no matter whether or not there is a parent, `parent?` always returns `false` and the other helpers (such as `parent` and `parent_class`) always return `nil`.

I would've attempted to add tests and submit a patch but the current master is broken. :(

**Comment by josevalim** [comment]
Test suite has been fixed!

**Comment by fredwu** [comment]
Thanks Jose! I just checked the test suite, they run fine on Rails 3.0, but on 3.1 they error out, I suspect my issue is actually related to 3.1's compatibility.

**Comment by josevalim** [comment]
I have updated the Gemfile.lock to 3.1.0.rc4 and made the test suite pass.
