### ISSUE TITLE
Mountable app namespace issue

### ISSUE THREAD

**Issue by tb** [activeadmin/inherited_resources#150]
I got exception ArgumentError in Kb::Admin::SectionsController#index in a mountable app namescoped controller with message:

"Kb is not missing constant Section!"

Trace leaded to:

```
vendor/inherited_resources/lib/inherited_resources/class_methods.rb:285:in `initialize_resources_class_accessors!'
vendor/inherited_resources/lib/inherited_resources.rb:41:in `inherit_resources'
app/controllers/application_controller.rb:6
```

Fix:
I could not use "defaults Kb::Section" as the module was not mixed because of the error
so I come up with is this: https://github.com/tb/inherited_resources/commit/b21aa27b218aa831592a449e554a2361bfc39d6f

This allows me to define:

```
class_attribute :resource_class
self.resource_class = Kb::Section
```

before calling "inherit_resources", which solves the problem ;)

**Comment by josevalim** [comment]
We can fix this issue by simply checking the rescue:

https://github.com/tb/inherited_resources/blob/b21aa27b218aa831592a449e554a2361bfc39d6f/lib/inherited_resources/class_methods.rb#L294

To also rescue errors like "Kb is not missing constant Section!". Similarly
to:

https://github.com/rails/rails/blob/master/actionpack/lib/action_controller/metal/params_wrapper.rb#L150

**Comment by tb** [comment]
Updated patch at https://github.com/tb/inherited_resources/commit/f4b2fca2993a0f6b6fc481376a24d36f875ea0d9

EngineName::Admin::ArticlesController is conveted into resource_class = EngineName::Article

**Comment by josevalim** [comment]
This updated patch looks good. Could you please send a pull request with tests? Tks!
