### ISSUE TITLE
Support for Rails 3.1 mass_assignment

### ISSUE THREAD

**Issue by virtualfunction** [activeadmin/inherited_resources#151]
Hi, I assume this is on the table at some point ... Support for Rails 3.1 mass assignment roles would be nice, 

My guess is that you will need to have a protected method like `assignment_role` which returns the symbol/role used for mass assignment (this will be set to :default by default), or be able to set this at the class level. eg: `defaults :assignment_role => :admin` (This I way would also need to support a proc, should it be the case that the role is set by data held in the user/permission tables/objects rather than set statically in code).

On a semi-related side note Jose, have seen: http://ablogaboutcode.com/2011/05/12/activerecord-3-1-mass-assignment-roles/

I do sort of agree with him that the multiple hash table arguments approach is ugly, and in some ways semantically wrong (I prefer the idea of something like an "as" method, for a chunk of code you'd want to assign under a set role for the new/create/attributes=/update_attributes methods, in the much the same way scopes currently work in Rails 3.x)

**Comment by ches** [comment]
I landed here from a search on how to handle mass assignment roles with `inherited_resources`, which as far as I can tell isn't documented anywhere yet, and this ticket was closed without reference. For sake of anyone else, the answer is a `with_role :admin` class method, introduced in 79d4c1e00f890bed3807c1fa50fc179eec97c810.

**Comment by amalagaura** [comment]
is there any more documentation on the with_role?  Doesn't setting it en masse defeat the purpose ?  Don't we want the controller to set this based on lets say the user accessing it?  Anyway for me, this will work since I have an admin controller which has a filter to only allow admins.

**Comment by latortuga** [comment]
+1 for taking another look at this issue. I'm using this gem via the active_admin gem and there's not really a good way to support the mass assignment protection without `with_role` supporting a run-time check.

**Comment by amalagaura** [comment]
It should simply allow a block or proc.  I believe the block will have access to the current_user and the role for assignment can be assigned in that way.

**Comment by igorbernstein** [comment]
A bit late of an answer but:
why not just override the methods: role_given? and as_role in base_helpers.rb

**Comment by latortuga** [comment]
@igorbernstein that's actually exactly how I ended up solving the problem :)
