### ISSUE TITLE
using InheritedResources breaks observers when config.cache_classes = false ( eg development env)

### ISSUE THREAD

**Issue by kirillrdy** [activeadmin/inherited_resources#156]
Using Inherited resource breaks cache_sweeper ( subclass of observer )
it only breaks when config.cache_classes = false ( eg development env)
and only when using InheritedResources

here is a simple app to reproduce an error
https://github.com/kirillrdy/insanity2

There is a cache_sweeper that observes Post, and creates corresponding comment for each post created.
it works only for first request fresh rails server ( just started )
for all subsequent requests it will not work

Also, we are using cache_sweepers as observers because they give us reference to controller instance, which we need in our callbacks ( not in the sample app )

See failing test

regards,
Kirill R

**Comment by lacco** [comment]
Any progress on this issue? It seems that inherited_resources causes the same problems at my application...

**Comment by lacco** [comment]
Just a quick note: I tried
`class MyController < ApplicationController; inherit_resources; end`
instead of
`class MyController < InheritedResources::Base; end`
and that seems to work. I will have a closer look on this tomorrow...

**Comment by kirillrdy** [comment]
@lacco thanks, I'll give that a try

**Comment by kirillrdy** [comment]
just an update,
I did full bundle update in my sample app and the issue disappeared.
Happy coding.
