### ISSUE TITLE
MissingTemple after overriding create action

### ISSUE THREAD

**Issue by kevynlebouille** [activeadmin/inherited_resources#159]
Hi,

When i override default create action to change redirect_to like that :

```
def create
  create! { new_admin_magic_item_url }
end
```

I got ActionView::MissingTemplate exception if my resource has errors (failed validations)

```
ActionView::MissingTemplate (Missing template admin/magic_items/new with {:handlers=>[:erb, :rjs, :builder, :rhtml, :rxml, :arb], :formats=>[:html], :locale=>[:fr, :fr]} in view paths [...]): app/admin/magic_items.rb:4:in `create'
```

Any idea where i'm doing wrong ?

**Comment by josevalim** [comment]
You need to have the new template.

**Comment by kevynlebouille** [comment]
But when i don't override create action, everything it's OK...

**Comment by kevynlebouille** [comment]
Seems to be related to ActiveAdmin gem what i use for my project. Sorry
