### ISSUE TITLE
Problem with Clearance Integration

### ISSUE THREAD

**Issue by millisami** [activeadmin/inherited_resources#16]
In my app, I'm using Clearance as my Auth purpose. I'm trying to use IHR. 
For the model association, 

<pre>
#user.rb
has_many :masterpieces, :dependent => :destroy
#masterpiece.rb
belongs_to :user
</pre>

Masterpiece controller:

<pre>class MasterpiecesController < ApplicationController
  before_filter :authenticate, :except => [:show, :index]
  def index
    @masterpieces = Masterpiece.all
  end
  def new
    @masterpiece = current_user.masterpieces.build
  end
  def create
    @masterpiece = current_user.masterpieces.build(params[:masterpiece])
    respond_to do |format|
      if @masterpiece.save
        flash[:notice] = 'Masterpiece was successfully created.'
        format.html { redirect_to(@masterpiece) }
        format.xml  { render :xml => @masterpiece, :status => :created, :location => @masterpiece }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @masterpiece.errors, :status => :unprocessable_entity }
      end
    end

  end
  def show
    @masterpiece = current_user.masterpieces.find(params[:id])
  end
end
</pre>

Now when I replace this controller with this version using IHR:

<pre>
class MasterpiecesController < InheritedResources::Base
  before_filter :authenticate, :except => [:show, :index]

  respond_to :html, :js
  belongs_to :user

  protected

  def begin_of_association_chain
    current_user
  end
end
</pre>

And I go to /masterpieces/new
I get the following error:

<pre>
 NoMethodError in MasterpiecesController#new

undefined method `users' for #<User:0xaccf808>
</pre>

**Comment by carlosantoniodasilva** [comment]
Hello!

Actually I think you don't need to declare "belongs_to :user" in your controller, since "begin_of_association_chain" already tell masterpieces will be filtered only by the current_user. Please try removing this belongs_to.

Carlos.

**Comment by millisami** [comment]
By removing that belongs_to :user, it works.

**Comment by josevalim** [comment]
Thanks Carlos for handling this!
