### ISSUE TITLE
optional nested routes don't generate optional non-nested helpers?

### ISSUE THREAD

**Issue by tribalvibes** [activeadmin/inherited_resources#162]
``` ruby
resources :users, only: [:index, :edit]  do
  resources :biscuits
end

class BiscuitsController < InheritedResources::Base
   belongs_to :user, optional: true
end
```

This seems to generate `user_biscuits_path`, `new_user_biscuits_path`, etc. but not `biscuits_path`, `new_biscuits_path`, etc. ??

Also please document what is the purpose of `:shallow` ?   Example?

Unfortunately this gem and Rails "resourceful" routing is becoming a major bottleneck to productive development today, instead of a benefit.  Sinatra is looking better every day...

**Comment by josevalim** [comment]
As I said in the other issue, the path generation is a Rails concern, not Inherited Resources. So please research Rails docs. We unfortunately do not have docs for shallow in Inherited Resources, pull requests are welcome.
