### ISSUE TITLE
route-polymorphic resource helpers?

### ISSUE THREAD

**Issue by tribalvibes** [activeadmin/inherited_resources#163]
Thanks for your responses--I had browsed `:shallow` as a pull request here and did not realize it was a Rails resourceful route option.  That worked to define the shallow routes, as did simply defining the resource non-nested as well as nested in routes.

Now, here's another need for the `xxx_resource_path` helpers (this is an IR issue no?)  Basically I have a partial that iterates on a collection of resources, but those resources are the optionally nested `Biscuit` kind, nested in `User`. The partial can be called thus from `/users/1/biscuits` or from `/biscuits` and also from `/users/1/edit` where it's included to generate a list of the user's biscuits on the user's profile page (so the resource in that case is the user.)

I want that `resource_path` in the partial generates either the shallow path or the fully qualified path, depending on how the request came in, and without specifying all the parent objects if it is nested.  This is more fully described here:
http://stackoverflow.com/questions/7158377/render-a-polymorphic-partial-with-optional-belongs-to-nested-inherited-resources

This is killing some hours for me to do something so ridiculously simple. I'm considering it an investment in IR, but I'm increasingly feeling that Rails and opaque DSLs are a waste of time compared to simple, visible, terse, and comprehensible ruby code paths.

**Comment by josevalim** [comment]
The resource_path is supposed to work fine. If not, consider using optional_belongs_to instead of shallow. I do not have time to currently debug the issue, so if you find issues, please try providing a pull request with fixes and tests.

Yes, using IR is an investment of your time. It may be completely worth, or not.

PS: If you want to continue a conversation, please don't open new issues, use the existing ones.

**Comment by tribalvibes** [comment]
Since I couldn't reopen the issue, I figured you would't get the notice.

I'm using `belongs_to :user optional: true` and had to declare the `Biscuit` as both nested and non-nested in routes. Now things seem set up properly, and `resource_path(biscuit)` in the partial does generate either the fq or shallow path depending on the route.  Now, how to get it to work for the case where the route is to a user, not to biscuits?   `resource_url` is either trying to call or is aliased to `user_url`.  Is there a way to force it to be `user_biscuit_url` so that the common partial works?
