### ISSUE TITLE
Call URLs

### ISSUE THREAD

**Issue by workdreamer** [activeadmin/inherited_resources#165]
I need to use the edit action to respond in multple formats:

class MycontrollerController < InheritedResources::Base
  respond_to :html, :json, :js

  def edit
    respond_to do |format|
        format.html{
          edit!
        }
        format.js{
          @output = Array.new
          @output = {
              :success =>  true,
              :customer => @customer.find(params[:id])
          }
          render :json => @output.to_json
        }
    end
  end

now i need to call with the url:
to repond for html is: http://localhost:3000/mycontroller/1/edit
and how for js?

I really appreciate the help!

**Comment by joelmoss** [comment]
This is a question about Rails, and not IR. But you should be able to call http://localhost:3000/mycontroller/1/edit.js
