### ISSUE TITLE
URL Helpers

### ISSUE THREAD

**Issue by umerkulovb** [activeadmin/inherited_resources#166]
Hello everyone!
Sorry for my Endlish))

I have problems with collection_path helper. All my controllers are inherited from base SitesController, where I check user authentication and inherit them from InheritedResources::Base.

class SitesController < InheritedResources::Base

Then in my other controller TasksController I'm trying to access collection_url, that returns me (after update to v 1.3) project_checklist_sites_path, but it must be project_checklist_tasks_path (was in v. 1.2.)

class TasksController < SitesController
    belongs_to :project do
        belongs_to :checklist, :ticket, :polymorphic => true  
    end
end

Could anyone help me?

**Comment by DouweM** [comment]
Add this to your `TasksController` class definition:

```
defaults :resource_class => Task
```

Your problem is caused by inherited_resources not respecting subclasses of controllers, as described in #174.

**Comment by joelmoss** [comment]
Duplicate of #174
