### ISSUE TITLE
Optional, singleton and the index action.

### ISSUE THREAD

**Issue by eloyesp** [activeadmin/inherited_resources#169]
If making an optional singleton action, index action is lost. I think it could be fixed adding an if in [this line](https://github.com/josevalim/inherited_resources/blob/master/lib/inherited_resources/class_methods.rb#L270), but I'm not sure how to do it or if it should be fixed.

My situation is that I have this routes:

``` ruby
  resources :lots do
    resource :contract
  end

  resources :contracts
```

What you think?

**Comment by josevalim** [comment]
Singleton resources do not generate the index action, not even in the router. If this is your case, I recommend you to add the action yourself. It is just few lines of code. Thanks!

**Comment by eloyesp** [comment]
Done that. thanks.

**Comment by futbolpal** [comment]
If anyone is curious, this seems to be working for me

```
module OptionalSingleton
    extend ActiveSupport::Concern

    included do  
        def index 
            super 
        end 
    end 

    def collection 
        get_collection_ivar || begin 
            c = end_of_association_chain 
            if defined?(ActiveRecord::DeprecatedFinders)
                set_collection_ivar(c.is_a?(ActiveRecord::Relation) ? c : c.all)
            else
                set_collection_ivar(c.respond_to?(:scoped) ? c.scoped : c.all) 
            end 
        end 
    end 
end 
```

**Comment by futbolpal** [comment]
added this function also to help with the 'show' action

```
def resource 
    if parent.nil? 
        get_resource_ivar || set_resource_ivar(end_of_association_chain.send(method_for_find, params[:id]))
    else
        get_resource_ivar || set_resource_ivar(end_of_association_chain.send(resource_instance_name))
    end 
end 
```
