### ISSUE TITLE
Is there is a quick way to use another layout?

### ISSUE THREAD

**Issue by gutenye** [activeadmin/inherited_resources#171]
something like this ?

```
class UserController < InheritedResources::Base
   layout 'user'

  def new
     layout 'application'   
     new! 
  end
```

thanks

**Comment by josevalim** [comment]
Please check the rails documentation for the method `layout`. This is a rails thing, not inherited resources.

**Comment by gutenye** [comment]
yes, I know the rails way.

```
def new
   @user = User.new
   render 'new', :layout => 'application'
end
```

But, if  I use the rails way, then I can't use InheritedResources any more. So I want to know whether I can both use InheritedResources and  custom-layout.

**Comment by josevalim** [comment]
You can do `layout "application", :only => :new` at the class level. Or even pass a symbol to specify the layout using a method. Check the layout method docs.

**Comment by gutenye** [comment]
thanks, that helps.
