### ISSUE TITLE
Tests fail and error on 3.1.0rc5 and higher

### ISSUE THREAD

**Issue by Arie** [activeadmin/inherited_resources#173]
I've checked out inherited_resources locally and ran the test suite. It works on 3.1.0rc4 (after running bundle update to compensate for yanked gems), but it fails on 3.1.0rc5 and higher.

The failing tests:
test/nested_model_with_shallow_test.rb:63
test/nested_model_with_shallow_test.rb:70

Tests that error:
test/url_helpers_test.rb:522
test/url_helpers_test.rb:578
test/url_helpers_test.rb:675
test/url_helpers_test.rb:414
test/url_helpers_test.rb:468
test/url_helpers_test.rb:630

The tests stop erroring if I revert this commit on Rails 3.1
https://github.com/rails/rails/commit/9395e89b7235779b1f5c84503442c1ebb7cf0b28

I haven't been able to figure out what causes the failing tests yet.

**Comment by iain** [comment]
It's actually [this commit](https://github.com/rails/rails/commit/9395e89) that Arie is referencing
