### ISSUE TITLE
InheritedResources::Base doesn't respect subclasses

### ISSUE THREAD

**Issue by raskhadafi** [activeadmin/inherited_resources#174]
I had to set "defaults :resource_class => Employee".

I have the following class chain.
InheritedResources::Base > AuthorizedController > PeopleController > EmployeesController

In this example the EmployeesController showed all People.

**Comment by ep-wac** [comment]
This is perfect! Solved my STI problem - thx for sharing!

**Comment by ahacking** [comment]
Why was this closed? Its still broken?!! Subclasses **should** work without having to override defaults.

There is not even a mention of this in the README and its an important enough behaviour wart that it deserves to be covered on the front page where defaults is covered.

**Comment by rafaelfranca** [comment]
It is more a feature request than a bug per si. So I'm closing.
