### ISSUE TITLE
Failure/Error: response.should render_template("new") - expecting <"new"> but rendering with <""> (IR 1.3.0, rSpec 2.6.0)

### ISSUE THREAD

**Issue by salzig** [activeadmin/inherited_resources#176]
Get the following error with rSpec and generated (resource generator) controller tests.

>  Failure/Error: response.should render_template("new") - expecting <"new"> but rendering with <"">

using:
- inherited_resources 1.3.0
- rSpec 2.6.0

anyone with similar problem? Any ideas?

**Comment by hrdwdmrbl** [comment]
https://github.com/josevalim/inherited_resources/issues/38

You must stub the errors. For some reason errors are not being set or read or something, so just stub them and you're get the proper rendering.
