### ISSUE TITLE
Error after update to ruby 1.9.3 with inherited_resources branch v1.0 for rails 2.3.x

### ISSUE THREAD

**Issue by jmcervera** [activeadmin/inherited_resources#178]
Hello.
I have just udated the version of ruby to 1.9.3, and I have this  error as soon as I am trying to access the home page.

Processing ApplicationController#index (for 127.0.0.1 at 2011-10-31 17:16:54) [GET]
  Parameters: {"controller"=>"entradas", "action"=>"index"}

LoadError (cannot load such file -- inherited_resources/base_helper.rb):
  /home/jmcervera/.rvm/gems/ruby-1.9.3-p0@florida/bundler/gems/inherited_resources-900e915851b5/lib/inherited_resources/base.rb:14:in `<module:InheritedResources>'
  /home/jmcervera/.rvm/gems/ruby-1.9.3-p0@florida/bundler/gems/inherited_resources-900e915851b5/lib/inherited_resources/base.rb:4:in`<top (required)>'
  app/controllers/entradas_controller.rb:1:in `<top (required)>'
  sass (3.1.7) lib/sass/plugin/rack.rb:54:in`call'
  internal:prelude:10:in `synchronize'
  /home/jmcervera/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/webrick/httpserver.rb:138:in`service'
  /home/jmcervera/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/webrick/httpserver.rb:94:in `run'
  /home/jmcervera/.rvm/rubies/ruby-1.9.3-p0/lib/ruby/1.9.1/webrick/server.rb:191:in`block in start_thread'

I am using rails 2.3.14 , so I have to use branch v1.0 of inherited_resources

**Comment by nicolasblanco** [comment]
What? You're using Ruby 1.9.3 with Rails 2 ? That should be forbidden :beer: !

**Comment by jescalante** [comment]
This is not from inherited_resources, this is from Rails 2.3.14 with Ruby 1.9.3-p0. Since Rails 2.3.x is not fully supported now I don't know if the core team would be able to fix this (http://groups.google.com/group/rubyonrails-core/browse_thread/thread/81be70a119260e59).

You can hack the solution by adding the file with the module asked, e.g. base_helper.rb, that's the way I did it, but I still looking for the real solution.

Greetings.

**Comment by jmcervera** [comment]
Thank you for the information.
I have downgraded to ruby 1.9.2 and I will be following the issue.

2011/11/22 jescalante <
reply@reply.github.com

**Comment by jescalante** [comment]
I found the problem! I forked rails and request a pull (https://github.com/rails/rails/pull/3745), but they rejected it because 2.3 is no longer mantained... :-/

However if you want, you can fork my repo https://github.com/jescalante/rails/tree/patch-1

Hope it works!

**Comment by jmcervera** [comment]
Hi,
Thank you very much.
I'll try your patch.

Juanma Cervera

2011/11/24 jescalante <
reply@reply.github.com

**Comment by jescalante** [comment]
Hey, I found a less intrusive solution, you can use the original rails, but adding a custom initializer (in config/initializers name it as you want) with a single line: 

MissingSourceFile::REGEXPS << [/^cannot load such file -- (.+)$/i, 1] 

That should do the trick.

**Comment by jmcervera** [comment]
Much better
Thanks

2011/11/25 jescalante <
reply@reply.github.com
