### ISSUE TITLE
Destroy do not show flash message when object.destroy returns false

### ISSUE THREAD

**Issue by sobrinho** [activeadmin/inherited_resources#181]
Using ActiveRecord we can return false from any callback to stop the destroy but IR thinks it's was destroyed and show the success message.

The issue could be simplified by this:

``` ruby
class SomeController < InheritedResources::Base
  def destroy_resource(object)
    false
  end
end
```

Currently I'm using this to workaround the issue:

``` ruby
def destroy(options={}, &block)
  object = resource

  if destroy_resource(object)
    options[:location] ||= smart_collection_url
  else
    options[:location] ||= edit_resource_path
    options[:alert]    ||= t("flash.actions.destroy.alert", :resource_name => resource_class.model_name.human)
  end

  respond_with_dual_blocks(object, options, &block)
end
```

**Comment by josevalim** [comment]
Paaaaaaaatch!

**Comment by sobrinho** [comment]
I trieeeeeeeeeed! :P

But something on responders or maybe with respond_with didn't work.

Note the `options[:alert]` is a [POG](http://desciclopedia.ws/wiki/Programação_Orientada_a_Gambiarras) to fetch the flash message but do not provide any expected fallback.

Removing this gambeta we receive the success message for destroy instead of failure.

**Comment by carlosantoniodasilva** [comment]
I believe that the current implementation expects some error to be added to the model, so IR would consider it a failing destroy case. Just to confirm, are we going to change this?

**Comment by josevalim** [comment]
Charles is correct. I have forgot about this case. Closing.

**Comment by sobrinho** [comment]
oh... who is charles?

**Comment by carlosantoniodasilva** [comment]
Me! =P

**Comment by carlosantoniodasilva** [comment]
Ok, it seems like we're having some problems with the way it works today, by requiring errors to be added to the model to consider a failure destroy scenario. The issue #185 was opened by @derekprior a few hours later relating the same problem.

I don't actually remember why we decided to let it this way, whether there was some drawback or not. After discussing with @josevalim, we believe that there seems to be no real problem to change this to check for destroy return value, so if you or @derekprior want to try out a patch, it'd be welcome :)

Thanks.

**Comment by derekprior** [comment]
I'll give it a shot. I'm trying to wrap my head around what `respond_with_dual_blocks` is actually doing.
