### ISSUE TITLE
Problem with scoped url

### ISSUE THREAD

**Issue by corroded** [activeadmin/inherited_resources#182]
my routes are setup like this:

```
scope :module => "test_base" do
   resources :regression_test
   resources :load_test
end

```

I've set the defaults in my controllers to:

```
defaults :resource_class => LoadTest::TestCase, :collection_name => 'test_cases', :instance_name => 'test_case'
```

but it always returns `test_base_load_test_test_case_path` etc for the resource url. is there a way to tell IR to ignore the scoped module?

**Comment by josevalim** [comment]
https://github.com/josevalim/inherited_resources/blob/master/lib/inherited_resources/class_methods.rb#L6
