### ISSUE TITLE
Smart redirects do not work under rails 3.1 mountable engine

### ISSUE THREAD

**Issue by marcelloma** [activeadmin/inherited_resources#183]
``` ruby
module Pessoas
  class PeopleController < InheritedResources::Base
    actions :all, :except => [:show]
  end
end

Pessoas::Engine.routes.draw do
  resources :people, :except => [:show]
end
```

it seems that its confusing the engine with just a namespace, and collection_url tries to get pessoas_people_url instead of pessoas.people_url

Any thoughts?

**Comment by josevalim** [comment]
Inherited Resources needs to check that the parent module is an isolated engine and properly generate the route then.

**Comment by rafaelfranca** [comment]
This issue is too old. If you have interest on fixing it please submit a pull request.
