### ISSUE TITLE
Destroy reports success when the action fails

### ISSUE THREAD

**Issue by derekprior** [activeadmin/inherited_resources#185]
The output from the call to `object.destroy` is cast aside when determining whether to respond with success or failure. It seems that the only thing driving this decision is `object.errors.empty?` (see https://github.com/josevalim/inherited_resources/blob/master/lib/inherited_resources/base_helpers.rb#L252).

Destroy can fail while errors is non-empty. For instance, a `before_destroy` callback may return `false`. In this case, inherited resources will think the call succeeded because errors is empty.

Shouldn't `respond_with_dual_blocks` also take into consideration the return value from `destroy` (or any operation, really)? Or is it simply poor style to ever fail a delete/write operation without adding to `object.errors`?

**Comment by derekprior** [comment]
Closing as it seems other have opened this issue in the past with the response that something should be added to errors

**Comment by carlosantoniodasilva** [comment]
Yeah, we had basically the same issue opened today a few hours ago :). See #181
