### ISSUE TITLE
Error when running in production

### ISSUE THREAD

**Issue by amaierhofer** [activeadmin/inherited_resources#188]
Hello, 

I have encountered problems when trying to run in production, everything works just fine in development mode. Here is what i am doing. 

```
/tmp❯ ruby -v; rails -v 
ruby 1.9.3p0 (2011-11-08 revision 33661) [x86_64-linux]
Rails 3.1.3

/tmp❯ rails new sample && cd sample
/tmp/sample❯ echo "gem 'inherited_resources'" >> Gemfile

/tmp/sample❯ sed -i 's/ActionController/InheritedResources/' app/controllers/application_controller.rb
/tmp/sample❯ bundle && RAILS_ENV=production rails s


/home/xxx/.rvm/gems/ruby-1.9.3-head@rails/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:490:in `load_missing_constant': Expected /home/xxx/.rvm/gems/ruby-1.9.3-head@rails/gems/inherited_resources-1.3.0/app/controllers/inherited_resources/base.rb to define InheritedResources::Base (LoadError)
    from /home/xxx/.rvm/gems/ruby-1.9.3-head@rails/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:181:in `block in const_missing'
    from /home/xxx/.rvm/gems/ruby-1.9.3-head@rails/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:179:in `each'
    from /home/xxx/.rvm/gems/ruby-1.9.3-head@rails/gems/activesupport-3.1.3/lib/active_support/dependencies.rb:179:in `const_missing'
    from /tmp/sample/app/controllers/application_controller.rb:1:in `<top (required)>'
```

Can  somebody help me understand what's going wrong and how this can be fixed?

**Comment by josevalim** [comment]
It works here. Do you have Bundler.require in your config/application.rb?

**Comment by amaierhofer** [comment]
Strange .. the sample app only contains what is generated by rails. The bundler related section looks like this 

```

if defined?(Bundler)
  # If you precompile assets before deploying to production, use this line
  Bundler.require(*Rails.groups(:assets => %w(development test)))
  # If you want your assets lazily compiled in production, use this line
  # Bundler.require(:default, :assets, Rails.env)
end
```

**Comment by josevalim** [comment]
Weird... thanks for reporting. I will take a look.

**Comment by codez** [comment]
As far as I see, there is a cyclic dependency when inherit_resources is called from ApplicationController (or if ApplicationController inherits from InheritedResources), as InheritedResources::Base inherits from ApplicationController. With class reloading in the development environment, this does not seem to matter, but it crashes in production. 

So InheritedResources should probably not be used in ApplicationController directly.

**Comment by josevalim** [comment]
Your ApplicationController should not inherit from InheritedResources::Base.

**Comment by knoopx** [comment]
> Your ApplicationController should not inherit from InheritedResources::Base

Why not? I mean, it's currently not supported or it's just a functional requirement?

**Comment by josevalim** [comment]
Both.
