### ISSUE TITLE
should not assume a parent if belongs_to is specified

### ISSUE THREAD

**Issue by aaronchi** [activeadmin/inherited_resources#19]
I have an invitations controller that I would like to use both nested as well as unnested. The controller is set up like this:

class InvitationsController < ApplicationController
inherit_resources
belongs_to :league
end

and I am accessing the controller both from /leagues/{id}/invitations and /invitations

Since inherited_resources always assumes a parent if belongs_to is defined, it throws an error trying to find the parent league when I access the unnested route. Instead, it should check for the presence of the parent_id first and only load the parent if it exists.

**Comment by josevalim** [comment]
Use belongs_to :league, :optional => true.
More info in the README.
Thanks!
