### ISSUE TITLE
Attempting to get redirect path for XHR requests

### ISSUE THREAD

**Issue by ClayShentrup** [activeadmin/inherited_resources#205]
Say I have PersonController, and I do a create on a Manager (where Manager inherits from person). This will cause an error  because there is no manager_path.

Makes sense, right?

But this happens EVEN if I do it as an XHR create. In which case it seems like a bug to try to create the redirect path even when no redirect should be happening.

Thank you.

**Comment by joelmoss** [comment]
Please reopen this issue with some code to show us what is happenning, along with any backtraces? thx

**Comment by ClayShentrup** [comment]
Are you saying you tried the most basic implementation of inheritance as I described, and you couldn't reproduce the bug??

**Comment by joelmoss** [comment]
No. I'm saying I need more info from you in order to investigate further.

**Comment by ClayShentrup** [comment]
```
class EmployeesController < InheritedResources::Base
end
```

If you do a create on a new employee, whose type is "Manager" (Single Table Inheritance), then it will create an instance of Manager, and will try to redirect to to manager_path instead of employee_path. Which will of course fail, as one would expect. But if you do an XHR request, there's no redirect needed, so it doesn't need to compute the redirect path. So XHR should work fine, but it doesn't. It seems pretty probable to me that the problem is, it's unconditionally computing the redirect path.
