### ISSUE TITLE
belongs_to "Couldn't find <model> without an ID"

### ISSUE THREAD

**Issue by nahue** [activeadmin/inherited_resources#206]
It seems that the associations are not working between namespaces.. here is a simplified version of my controller and the involucred models.

Resources Controller:

``` ruby
class Admin::ResourceController < Admin::ApplicationController
  inherit_resources

  respond_to :html
  has_scope :page, default: 1
  self.responder = Admin::Responder
end
```

Courses controller:

``` ruby
class Admin::CoursesController < Admin::ResourceController
    belongs_to :certification
end
```

Models:

``` ruby
class Course < ActiveRecord::Base
        belongs_to :certification
end
```

``` ruby
class Certification < ActiveRecord::Base
        has_many :courses  
end
```

Maybe its looking for the Admin::Certification model? i dont know!

**Comment by philipcunningham** [comment]
Did you have any luck with this? I'm having similar issues.

**Comment by joelmoss** [comment]
Can you try removing the `#has_scope` and `self.responder` lines and see if you have issues still?

**Comment by risinglf** [comment]
Hello there, I have the same issue. Do you know how this can be solved? Thanks!
