### ISSUE TITLE
redirect show action

### ISSUE THREAD

**Issue by wjlroe** [activeadmin/inherited_resources#207]
There doesn't appear to be a way to redirect the show action.

I want to do something of the sort:

``` ruby
def show
  show! {
    if request.path != user_path(@user)
      redirect_to user_path(@user), :status => :moved_permanently
    end
  }
end
```

Basically redirecting a surrogate ID to the slug. I tried returning the user_path, but whatever I do I get an error indicating show! ran render after the redirect: `AbstractController::DoubleRenderError`

How can I do this - use both friendly_id redirecting and inherited_resources?

**Comment by josevalim** [comment]
Yes, because the show action never redirects by default. The redirect block only works for actions that redirect at some point.
