### ISSUE TITLE
acts as tree support (self association)

### ISSUE THREAD

**Issue by sobrinho** [activeadmin/inherited_resources#21]
Hello,

I tried to use inherited resources with acts_as_tree without success. An example:

<pre><code>class Page < ActiveRecord::Base
  acts_as_tree
end

class PagesController < ApplicationController
  inherit_resources
  respond_to :html
  actions :all
  belongs_to :parent, :optional => true
end

map.resources :pages, :has_many => :pages</code></pre>

When I access http://localhost:3000/pages/3/pages the filter doesn't work.

I got the same behaviour of http://localhost:3000/pages/

You can verify that?

**Comment by josevalim** [comment]
If you give belongs_to :parent, it will look for a :parent_id in the params and call parents in the model. Is this what acts_as_tree API expects?

**Comment by josevalim** [comment]
Closing.

**Comment by me-kirill** [comment]
I have an issue with acts_as_nested_set. An example:

class Page < ActiveRecord::Base
  acts_as_nested_set
end
class PagesController < InheritedResources::Base
  respond_to :html, :json
end
routes:
  resources :pages
end
When I try to open /pages I have an error "No route matches "/pages"..
If I remove   acts_as_nested_set its ok

**Comment by sobrinho** [comment]
The route is show when you run rake routes?
