### ISSUE TITLE
Why inherited_resouces ignores 'defaults' setting

### ISSUE THREAD

**Issue by Bazai** [activeadmin/inherited_resources#210]
I have model:

```
class Sms < ActiveRecord::Base
end
```

And i want controller for it, where i make defaults:

```
class Admin::SmsesController < Admin::InheritedResources
  defaults :resource_class => Sms,
           :collection_name => 'smses',
           :instance_name => 'sms'
end
```

But it still trying to get "Smse" model:

```
NameError in Admin::SmsesController#index
uninitialized constant Smse
```

What's wrong?

**Comment by MSch** [comment]
@Bazai having the same issue, did you figure out what went wrong?

**Comment by Bazai** [comment]
@MSch look first and only answer here, it explains everything:
http://stackoverflow.com/questions/9363807/rails-3-inherited-resources-ignores-defaults-setting
