### ISSUE TITLE
Using attr_accessible in the controller

### ISSUE THREAD

**Issue by joevandyk** [activeadmin/inherited_resources#214]
Rails supports attr_accessible in the controller, which imo, is where it belongs.

What's the best way to get inherited_resources working with attr_accessible?

**Comment by josevalim** [comment]
There isn't afaik. Notice inherited resources has a deprecation notice though, if you are using it and interested in maintaining it, please let me know. :)

**Comment by joevandyk** [comment]
man, i just found inherited_resources like two weeks ago and it's already deprecated.  I can't keep up. :)

**Comment by rafaelfranca** [comment]
Closing this one
