### ISSUE TITLE
Memoizable resource_params

### ISSUE THREAD

**Issue by atd** [activeadmin/inherited_resources#216]
The resource_params method in InheritedResources::BaseHelpers is:

``` ruby
def resource_params
  rparams = [params[resource_request_name] || params[resource_instance_name] || {}] 
  rparams << as_role if role_given?
  rparams
end
```

A new hash is created when params is blank. However, this prevents generic manipulation of the parameters with before_filters, for example for setting the author of a post. This is because the hash is created again in build_resource

I think memoize resource_params would be valuable. What do you think?

**Comment by rafaelfranca** [comment]
Hey @atd. We are not maintain this project anymore (See the deprecation notice in the README). If you or anyone want to maintain it, please let us know.

**Comment by atd** [comment]
I'd love to, but I can't :-(

Thanks for your work

**Comment by joelmoss** [comment]
@atd I'm resurrecting inherited_resources. You wanna create a pull request for this?
