### ISSUE TITLE
Feature request: edit_parent_url

### ISSUE THREAD

**Issue by baldwindavid** [activeadmin/inherited_resources#22]
It would be nice if in addition to "parent_url", there was "edit_parent_url".  Additions/updates to children may often redirect to the edit page of the parent rather than the show. (at least in my apps, but maybe I'm doing it wrong)

Best Regards,
David Baldwin

**Comment by grimen** [comment]
+1

**Comment by josevalim** [comment]
Done.

**Comment by baldwindavid** [comment]
Thanks.  This is handy.
