### ISSUE TITLE
Eager Loading

### ISSUE THREAD

**Issue by hrdwdmrbl** [activeadmin/inherited_resources#222]
How do I use eager loading when I'm using inherited_resources? 

The only solution I can see is to use "default_scope :includes(:foobar)", but that will always eager load, even when I have a nested resource such as /foos/1/bars/1. In the case of a specific nested resource, I might not always want to eager load :foobar since it might only get access on the index page. But on the index page, I'll most certainly want to eager load foodbar since I might access it on every record.

**Comment by joelmoss** [comment]
This should do the trick...

```
class ProjectsController < InheritedResources::Base
  protected
    def collection
      @projects ||= end_of_association_chain.includes(:foobar)
    end
end
```

Please check the README for more.

**Comment by hrdwdmrbl** [comment]
Better solution:

has_scope :foobar, :only => :index, :type => :boolean, :default => true

MODEL.rb
scope :foobar, includes(:foobar)

**Comment by joelmoss** [comment]
Or that ;)
