### ISSUE TITLE
when controller inherited from a basecontroller,the resource_class is the supper class

### ISSUE THREAD

**Issue by chengdh** [activeadmin/inherited_resources#225]
i have following code:
BaseController < InheritedResources:Base
CarryingBillsController < BaseController
HandBillsController < CarryingBillsController
ComputerBillsController < CarryingBillsController
also,i have following model class:
CarryingBill < ActiveRecord::Base
ComputerBill < CarryingBill
HandBill < CarryingBill
but when i reuqest ComputerBillsController#create
i found the resource_class return CarryingBill,not ComputerBill,is it a bug?

**Comment by joelmoss** [comment]
Duplicate of #174
