### ISSUE TITLE
Cannot get object from collection

### ISSUE THREAD

**Issue by torsakch** [activeadmin/inherited_resources#227]
I used inherited resources for my application. But in some models, I got the error saying that "undefined method `type' for nil:NilClass" in the "collection.each do |resource|" (in view). 

In the full trace:

activerecord (3.2.0) lib/active_record/attribute_methods/time_zone_conversion.rb:57:in `create_time_zone_conversion_attribute?'
activerecord (3.2.0) lib/active_record/attribute_methods/time_zone_conversion.rb:24:in`attribute_cast_code'
activerecord (3.2.0) lib/active_record/attribute_methods/serialization.rb:79:in `attribute_cast_code' 

When I debug my application, I found that I can get the result from "collection.count" but I cannot get the result from "collection.first". The error seems like the object cannot be instantiated from the collection. I don't know why. It's so wired for me. Can you point me out of the problem? Thanks.

**Comment by joelmoss** [comment]
This sounds like a problem with your view, and not the controller. IR has no regard for the view.
