### ISSUE TITLE
Docs: sample for migration to responders

### ISSUE THREAD

**Issue by janlimpens** [activeadmin/inherited_resources#228]
It would be of great help, if you could include a sample of a good migration to responders for each of the default crud actions.

**Comment by joelmoss** [comment]
IR is no longer deprecated, so we won't be creating a migration guide to responders gem. But feel free to add one to the wiki.

**Comment by janlimpens** [comment]
Joel Moss@28/062012:

> IR is no longer deprecated

Interesting, why is that?

## Abraços,

Jan

Jan Limpens
jan@limpens.com
http://limpens.com
Cel: (11) 7909 6066

**Comment by joelmoss** [comment]
Because I still use it, and intend to continue to support it now that I have been given push access.  

## 

Joel Moss

# Develop with Style at http://DevelopWithStyle.com

Call me +44 7791 503309
http://twitter.com/joelmoss
AIM: joelkmoss
Skype: joelmoss.info

**Comment by janlimpens** [comment]
Joel Moss@29/062012:

> Because I still use it, and intend to continue to support it now that I have been given push access.  

That’s good news!
Thanks,

## Cheers,

Jan

Jan Limpens
jan@limpens.com
http://limpens.com
Cel: (11) 7909 6066
