### ISSUE TITLE
Destroy action

### ISSUE THREAD

**Issue by wanderley** [activeadmin/inherited_resources#23]
When I add actions as follow:

> actions :index, :show, :new, :edit, :create, :update
> and try to delete it's delete the field in database. So, it's a bug! I don't want to delete anything.

But, when I add actions like:

> actions :all, :except => [ :destroy ]
> and try to delete it doesn't delete. So, it's correct because I don't want to create destroy action.

Thanks,

**Comment by josevalim** [comment]
Sorry, I could not understand the issue. Can you please explain it again?

**Comment by wanderley** [comment]
Então vai em português mesmo.
Dentro de um controller se eu dizer as actions que quero tipo:
actios :index, :show
ele ainda aceita outras actions como por exemplo update e destroy

Quando eu faço via actions :all, :except => [:updater]
aí funciona.

**Comment by josevalim** [comment]
Wanderley, eu não consegui reproduzi o erro. Inclusive adicionei mais testes na suíte que garantem que tal erro não acontece. :(
