### ISSUE TITLE
:back redirect shortcut in overridden action hangs and then barfs

### ISSUE THREAD

**Issue by danieldkim** [activeadmin/inherited_resources#231]
inherited_resources version: 1.3.1
rails version: 3.2.2

I'm redirecting to :back in an overridden action like so:

```
def destroy
  destroy! { :back }
end
```

It hangs for a really long before spitting out the error:

```
NoMethodError (undefined method `back_url' for #<Organizations::DataAssetsController:0x10f118d88>):
```

Using request.referer instead of :back works, though:

```
def destroy
  destroy! { request.referer }
end
```

The long form also works:

```
def destroy
  destroy! do |format|
    format.html { redirect_to :back }
  end
end
```

**Comment by joelmoss** [comment]
Passing `:back` is not supported. But I'd be happy to accept a pull request if you would like to add support for it.

**Comment by cutalion** [comment]
This works and looks fine.

``` ruby
def destroy
  destroy! { :back }
end

def back_url
  request.referer
end
```
