### ISSUE TITLE
flash messages stopped working after adding spree

### ISSUE THREAD

**Issue by jess** [activeadmin/inherited_resources#232]
I realize this is probably not a bug with inherited resources, but thought some of you might have an idea of what's going on.  

I added spree as a gem to my app that was already using inherited resources.  Before adding spree, flash messages were working fine (both default messages and overridden messages).  

Now neither work (default or overrides).  If I remove spree from Gemfile, they go back to working fine.

I can override with:

```
def create
  create!(:notice => "some message that does not work")
  flash[:notice] => "message that works"
end
```

Anyone got a few ideas to get me started on in the right direction?

I'll post back with any findings if I discover something useful in case someone else runs into it.

**Comment by joelmoss** [comment]
Sounds like this is an issue with Spree, and not IR. Sorry.
