### ISSUE TITLE
Issue using models with has_one association

### ISSUE THREAD

**Issue by kuraga** [activeadmin/inherited_resources#239]
It seems that if we use `belongs_to` then `inherited_collection` ever tries to use `collection`. Am I right?

And what should I do if my `feedback` has _one_ `reply` not many? I have an error in `create`:
`undefined method 'replies' for #<Feedback:0xb325e5a0>` with stack

```
lib/inherited_resources/base_helpers.rb:171:in `end_of_association_chain'
lib/inherited_resources/base_helpers.rb:52:in `build_resource'
lib/inherited_resources/actions.rb:31:in `create'
```

And my `feedback_id` field of the `reply` is `NULL` if I don't use `belongs_to`.

Help Me Please!
Thanks!

**Comment by josevalim** [comment]
Sorry, I no longer maintain Inherited Resources. Try pinging @joelmoss .

**Comment by kuraga** [comment]
I'm sorry very much. I haven't read about polymorphic belongs_to...

**Comment by tsemana** [comment]
@kuraga, could you let me know how you resolved using the `belongs_to` call with a `has_one` association? I am running into the same problem. I see you mention `polymorphic belongs_to`, but I don't have additional models that need the same association.

**Comment by codespore** [comment]
Just add: defaults :singleton => true above your belongs_to statement like so:

```
class RepliesController < InheritedResources::Base
  defaults :singleton => true
  belongs_to :feedback
end
```
