### ISSUE TITLE
changing flash messages based on response format

### ISSUE THREAD

**Issue by blakechambers** [activeadmin/inherited_resources#24]
I still get flash notices when updating a model using js.  I may have missed it in the docs, but is there a way to turn that off?

**Comment by blakechambers** [comment]
BTW, here is my update function currently:
    def update
      update! do |success, failure|
        success.js { 
          flash.discard(:notice)
          render @todo 
        }
      end
    end

**Comment by josevalim** [comment]
No, it's not possible, some people may use it inside their js, but there should be a  config option to change that.
