### ISSUE TITLE
Cannot create instance of a model with attr_readonly properties

### ISSUE THREAD

**Issue by sodabrew** [activeadmin/inherited_resources#247]
I have a model in which I want some properties to be settable only at creation. ActiveModel's attr_readonly defines this behavior.

``` ruby
class Thing < ActiveRecord::Base
  attr_readonly :key
  attr_accessible :value
end

class ThingsController < InheritedResources::Base
  def create
    create! do |success, failure|
      failure.html {
        render :new
      }
    end
  end
end
```

I would expect that upon posting a form and following this code path, create! would correctly perform the initial assignment of key and value, and only subsequent calls to update! would raise errors if there was an attempt to change the key.

Unfortunately create! raises a mass-assign exception right away, preventing me from using attr_readonly as usual.

Am I doing something wrong here, or does inherited_resources actually not support attr_readonly?

**Comment by rafaelfranca** [comment]
If it is mass assignment error you need to put `:key` in the `attr_accessible` list.

**Comment by sodabrew** [comment]
I was under the impression that the first-time creation of an object could set the readonly keys?

**Comment by rafaelfranca** [comment]
Yes, it can, but the error you are getting is not because the attribute is readonly but because it is not allowed for mass assignment.
