### ISSUE TITLE
before action block

### ISSUE THREAD

**Issue by bhh** [activeadmin/inherited_resources#250]
what do you think of something like

``` ruby
def update
  update! do |success, failure, before|
    before do
      # custom
      # i'm thinking of cancan or pundit authorization if available
      # or probably some default values just for this controller (not the model in general, let's say because of namespacing admin and normal users)
      # maybe authorization as a default if available
    end
  end
end
```

i know you can load the model, do something and then call update! but in this case it wouldn't use the association_chain or belongs_to.

let me know if i should try to implement it in general or if it's something you would not approve.

**Comment by carlosantoniodasilva** [comment]
It'll use the association chain if you use `collection` or `resource`, so that you can execute anything you want before calling `update!`. I don't think there's the need to extend the api with more blocks, since this can already be achieved in other ways. Thank you!
