### ISSUE TITLE
Let's bump new version?

### ISSUE THREAD

**Issue by kuraga** [activeadmin/inherited_resources#253]
Hello @josevalim !

Thank you for this gem! It allows to write less code and  controllers are very nice. It's bad that I can't say it about my models...

Gem was undepricated for a year ago. Some fixes were applied. But there is not a new version. Let's bump it? What do you think?

**Comment by josevalim** [comment]
@kuraga, I no longer maintain inherited resources.

@joelmoss, are you planning to release a new gem? If so, let me know if you run into any issues!

Thanks everyone!

**Comment by joelmoss** [comment]
Bumped and released 1.4.0!
