### ISSUE TITLE
Extending InheritedResources::Base or using inherit_resources causes the resource_class variable to have an incorrect value

### ISSUE THREAD

**Issue by lserman** [activeadmin/inherited_resources#256]
I am developing a gem that has InheritedResources as a dependency for the company I work for. I want to be able to include all of the features of InheritedResources::Base, and then override some functionality with my own.

The gem is an Engine with this base controller (so far):

```
module Company
  module Api
    class Base < InheritedResources::Base
    end
  end
end
```

In the Engine's dummy app, I have this controller:

```
class UsersController < Company::Api::Base
  def create
    puts self.resource_class
    super
  end
end
```

This outputs "Company::Api::Base". This is a problem, because the `end_of_association_chain` method uses `resource_class` to perform methods on the resource. Right now, it is trying to do `Company::Api::Base.new(resource_params)` instead of `User.new(resource_params)`, which breaks everything.

If I use:

```
class UsersController < InheritedResources::Base
end
```

Then it works properly. What am I doing wrong here? I understand I can add `defaults :resource_class => User` to my controller, but I feel like that shouldn't be necessary. I dont know why `resource_class` is ever my controller's class instead of the model.

**Comment by elfassy** [comment]
+1

**Comment by elfassy** [comment]
``` ruby
  private

  def self.inherited(base)
    base.resource_class = nil
    super(base)
  end
```

it's only called once on app load

**Comment by atd** [comment]
+1

I also expected the subclasses controllers to just work

`resource_class` is filled up in https://github.com/josevalim/inherited_resources/blob/master/lib/inherited_resources/class_methods.rb#L291

**Comment by ahacking** [comment]
+1 Yep you have to set defaults in subclassed controllers.

The way inherited resources "respond with dual blocks" handing works, it is also very tricky to handle a particular response type in a subclass and have some default behaviour for everything else in your superclass.

I've come to the conclusion Inherited Resources is hurting more that helping with so many of these kinds of issues, name-spaced controllers and url helpers are broken too, so by the time you work around and repair things its easier to just use regular ruby class inheritence to get most of the DRY benefit without the convoluted approach.

**Comment by rafaelfranca** [comment]
This is more a feature request. Since this gem is deprecated and in maintenance-only I'll close.

Thanks.
