### ISSUE TITLE
Calling Document.find with nil is invalid.

### ISSUE THREAD

**Issue by iom00** [activeadmin/inherited_resources#259]
I'm using with mongoid as below

   class PostsController < InheritedResources::Base
    belongs_to :user
   end

and there is error as below

Problem:
  Calling Document.find with nil is invalid.
Summary:
  Document.find expects the parameters to be 1 or more ids, and will return a single document if 1 id is provided, otherwise an array of documents if multiple ids are provided.
Resolution:
  Most likely this is caused by passing parameters directly through to the find, and the parameter either is not present or the key from which it is accessed is incorrect.

what i have to do solve this problem?!

**Comment by joelmoss** [comment]
This is an issue with Mongoid.
