### ISSUE TITLE
Running into bug using inherited_resources with DataMapper

### ISSUE THREAD

**Issue by bnoguchi** [activeadmin/inherited_resources#26]
I am trying out inherited_resources with DataMapper. I found that mimes_for_respond_to resolves to nil. Based on my debugging, I think this is because inherited_resources assumes developers are using the class inheritable attribute methods from ActiveSupport, while DataMapper provides a subset of those methods with a different implementation using the Extlib gem. This results in data being stored using ActiveSupport's write_inheritable_attribute method, but that data can't be accessed because inherited_resources ends up using Extlib's class_inheritable_reader, resulting in mimes_for_respond_to resolving to nil. Not sure how to do a work-around gracefully without messing up other libs that depend on DataMapper's Extlib and ActiveSupport.

**Comment by jeroenvandijk** [comment]
I can confirm InheritedResources (0.9.3) is not working with Datamapper (10.1)

I have quickly tried to redefine the write_inheritable_attribute method, but that didn't work.

**Comment by josevalim** [comment]
Ok, I pushed a fix. It may work, but you will have to wait to 1.0 release.
