### ISSUE TITLE
Resources not honoring after_initialize

### ISSUE THREAD

**Issue by baldwindavid** [activeadmin/inherited_resources#27]
I have a resource that has some accessors created within an after_initialize method...

```
class Project < ActiveRecord::Base
  def after_initialize
    # create method...
  end
  ...
```

In the controller I have the "new" action automatically created with inherited resources.  However, the resource is nil when it hits the "after_initialize".  However, if I explicitly add the new method, everyone works fine...

```
 def new
   @project = end_of_association_chain.new
 end
```

Shouldn't the resource being automatically created with inherited resources also be using end_of_association_chain.new?

BTW - I do have :new listed as an action in the controller, and inherited resources works splendidly almost everywhere

Best regards,
David Baldwin

**Comment by josevalim** [comment]
Yeah, that definitely should work. Can you please add a failing test case?

**Comment by carlosantoniodasilva** [comment]
Are you using after_initialize inside private declaration in your model? after_initialize only works if its protected/public.

**Comment by josevalim** [comment]
Closing. Reopen if it's really an issue.
