### ISSUE TITLE
Specifying controller actions is ignored when nesting resources

### ISSUE THREAD

**Issue by hrdwdmrbl** [activeadmin/inherited_resources#275]
In this example, I have only included the action "index"

```
class ProjectsController < InheritedResources::Base
  actions :index
  belongs_to :user, :optional => true
end

#routes.rb
resources :users do
  resources :projects
end
```

But if I did something like,

```
example.com/users/1/projects/1
```

it will serve me the page.

This is probably a security bug on top of just being wrong. Or am I missing something?

**Comment by rafaelfranca** [comment]
`actions` will only tell if the action will be inherited from the inherited controller, not the actions that can be presented. This kind of permission you have to do in the route definition.

**Comment by hrdwdmrbl** [comment]
> `actions` will only tell if the action will be inherited from the inherited controller

But clearly other actions, like the `show` action, _are_ being inherited from InheritedResources::Base. Perhaps allow an argument on the end like `belongs_to :user, :optional => true, actions: [:index]`

**Comment by rafaelfranca** [comment]
Even if you inherit your controller from ActionController::Base the view will still be rendered. It is not specific from Inherited Resources.

About allow more arguments, the feature set of this gem is frozen and we are in maintenance-only, only critical bug fixes will be made.
