### ISSUE TITLE
begin_of_association_chain not called when inherit_resources is called in controller class scope

### ISSUE THREAD

**Issue by fernandomm** [activeadmin/inherited_resources#276]
I have the following controller which i can't extend InheritedResources::Base because there are some custom things in Rpanel::ApplicationController that i need.

So i call inherit_resources in controller scope.

```
class Rpanel::AccountsController < Rpanel::ApplicationController
  inherit_resources

  protected
    def begin_of_association_chain
      @current_user
    end
end
```

The issue is that begin_of_association_chain is never called. Is there another way to do this?

**Comment by zhkazarosian** [comment]
+1

**Comment by macfanatic** [comment]
Noticing this today as well on version`1.4.1`

**Comment by rafaelfranca** [comment]
It may not be calling because the controller you inherit from may be overriding some action. If you want to see this fixed make sure the problem is on inherited resources and create a sample application reproducing the bug.
