### ISSUE TITLE
[ERROR] products#create (ActionView::MissingTemplate) "Missing template products/create, resource/create, base/create, a...

### ISSUE THREAD

**Issue by Set2005** [activeadmin/inherited_resources#285]
Hi,

```
First, I cannot reproduce this error, only reported using exception_notification following agent, 
```
- HTTP_USER_AGENT                                : Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/6.0; .NET4.0E; .NET4.0C; InfoPath.3; SE 2.X MetaSr 1.0)

Controller:
  def create
    create!{product_path(@product)}
  end

Error:
An ActionView::MissingTemplate occurred in products#create:

  Missing template products/create, resource/create, base/create, application/create with {:locale=>[:en], :formats=>[:js, :html], :handlers=>[:erb, :builder, :slim, :arb]}. Searched in:
- "/home/app/riffbox/releases/20130514095305/app/views"
- "/home/app/riffbox/shared/bundle/ruby/1.9.1/gems/activeadmin-0.6.0/app/views"
- "/home/app/riffbox/shared/bundle/ruby/1.9.1/gems/kaminari-0.14.1/app/views"
- "/home/app/riffbox/shared/bundle/ruby/1.9.1/gems/ckeditor-4.0.4/app/views"
- "/home/app/riffbox/shared/bundle/ruby/1.9.1/gems/twitter-bootstrap-rails-2.2.6/app/views"
- "/home/app/riffbox/shared/bundle/ruby/1.9.1/gems/devise_invitable-1.1.8/app/views"
- "/home/app/riffbox/shared/bundle/ruby/1.9.1/gems/devise-2.2.4/app/views"
  
  actionpack (3.2.13) lib/action_view/path_set.rb:58:in `find'
  actionpack (3.2.13) lib/action_view/lookup_context.rb:109:in`find'
  actionpack (3.2.13) lib/action_view/renderer/abstract_renderer.rb:3:in `find_template'
  actionpack (3.2.13) lib/action_view/renderer/template_renderer.rb:34:in`determine_template'
  newrelic_rpm (3.6.2.96) lib/new_relic/agent/instrumentation/rails3/action_controller.rb:157:in `render_with_newrelic'
  actionpack (3.2.13) lib/action_view/renderer/renderer.rb:36:in`render_template'
  actionpack (3.2.13) lib/action_view/renderer/renderer.rb:17:in `render'
  actionpack (3.2.13) lib/abstract_controller/rendering.rb:110:in`_render_template'
  actionpack (3.2.13) lib/action_controller/metal/streaming.rb:225:in `_render_template'
  actionpack (3.2.13) lib/abstract_controller/rendering.rb:103:in`render_to_body'
  actionpack (3.2.13) lib/action_controller/metal/renderers.rb:28:in `render_to_body'
  actionpack (3.2.13) lib/action_controller/metal/compatibility.rb:50:in`render_to_body'
  actionpack (3.2.13) lib/abstract_controller/rendering.rb:88:in `render'
  actionpack (3.2.13) lib/action_controller/metal/rendering.rb:16:in`render'
  actionpack (3.2.13) lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
  activesupport (3.2.13) lib/active_support/core_ext/benchmark.rb:5:in`block in ms'
  /home/app/.rvm/rubies/ruby-1.9.3-p392/lib/ruby/1.9.1/benchmark.rb:295:in `realtime'
  activesupport (3.2.13) lib/active_support/core_ext/benchmark.rb:5:in`ms'
  actionpack (3.2.13) lib/action_controller/metal/instrumentation.rb:40:in `block in render'
  actionpack (3.2.13) lib/action_controller/metal/instrumentation.rb:83:in`cleanup_view_runtime'
  activerecord (3.2.13) lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
  actionpack (3.2.13) lib/action_controller/metal/instrumentation.rb:39:in`render'
  wicked_pdf (0.9.6) lib/pdf_helper.rb:23:in `render_with_wicked_pdf'
  remotipart (1.0.5) lib/remotipart/render_overrides.rb:14:in`render_with_remotipart'
  actionpack (3.2.13) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  actionpack (3.2.13) lib/action_controller/metal/responder.rb:232:in`default_render'
  actionpack (3.2.13) lib/action_controller/metal/responder.rb:167:in `to_js'
  responders (0.9.3) lib/responders/flash_responder.rb:109:in`to_js'
  actionpack (3.2.13) lib/action_controller/metal/responder.rb:153:in `respond'
  actionpack (3.2.13) lib/action_controller/metal/responder.rb:146:in`call'
  actionpack (3.2.13) lib/action_controller/metal/mime_responds.rb:239:in `respond_with'
  inherited_resources (1.4.0) lib/inherited_resources/base_helpers.rb:269:in`respond_with_dual_blocks'
  inherited_resources (1.4.0) lib/inherited_resources/actions.rb:37:in `create'
  app/controllers/products_controller.rb:10:in`create'

**Comment by rafaelfranca** [comment]
> First, I cannot reproduce this error

If you can't, we can't too.
