### ISSUE TITLE
Flashes appear twice

### ISSUE THREAD

**Issue by allangrant** [activeadmin/inherited_resources#29]
Since updating inherited_resources from 0.9.3 to 0.9.4, all actions are getting two flashes -- one with :notice and one with :success.  Issue is reproducible in base Rails app.

**Comment by allangrant** [comment]
Setting "DO_NOT_SET_DEPRECATED_FLASH" fixes it.  Its being set in set_flash_message! (base_helpers.rb).  I don't understand the point of having this behavior in the base gem, and the deprecation warning in the log/readme doesn't make sense.  Perhaps I'm missing the point somewhere?

**Comment by josevalim** [comment]
Yeah, fixed.

**Comment by allangrant** [comment]
Sweet.  Thanks for the quick fix!
