### ISSUE TITLE
Instead of actual destroying a object, updating a column attribute.

### ISSUE THREAD

**Issue by shrimanwar92** [activeadmin/inherited_resources#293]
I am using inherited resource for my project. I want to override default destroy action. But destroy! actually deletes the resource. What i want is just to update a column to that resource. Something like:

``` ruby
def destroy
  @user = User.find(params[:id])
  @user.update_column(:status, 0)
  redirect_to root_path
end
```

Any help is appreciated.

**Comment by joelmoss** [comment]
Pretty sure you just answered your own question :wink: The code you included should do the trick.
