### ISSUE TITLE
Sending metadata via serializers

### ISSUE THREAD

**Issue by pzuraq** [activeadmin/inherited_resources#296]
Hey, I need to send metadata from search results such as number of results, number of pages, etc. I'm using ActiveModelSerializers and I can do this using the :meta option, but I can't figure out a way to set the options hash in the standard `index` method used in inherited_resources. Is there a way to access the hash from the `collection` method?

**Comment by danielgatis** [comment]
There is my implementation

``` ruby
class Api::V1::BaseController < ApplicationController
   inherit_resources

   def index
       search = collection.limit(limit)
                          .offset(offset)
                          .search q
       meta = {
         total: search.result.offset(0).limit(nil).count,
         limit: limit,
         offset: offset,
         q: q
       }

       index! do |format|
         format.json { render json: { meta: meta, results: ActiveModel::ArraySerializer.new(search.result) } }
       end
   end

end
```

**Comment by pzuraq** [comment]
Ah thanks, that's all I needed :)

**Comment by koloritcm** [comment]
@pzuraq @danielgatis Suggestion of an improved way letting ActiveModelSerializers work as intended and also working nice with will_paginate and has_scope:

``` ruby
def index(options={}, &block)
  options = options.merge( { meta: {
    total_entries: collection.total_entries,
    current_page: collection.current_page,
    total_pages: collection.total_pages,
    per_page: collection.per_page } } )

  index!(options)
end
```
