### ISSUE TITLE
callback before_destroy does not work

### ISSUE THREAD

**Issue by boblin** [activeadmin/inherited_resources#30]
hi,
since version 1.0.0 using of callback before_destroy does not work correctly with inherited_resources.

example:
     git clone git://github.com/akitaonrails/ryanb-15min-blog.git
     git checkout remotes/origin/inherited_resources

config/environment.rb
    config.gem "inherited_resources", :version => "1.0.0"

app/models/post.rb
    class Post < ActiveRecord::Base
      def before_destroy
        false
      end
     end

When I start scrip/server and I try to destroy some of created posts, Post is not destroyed, but I get notice `Post was successfully destroyed.`.

**Comment by josevalim** [comment]
This is how it will work with Rails 3, so returning destroy is not enough, you have to add an error:

def before_destroy
  errors.add_to_base(:invalid)
  false
end

As said here:

http://blog.plataformatec.com.br/2009/12/one-in-three-inherited-resources-has-scope-and-responders/

I should add it to the README though.

**Comment by boblin** [comment]
So it is not a bug, it's a feature :-) 
Thanks Jose!

**Comment by josevalim** [comment]
Updated readme! Thanks!
