### ISSUE TITLE
duplicate belongs_to calls break routing

### ISSUE THREAD

**Issue by seanlinsley** [activeadmin/inherited_resources#306]
As I mentioned in https://github.com/gregbell/active_admin/issues/2386#issuecomment-22468731, this code breaks:

``` ruby
ProjectsController < InheritedResources::Base
  belongs_to :user
  belongs_to :user
end
ProjectsController.parents_symbols # => [:user, :user]
ProjectsController.new.send :new_resource_path
# NoMethodError: undefined method `new_user_user_project_path'
```

The solution seems to be to change [this line](https://github.com/josevalim/inherited_resources/blob/ae1516a3f1a01f98beac3334f76831a1c793c521/lib/inherited_resources/class_methods.rb#L167) to something like this:

``` ruby
parents_symbols << symbol unless parents_symbols.include? symbol
```

Either that, or change `parents_symbols` to be a Set instead of an Array: http://www.ruby-doc.org/stdlib-2.0/libdoc/set/rdoc/Set.html

**Comment by stereoscott** [comment]
:+1:

**Comment by seanlinsley** [comment]
Hmm, seems I didn't [read the docs](https://github.com/josevalim/inherited_resources/blob/cf9c44845c6af46739978fdca8ed06ea840d01a1/README.md#nested-belongs-to)
