### ISSUE TITLE
Calling inherit_resources in a controller doesn't initialize responders

### ISSUE THREAD

**Issue by eugenebolshakov** [activeadmin/inherited_resources#31]
If I do 

```
class PostsController < ApplicationController
  inherit_resources
end
```

intead of subclassing InheritedResources::Base responders don't seem to work (e.g. flash messages are not set). I'm not really familiar with the internals of IR/Responders, but after a quick look, it appears that this line http://github.com/josevalim/inherited_resources/blob/master/lib/inherited_resources/base.rb#L42 makes the difference. If I add it to my controller like this:

```
class PostsController < ApplicationController
  inherit_resources
  self.responder = InheritedResources::Responder
end
```

flash messages at least start working.

Hope it makes sense. Thanks!

**Comment by josevalim** [comment]
Touchez! It makes sense!
Sorry, it most have taken a lot of time for you to debug and find the error. Expect a new gem in a couple minutes.

**Comment by josevalim** [comment]
1.0.1 released.

**Comment by eugenebolshakov** [comment]
Wow! Hey Jose, thanks for such an amazingly fast response/fix. It's working!
