### ISSUE TITLE
Bug in create redirect url

### ISSUE THREAD

**Issue by paulofelisbino** [activeadmin/inherited_resources#310]
This code breaks if the form is submitted with errors:

> /\* redirect to edit page after creation */
>     def create
>         create!(:notice=> "Custom message"){  edit_os_path(@os)  }
>     end

Why?

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
