### ISSUE TITLE
Suggestion: update controller extensions to be concerns

### ISSUE THREAD

**Issue by tristanm** [activeadmin/inherited_resources#319]
Hey guys, just a suggestion for the future of IR that you may have already considered.

Perhaps IR could be reimplemented using `ActiveSupport::Concern` rather than the current options of inheriting from `InheritedResources::Base` or calling `inherit_resources`? It seems to be a good candidate for a concern and the future of Rails extensions seems to be trending this way. It's never seemed "correct" to me to inherit from `InheritedResources::Base` and I always use `inherit_resources` because I usually have a reasonably complex controller class inheritance structure anyway.

Implemented as a concern, IR could be used like:

```
class PeopleController < ApplicationController
  include InheritedResources::Concern # or whatever it'd be called
  # other IR configuration here...
end
```

I'm certain there will be many things I haven't considered but, especially with concerns being encouraged in Rails 4, perhaps this might be a worthy exercise?

I'm considering forking the project and giving it a go so any feedback now would be appreciated... just in case it'd be considered a waste of time.

**Comment by rafaelfranca** [comment]
The feature set of this project is frozen. We don't take any new feature request. Thanks
