### ISSUE TITLE
Not compatible with MongoMapper (Validations plugin)

### ISSUE THREAD

**Issue by IvanUkhov** [activeadmin/inherited_resources#32]
Hello.

I'm trying to use this great plugin with MongoMapper. After destroy action InheritedResources calls 'has_errors' method after destroying and freezing the record. But have a look at this line:

http://github.com/jnunemaker/validatable/blob/master/lib/validatable/errors.rb#L59

Validations is used by MongoMapper... So plugin is trying to set instance variable when the instance is already frozen.

I don't think it is a bug of IR, but the author of Validations and MongoMapper doesnt what to fix this issue.

Best regards,
Ivan Ukhov.

**Comment by josevalim** [comment]
Sorry, but I do not understand the error. record.errors.empty? is all that IR does, and it should work in any case.

**Comment by IvanUkhov** [comment]
so when the record is already destroyed (like @article.destroy), it is frozen, so can't be modified. when IR calls record.errors, it initializes an instance variable (@errors ||= ....), that method does this, so it modifies the record...

**Comment by IvanUkhov** [comment]
is it necessary to check errors after destroy?

**Comment by josevalim** [comment]
Yes, it's necessary. This is definitely a MongoMapper bug for me:

```
record.destroy
record.errors # raises an error! wtf!?
```

You can quick hack your MongoMapper to ensure it works. Doing this somewhere might fix it:

```
def destroy
  errors
  super
end
```

But sorry, I cannot do anything in the IR side.

**Comment by IvanUkhov** [comment]
Yes, you are definitely right, it is not bug of IR as I already said. Thanks for quick responce and Happy New Year! =)

**Comment by josevalim** [comment]
Thanks! Happy New Year as well!

**Comment by PlasticLizard** [comment]
Looks like the cause of this problem (freezing) was just removed from MongoMapper a few hours ago anyway.

**Comment by IvanUkhov** [comment]
Ohh, that's great! I was wrong about the author, he does care about MongoMapper. Now I can freely use it with other my favorite plugins.
