### ISSUE TITLE
Can't include mongoid embedded docs by default

### ISSUE THREAD

**Issue by cayblood** [activeadmin/inherited_resources#322]
I have a couple mongoid models:

<pre>
class Album
  include Mongoid::Document
  field :name, type: String
  embedded_in :band
end
class Band
  include Mongoid::Document
  field :name, type: String
  embeds_many :albums
end
</pre>

And I'm trying to get inherited_resources to include the embedded albums in the json for bands, like so:

<pre>
class BandsController &lt; InheritedResources::Base
  respond_to :html, :xml, :json
  def permitted_params
    params.permit!
  end
protected
  def collection
    @bands ||= end_of_association_chain.includes(:albums)
  end
end
</pre>

But I get the following error when trying to retrieve the list of bands:

<pre>undefined method `eager_load' for Mongoid::Relations::Embedded::Many:Class</pre>

Any idea what I might be doing wrong?

**Comment by lukefan** [comment]
remove 'includes'.
embed can't includes.

**Comment by rafaelfranca** [comment]
> remove 'includes'.
> embed can't includes.

Right
