### ISSUE TITLE
Overriding location path with block does not work (inherited_resources 1.0.1)

### ISSUE THREAD

**Issue by knoopx** [activeadmin/inherited_resources#33]
inherited_resources (1.0.1)

This example in the readme file does not work (on create action at least)

```
class ProjectsController < InheritedResources::Base
  def destroy
    destroy!{ root_url }
  end
end
```

also I found some references to an option argument with name :location, can you provide any examples on how to use it? i'm unable to make it work neither

**Comment by josevalim** [comment]
Why do you say it's not working? The test suite says otherwise, so I need more feedback to really know what is happening.

**Comment by knoopx** [comment]
wow that was fast, let me take a look at the tests, but it redirects to resource_url instead of the one I'm providing on successful resource creation (on my app).

**Comment by josevalim** [comment]
Are you using rspec?

**Comment by knoopx** [comment]
> Are you using rspec?

yes, but already found "my" problem. i was attempting to append the user to the resource this way, in order to avoid writing the finder code and expecting that "resource" method would build the resource for me, but it turns out that, without calling build_resource first, the create method somehow no longer redirects to the location i'm overriding:

```
def create
  #build_resource #i was missing this line
  resource.user = current_user
  create! do
    parent_path
  end
end
```

i'm aware that this is not the intended usage of inherited_resources or it is?

**Comment by josevalim** [comment]
Yeah, you need to call build_resources.

Forgive the whining, but whenever you are reporting bugs please try to append information like your environment and some context on what are you doing . Saying that a feature does not work, without any further information, does not help at all, even because we have a test suite to prove otherwise. ;)

Thanks and closing.
