### ISSUE TITLE
Not using Responders::HttpCacheResponder

### ISSUE THREAD

**Issue by brendon** [activeadmin/inherited_resources#342]
Hi there, I think:

`include Responders::HttpCacheResponder`

is to blame for the weird caching errors I'm seeing. Basically the contents of index and show views are cached (including flash messages) until I forcefully fetch the page again.

How would I go about overriding this?

**Comment by rafaelfranca** [comment]
Please use the mailing list or StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.

**Comment by bitboxer** [comment]
We hit the same error and it surprised us, too :cry: . We removed the HttpCacheResponder in our Controllers and it worked again.

**Comment by rafaelfranca** [comment]
@bitboxer maybe we should just remove it from the default controller. Mind to open a PR?

**Comment by bitboxer** [comment]
Sure. PR opened.

**Comment by brendon** [comment]
Lol, I forgot all about this :)

**Comment by bitboxer** [comment]
@brendon sorry to bring this back to your memory :wink:

**Comment by brendon** [comment]
It's all good :) I abandoned the project I was inherited_resources for, but I have fond memories of using it otherwise.
