### ISSUE TITLE
Git tags missing for 1.4.0 and 1.4.1

### ISSUE THREAD

**Issue by seanlinsley** [activeadmin/inherited_resources#345]
While browsing the source code and trying to view it at a particular point in history, I noticed that the Git tags are missing for the two most recent releases, 1.4.0 and 1.4.1. I'd really appreciate if someone could add them retroactively :cat:

**Comment by rafaelfranca** [comment]
:+1: I missed these tags too, and the only person who knows which commits the tags contains is who released.

**Comment by rafaelfranca** [comment]
I think we can consider ae1516a3f1a01f98beac3334f76831a1c793c521 v1.4.1 and 6a94a2c1b45215ee023804979321d889483c87ea v1.4.0. @joelmoss could you confirm?

**Comment by joelmoss** [comment]
Yes, sorry guys. That is correct.

**Comment by rafaelfranca** [comment]
Pushed both tags
