### ISSUE TITLE
Getting 'superclass mismatch for class Responder'

### ISSUE THREAD

**Issue by bloomper** [activeadmin/inherited_resources#35]
Hi!
I am using http://code.google.com/p/mail-queue/ for asynchronous mail processing, i.e. every now and then I run 'ruby /script/runner 'MailQueue.process' -e production' to send all queued mails.

I am not sure if mail_queue is the source of the problem but when running the above, I get the following error:

/bla/bla/bla/vendor/plugins/inherited_resources/lib/inherited_resources/responder.rb:2: superclass mismatch for class Responder (TypeError)
        from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
        from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
        from /usr/local/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:158:in `require'
        from /bla/bla/bla/vendor/plugins/inherited_resources/lib/inherited_resources/base.rb:2
        from /bla/bla/bla/vendor/plugins/inherited_resources/lib/inherited_resources.rb:39:in`inherit_resources'
        from /bla/bla/bla/app/controllers/activities_controller.rb:2
        from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
        from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
        from /usr/local/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:158:in `require'
        from /usr/local/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:265:in`require_or_load'
        from /usr/local/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:224:in `depend_on'
        from /usr/local/lib/ruby/gems/1.8/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:136:in`require_dependency'
        from /usr/local/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:414:in `load_application_classes'
        from /usr/local/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:413:in`each'
        from /usr/local/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:413:in `load_application_classes'
        from /usr/local/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:411:in`each'
        from /usr/local/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:411:in `load_application_classes'
        from /usr/local/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:197:in`process'
        from /usr/local/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:113:in `send'
        from /usr/local/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/initializer.rb:113:in`run'
        from /home/users/register/releases/20100106215523/config/environment.rb:9
        from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
        from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
        from /usr/local/lib/ruby/gems/1.8/gems/rails-2.3.5/lib/commands/runner.rb:39
        from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
        from /usr/local/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in`require'
        from ./script/runner:3

where the ActivitiesController looks something like:

class ActivitiesController < ApplicationController
  inherit_resources
  actions :all
etc...

Any hints on this one?

Cheers,
Anders

**Comment by josevalim** [comment]
Which InheritedResources version?

**Comment by bloomper** [comment]
1.0.1

**Comment by josevalim** [comment]
Are you opening InheritedResources::Responder class to do some tweaking?

**Comment by bloomper** [comment]
Yes, I have an initializer that changes the flash keys and adds a method:

Responders::FlashResponder.flash_keys = [ :success, :failure ]

class InheritedResources::Responder
  def to_js
    set_flash_message! if set_flash_message?
    default_render
  end
end

**Comment by josevalim** [comment]
This is the reason.
Be sure to require 'inherited_resources/responder' before modifying it. :)

**Comment by bloomper** [comment]
Doh... thanks for your incredibly fast support!
