### ISSUE TITLE
uninitialized constant ApplicationController

### ISSUE THREAD

**Issue by otherjohn** [activeadmin/inherited_resources#354]
Ok, when I put "inherit_resources" in my controller, I get "uninitialized constant ApplicationController", when I take it out, the error disappears.

So I have an app with mountable engines in it. 
One of my mountable engines ('Signup') has both an application controller and an accounts controller. Any idea why it would be doing this? 

the code looks like : 

```
module Signup
  class AccountsController < ApplicationController
    inherit_resources

   def new
   end
end
end
```

**Comment by rdetert** [comment]
Does the file `signup/application_controller.rb` exist?

**Comment by matheusvetor** [comment]
The same is happening with me.

```
module Octopus
  class Admin::ResourceContoller < Admin::ApplicationController
    inherit_resources
  end
end
```

When i put a `application_controller.rb` on controllers/ it works fine
But i have:
controllers/octopus/admin
controllers/octopus/frontend

admin and frontend have have their own application_contoller

all controllers that inherit from Admin::ResourceController

This is a mountable engine with isolate_namespace

**Comment by rafaelfranca** [comment]
You need to keep the `ApplicationController` without any namespace to inherited resources work.

**Comment by wvengen** [comment]
I'm running into this as well. For inspiration, devise allows to [configure it](https://github.com/plataformatec/devise/blob/d3d9fba201e3b23361f68ff44e96a6dbf4492afc/lib/devise.rb#L231) in [this way](https://github.com/plataformatec/devise/blob/710efe557d38a897474ef27c051384d5edee26fc/app/controllers/devise_controller.rb#L1).
