### ISSUE TITLE
rails update problem in `method_missing': undefined method `generators' for #<Rails::Railtie

### ISSUE THREAD

**Issue by Hussein1147** [activeadmin/inherited_resources#359]
i have updated rails and it is throwing this error:
/Users/djibrilkeita/.rvm/gems/ruby-2.1.0/gems/railties-4.0.0/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method`generators' for #Rails::Railtie::Configuration:0x00000103242f80 (NoMethodError)

please help!!!

**Comment by rafaelfranca** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Thanks!
