### ISSUE TITLE
Setting flash within success/failure block doesn't overwrite automatically set flash

### ISSUE THREAD

**Issue by allangrant** [activeadmin/inherited_resources#36]
This is probably the expected behavior, but it's less than ideal.  When setting a flash within success/failure blocks, the flash is added to the flash that's automatically set by inherited_resources.  I think a better behavior would be to only automatically add a flash if one was not explicitly set in the success/failure block.  For example, in the following code I would expect one flash, but end up with two:

  def update
    update! do |success, failure|
      success.html do
        flash[:success] = 'Your account has been updated.'
        redirect_to account_path
      end
    end
  end

**Comment by josevalim** [comment]
Please, which IR version are you using? This should be solved if you are using latest responders version with IR.

**Comment by allangrant** [comment]
I'm using inherited_resources-1.0.2 without responders.  Tried with responders-0.4.2 and the behavior is the same.

**Comment by josevalim** [comment]
:( Could you please try adding a failing case to the suite?

**Comment by allangrant** [comment]
Although I know it's lame on my part, I'm afraid I don't know how to. :(  I need to get up to speed on Rails TDD/rspec/etc, but won't get to that within any reasonable time.
