### ISSUE TITLE
NoMethodError (undefined method `find' for nil:NilClass) with polymorphic belongs_to 

### ISSUE THREAD

**Issue by Set2005** [activeadmin/inherited_resources#368]
I got this error in my controller after bundle update, can someone confirm this? did I do something wrong?

Thanks

```
class FlagsController < Api::V1::ResourceController
  belongs_to :deal, :polymorphic => true

  resources :deals do
    resources :comments
    resources :images
    resources :flags
  end
```

Started POST "/api/v1/deals/56/flags.json?clearence=1" for 192.168.1.56 at 2014-06-11 17:32:56 +1200
Processing by Api::V1::FlagsController#create as JSON
  Parameters: {"deal_id"=>"56", "content"=>"asdfad", "auth_token"=>"SoodcyUosyf8ZKY7L7ZN", "clearence"=>"1", "flag"=>{"content"=>"test"}}

**Comment by Set2005** [comment]
Roll back to version 1.4.1 works.

**Comment by rohitpaulk** [comment]
@jianbo - Looks like this is related to #325. #367 looks like it solves the problem. For now, what you could do is specify the parent_class manually like this : 

``` ruby
class FlagsController < Api::V1::ResourceController
  belongs_to :deal, :polymorphic => true, :parent_class => Deal
end
```

**Comment by phlegx** [comment]
@rohitpaulk add parent class works for me! Thank you!

**Comment by rohitpaulk** [comment]
@phlegx - You're welcome!

**Comment by bronislav** [comment]
@rohitpaulk `polymorphic: true` in your example doesn't have much sense, because you have only one possible parent association.

``` ruby
module Admin
  class PositionsController < BaseController
    belongs_to :employee, :assignment, polymorphic: true
  end
end
```

In this case you can't use `parent_class` option to point to the correct parent class

**Comment by rohitpaulk** [comment]
@bronislav - True :) I had just copied the OP's code and added the parent class part.

**Comment by rafaelfranca** [comment]
Could you check with current master? It may be fixed by https://github.com/josevalim/inherited_resources/pull/376
