### ISSUE TITLE
Controller with shared views, when using STI

### ISSUE THREAD

**Issue by kevwil** [activeadmin/inherited_resources#37]
If I use STI in my ActiveRecord models, and I have a controller for each model, and my controllers inherit from InheritedResources::Base, I end up having a lot of duplication of code in the views. In a normal controller, I would use "render 'shared/blah'" and use shared view templates in app/views/shared.

How can I do this with the Inherited Resources plugin? My apologies if this is a silly question, I'm quite new at this.

**Comment by josevalim** [comment]
Please use the mailing list for doubts and questions:

http://groups.google.com/group/inherited_resources

Somewhere there might be able to help you.
