### ISSUE TITLE
Ruby >= 2.0 and has_scope

### ISSUE THREAD

**Issue by mathieumahe** [activeadmin/inherited_resources#370]
I have a problem with has_scope in ruby >= 2.0. After some search, I found that the bug came from the apply_scopes_if_available method in base_helpers.rb.

In Ruby 1.9, respond_to?(:apply_scopes) works well, but since the 2.0 version, respond_to? return false.

But I'm not sure how to fix this bug... Do you have any idea ?

Thanks in advance!

**Comment by rafaelfranca** [comment]
You need to give us more information on how to reproduce this issue, otherwise there is nothing we can do. Thanks!
