### ISSUE TITLE
belongs_to collection_name attribute is not working properly

### ISSUE THREAD

**Issue by bamorim** [activeadmin/inherited_resources#371]
Well, if I have, for example

``` ruby
class Root < ActiveRecord::Base
  has_many :foos, class_name: "Child"
end

class Child < ActiveRecord::Base
  belongs_to :root
end
```

And I have a controller 

``` ruby
class ChildsController < InheritedResources::Base
  belongs_to :root, collection_name: :foos
end
```

I just doesn't work properly: 

```
undefined method `childs' for #<Root:0x00000002dfbf40>
```

I think that is because it's adding the collection_name to the resources_configuration[:root] instead of [:self]

``` ruby
2.1.0 :009 > ChildsController.resources_configuration
 => {:self=>{:collection_name=>:childs, :instance_name=>:child, :route_collection_name=>:childs, :route_instance_name=>:child, :request_name=>"child"}, :polymorphic=>{:symbols=>[], :optional=>false}, :root=>{:parent_class=>Root (call 'Root.connection' to establish a connection), :singleton=>false, :collection_name=>"bars", :instance_name=>"bars", :param=>:root_id, :route_name=>:root, :finder=>:find}} 
```

And the method_for_association_chain is by default the [:self] one

``` ruby
      def method_for_association_chain #:nodoc:
        resource_collection_name
      end
```

Probably a belongs_to association should also override method_for_association_chain to return the correct collection_name!

In my official project I did a workaround using

``` ruby
resources_configuration[:self][:collection_name] = "detonateds" # workaround for now...
```

I can make this change that way (making the belongs_to to override this method) but I think that will mess with the "optional" belongs_to...
Maybe we should check if `params[param]` exists and then return the correct collection_name

I've also created a project to demonstrate that behaviour (with both namespaced and non-namespaced models/controllers)

https://github.com/bamorim/InheritedResourcesBelongsToBug

(there's a db:seed)

Thank you!

**Comment by bamorim** [comment]
Oh, I've just realized that It's not this purpuse of the belongs_to collection_name.
If I'm right, it is only for nested belongs_to and this is to tell how to fetch the parent. I'm supposed to do like:

``` ruby
class ChildsController < InheritedResources::Base
  belongs_to :root
  defaults collection_name: :foos
end
```

Right? If yes, just close this issue. (But that would be a nice feature if I can say how it's fetched and do not change the variable to @foos)

Well, I'm sorry for this.

**Comment by rafaelfranca** [comment]
Right.
