### ISSUE TITLE
Setting default class_name dynamicaly

### ISSUE THREAD

**Issue by reignmaker** [activeadmin/inherited_resources#372]
Hello.
How can i set `:class_name` dynamically?
I need it for my STI models. 

``` ruby
resources :points, controller: 'points', type: 'Points'
resources :terminals, controller: 'points', type: 'Terminal'
```

``` ruby
class PointsController < InheritedResources::Base
  respond_to :html, :json
  defaults class_name: set_type

  private
  def set_type
    params[:type]
  end
end
```

**Comment by TomK32** [comment]
I have quite a few STI models (subclassed from the same parent model) in my app and my approach was to go into `build_resource` as that is the only place where you really need to get the class right. Other than that my type is the parent class that i subclassed from.
PS: I'm using mongoid, not sure what activerecord is capable of.

**Comment by rafaelfranca** [comment]
Please use StackOverflow for questions/help, where a wider community will be able to help you. We reserve the issues tracker for issues only.
