### ISSUE TITLE
Support for Rails 4.2 - add responders gem dependency

### ISSUE THREAD

**Issue by kofronpi** [activeadmin/inherited_resources#373]
I tried to install the ActiveAdmin gem with rails `4.2.0beta1` . The application fails to launch because of inherited_responders:

```
/.bundle/ruby/2.1.0/gems/inherited_resources-1.4.1/lib/inherited_resources/responder.rb:2:in `<module:InheritedResources>': cannot load such file -- action_controller/metal/responder (LoadError)
```

Responders are taken off the framework starting at Rails 4.2 and will need to be added as a dependency with the [responders gem](https://github.com/plataformatec/responders).
( see [blog post here](http://weblog.rubyonrails.org/2014/8/20/Rails-4-2-beta1/) )

**Comment by andriytyurnikov** [comment]
gem 'inherited_resources',  github: 'andriytyurnikov/inherited_resources', branch: 'rails_4_2', still work-in-progress though

**Comment by markmohr15** [comment]
Is there a way around it not letting me install 1.5 because of dependency issues?

**Comment by andriytyurnikov** [comment]
@markmohr15 fork gem dependent on it, and replace original dependency

**Comment by rafaelfranca** [comment]
Inherited resources is deprecated and we will not support it anymore. We recommend active admin to stop using it.

**Comment by aaronchi** [comment]
@rafaelfranca Why not allow a new maintainer to take over the project? Seems like this is still valuable for a lot of people.

**Comment by rafaelfranca** [comment]
We did it before and the maintainer didn't could keep working on it. But for real, we don't want to spread this project anymore. We believe it add unneeded complexity in applications that are not worth.

**Comment by rafaelfranca** [comment]
I'll keep maintaining the project to fix bugs and keep the legacy working, but new features will not be developed and we will not support Rails >= 4.2

**Comment by goosetav** [comment]
> add unneeded complexity in applications

While I tend to agree about complexity, some of the dsl (`belongs_to`, etc...) and utility methods are very valuable -- it'd be great to see those repackaged into a concern or something.

**Comment by jeffutter** [comment]
Any status update? Rails 4.2 was officially released yesterday.

**Comment by thiensubs** [comment]
Why this gems isn't support 4.2, i was upgrade rails 4.2, but project is down because this gems.
Realy readly uncomfortable!

**Comment by gkunwar** [comment]
I am facing same problem on Rails 4.2, What is the best solution?

**Comment by markmohr15** [comment]
Fork it and change the dependency

**Comment by meligatt** [comment]
Hello, markmohr15 , can you give us more details about the dependency you are talking about, please. I'm beginner and I want to be sure that I'm changing the right dependency..(if that makes sense) Thank you!

**Comment by markmohr15** [comment]
I did this a few months ago, so I can' say 100% that this is what it is, but I believe you need to change your inherited resources dependency to inherited_resources (>= 1.4.1) and then use this in your gem file for inherited dependency:  gem "inherited_resources", github: "andriytyurnikov/inherited_resources", branch: "rails_4_2"
