### ISSUE TITLE
Rails 4+

### ISSUE THREAD

**Issue by richpeck** [activeadmin/inherited_resources#375]
Just read up about this being deprecated - we still rely on IR to provide `resource`, `collection` and `resource_class` functionality in our apps, as well as a standard "base" line of controller - how you would recommend we maintain this functionality without the presence of IR?

I am eager to make the code a lot more efficient - I can write a separate gem if required, too

**Comment by joost** [comment]
Interested in this as well!

**Comment by milankubin** [comment]
+1

**Comment by rafaelfranca** [comment]
Just implement this code in your application. BTW, we believe this methods give more problems than are useful, and this is the main reason we deprecated this gem
