### ISSUE TITLE
Rails 4 saving deep nested associations through a nested form broken with inherited_resources

### ISSUE THREAD

**Issue by milankubin** [activeadmin/inherited_resources#377]
Hi,

Just want to give a heads up to anyone googeling. or having problems with this.
I spent 2 days trying to fix my code, while it was actually just the right way to do it, but somehow  it didn' t work.  Associations were being saved, but on failed validation  (with validates_associated )  it left my associated form fields (fields_for ) empty.

Someone on IRC suggested that this gem is now deprecated, and It's the first time I ran in to this kind of problem, so decided to dump the gem from my controller. And replace all " resource" and collection with @model, @models.  (yaay :(  ).  It did work however.

Kinda still meh though, I was used to using collection and resource, and be able to re-use views and scaffold controllers.

Anyway, maybe I was doing something wrong in regards to doing this with inherited_resources.

Gist:
https://gist.github.com/milankubin/3541bed126c4f6375ed0

**Comment by rafaelfranca** [comment]
Could you test with the current master branch? Thanks
