### ISSUE TITLE
Controller tests fail when stubbing models to be invalid

### ISSUE THREAD

**Issue by javierm** [activeadmin/inherited_resources#38]
It seems my tests don't pass when I use Inherited Resources and stub a model to be invalid (although the application works fine).

I'm using Shoulda with Ryan Bates nifty scaffold generator, but I've also tried Test::Unit (both standard and 2.x). Here are examples I've tried:

```
test "should not create user" do
  User.any_instance.stubs(:valid?).returns(false)
  post :create
  assert_template 'new'
end

context "create action" do
  should "render new template when model is invalid" do
    User.any_instance.stubs(:valid?).returns(false)
    post :create
    assert_template 'new'
  end
end
```

Using the standard controller code, it works fine, but when I inherit from Inherited Resources:

```
class UsersController < InheritedResources::Base
end
```

The test fails:
    1) Failure:
    test: invalid create action should render template :new. (UsersControllerTest)
    [shoulda (2.10.3) lib/shoulda/action_controller/macros.rb:164:in `__bind_1264668968_695329'
       shoulda (2.10.3) lib/shoulda/context.rb:362:in`call'  
       shoulda (2.10.3) lib/shoulda/context.rb:362:in `test: invalid create action should render template :new. ']:
    expecting <"new"> but rendering with <""> 

It also fails when testing responses:

```
1) Failure:
test: invalid create action should respond with success. (UsersControllerTest)
response to be a 200, but was 302
```

I've tried to mofidy my code to look like this:
    class UsersController < InheritedResources::Base
      def create
        create! do |success, failure|
          failure.html do
            render :action => 'new'
          end
        end
      end
    end

Debugging the test shows the render method is never called. If I add a success block, the success block is called, but the failure block isn't.

If I add a validation rule to User model (for example, validates presence of name) _and_ remove the stub in my tests, the test pass. Note that if I add the validation rule but still do the stub, it still fails. So I guess it has something to do with the stub.

Is there anything I'm doing wrong? I've looked for information about it, but I've only found a bug when using RSpec (which looks pretty similar).

BTW: I've shown the examples with the "create" action, but the same happens with "update".

Thanks!

_Edit_: Forgot to say, I'm using Rails 2.3.5, Inherited Resources 1.0.2, mocha 0.9.8 and shoulda 2.10.3

**Comment by carlosantoniodasilva** [comment]
Hello, 
to be considered an invalid record and render failure inside your action, your model must have at least one error added. Responders will check whether your model has errors or not to render success/failure cases. This is why adding the validation works, because there is one error added in the model.
Please try stubbing model.errors with at least one error.
Carlos.

**Comment by josevalim** [comment]
Carlos is right! Closing...

**Comment by javierm** [comment]
Thank you. It works right.

Now I see it says so in the Responders documentation, although I guess you have to know a bit of the internals to see the issues are related.

I'll leave to you if you consider it should be added more explicitly somewhere in the documentation.

Thank you!

**Comment by dukex** [comment]
Thank you!

**Comment by nskeip** [comment]
Just for newbies like me got @carlosantoniodasilva right:

```
MyModel.any_instance.stub(:errors).and_return(["Error1"])  # this is for inherited_resources
```

This works! Yay!
