### ISSUE TITLE
Updating to newer version of responders dependency

### ISSUE THREAD

**Issue by dankohn** [activeadmin/inherited_resources#380]
I know the project has been deprecated, but I would appreciate assistance resolving this issue, since inherited_resources is still required by activeadmin, a very popular project.

When I try to upgrade devise from 3.3.0 to 3.4.1, I get the following error:

```
$ bundle exec rspec  --format documentation spec 
/Users/dan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/actionpack-4.1.7/lib/action_controller/base.rb:164:in `<module:ActionController>': uninitialized constant ActionController::Metal (NameError)
    from /Users/dan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/actionpack-4.1.7/lib/action_controller/base.rb:5:in `<top (required)>'
    from /Users/dan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/bundler/gems/responders-e0bfec2624da/lib/responders.rb:1:in `<top (required)>'
    from /Users/dan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/devise-3.4.1/lib/devise.rb:7:in `<top (required)>'
    from /Users/dan/Dropbox/Documents/dev/chewy/spec/spec_helper.rb:4:in `require'
    from /Users/dan/Dropbox/Documents/dev/chewy/spec/spec_helper.rb:4:in `<top (required)>'
    from /Users/dan/Dropbox/Documents/dev/chewy/spec/rails_helper.rb:4:in `require'
    from /Users/dan/Dropbox/Documents/dev/chewy/spec/rails_helper.rb:4:in `<top (required)>'
    from /Users/dan/Dropbox/Documents/dev/chewy/spec/controllers/admin/doctors_controller_spec.rb:1:in `require'
    from /Users/dan/Dropbox/Documents/dev/chewy/spec/controllers/admin/doctors_controller_spec.rb:1:in `<top (required)>'
    from /Users/dan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `load'
    from /Users/dan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `block in load_spec_files'
    from /Users/dan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `each'
    from /Users/dan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/configuration.rb:1105:in `load_spec_files'
    from /Users/dan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:96:in `setup'
    from /Users/dan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:84:in `run'
    from /Users/dan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:69:in `run'
    from /Users/dan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.1.7/lib/rspec/core/runner.rb:37:in `invoke'
    from /Users/dan/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/rspec-core-3.1.7/exe/rspec:4:in `<top (required)>'
    from /Users/dan/.rbenv/versions/2.1.2/bin/rspec:23:in `load'
    from /Users/dan/.rbenv/versions/2.1.2/bin/rspec:23:in `<main>'
```

That is fixed in the 2.0 branch of responders. https://github.com/plataformatec/responders/issues/97

inherited_resources is [locked](https://github.com/josevalim/inherited_resources/blob/master/inherited_resources.gemspec) to the 1.0 version of responders. You can see that the 3.4.1 [version](https://github.com/plataformatec/devise/compare/v3.3.0...v3.4.1#diff-16) of devise added responders 1.1.1, which requires a newer railties.

I'm willing to fork inherited_resources or responders if necessary, but am having trouble resolving this dependency maze. I would appreciate any suggestions.

One other detail: `bundle exec spring rspec spec` works correctly.

**Comment by rafaelfranca** [comment]
Was this issue fixed at 1.1 branch of responders? If not it should be.

We are not going to support responders 2.0 since it depends on Rails 4.2 and we will not support Rails 4.2, but we still support any version of responders >= 1.0 and < 2.0, so we can fix that issue on responders 1.1.x and you can solve this problem.

**Comment by rafaelfranca** [comment]
Just backported the fix to 1-1-stable branch. Could you check with it? If it does fix your problem I'll release a new version

**Comment by dankohn** [comment]
Yes, using `gem 'responders', github: 'plataformatec/responders', ref: '553527f'` resolved my issue. I can now use devise 3.4.1. Thanks very much for the fix and the quick turnaround. It would be great if you could release a responders 1.1.2.

**Comment by rafaelfranca** [comment]
1.1.2 released. Thank you for the report.

**Comment by dankohn** [comment]
Thank you for being so responsive.
