### ISSUE TITLE
Rails 4.2

### ISSUE THREAD

**Issue by timoschilling** [activeadmin/inherited_resources#381]
@rafaelfranca Thanks agin for your [announcement](https://github.com/activeadmin/activeadmin/pull/3193#issuecomment-62421649) to help with `inherited_resources` and Rails 4.2.

@andriytyurnikov says on https://github.com/josevalim/inherited_resources/issues/373#issuecomment-54052409 that he works on a fix ([andriytyurnikov/inherited_resources branch rails_4_2](https://github.com/andriytyurnikov/inherited_resources/tree/rails_4_2)), that I have tried  some days a go and the basics themes to work.

And @pedrofaria says (https://github.com/activeadmin/activeadmin/issues/3346#issuecomment-62421948) that he has a fork ([codecraft63/inherited_resources](https://github.com/codecraft63/inherited_resources)) to support Rails 4.2 too

**Comment by timoschilling** [comment]
@rafaelfranca any updates on this, or can I help in some way?

**Comment by rafaelfranca** [comment]
I already create a branch but I need to understand why the tests are failing randomly. https://github.com/josevalim/inherited_resources/tree/rails-4-2

**Comment by boxofrad** [comment]
@rafaelfranca is this one of the failures you're getting?

```
ShowActionBaseTest#test_controller_should_render_show:
NoMethodError: undefined method `show' for #<UsersController:0x007fb9acb356d8>
    /Users/daniel/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/actionpack-4.1.5/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
    /Users/daniel/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/actionpack-4.1.5/lib/abstract_controller/base.rb:189:in `process_action'
    /Users/daniel/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/actionpack-4.1.5/lib/action_controller/metal/rendering.rb:10:in `process_action'
    /Users/daniel/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/actionpack-4.1.5/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
    /Users/daniel/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.5/lib/active_support/callbacks.rb:82:in `run_callbacks'
    /Users/daniel/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/actionpack-4.1.5/lib/abstract_controller/callbacks.rb:19:in `process_action'
    /Users/daniel/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/actionpack-4.1.5/lib/action_controller/metal/rescue.rb:29:in `process_action'
    /Users/daniel/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/actionpack-4.1.5/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
    /Users/daniel/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.5/lib/active_support/notifications.rb:159:in `block in instrument'
    /Users/daniel/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.5/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    /Users/daniel/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/activesupport-4.1.5/lib/active_support/notifications.rb:159:in `instrument'
    /Users/daniel/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/actionpack-4.1.5/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
    /Users/daniel/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/actionpack-4.1.5/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
    /Users/daniel/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/actionpack-4.1.5/lib/abstract_controller/base.rb:136:in `process'
    /Users/daniel/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/actionview-4.1.5/lib/action_view/rendering.rb:30:in `process'
    /Users/daniel/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/actionpack-4.1.5/lib/action_controller/test_case.rb:595:in `process'
    /Users/daniel/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/actionpack-4.1.5/lib/action_controller/test_case.rb:64:in `process'
    /Users/daniel/.rbenv/versions/2.1.1/lib/ruby/gems/2.1.0/gems/actionpack-4.1.5/lib/action_controller/test_case.rb:495:in `get'
    /Users/daniel/src/inherited_resources/test/base_test.rb:98:in `test_controller_should_render_show'
```

It seems the setup from `test_redirect_to_the_users_list_if_show_undefined` isn't torn down / persists between tests.

``` ruby
def test_redirect_to_the_users_list_if_show_undefined
  @controller.class.send(:actions, :all, :except => :show)
```

If I comment out the entire test it seems to fix the other failures.

**Comment by scudelletti** [comment]
@boxofrad we remove the show method when we call `.send(:actions, :all, :except => :show)` as we can see [here](https://github.com/josevalim/inherited_resources/blob/master/lib/inherited_resources/class_methods.rb#L78-L80), so it not returns.

**Comment by boxofrad** [comment]
@scudelletti yeah it's strange that the method is still missing in subsequent tests though...

Given the intermittent nature of the test failures, I'd be tempted to think its something to do with the rails autoloader / constants not getting redefined - I've been bitten by this before.

I'll have a read through the changelog, they may have introduced some caching behaviour or a regression.

**Comment by boxofrad** [comment]
I should also note that the controller tests on our application have also intermittently started failing, which I believe is a related issue.

**Comment by boxofrad** [comment]
Actually I think I may've spoken out of turn...

I have the same test failures on cb178c2 (v1.5.1 / before the 4.2 work) so this is probably a side-issue, sorry guys!

**Comment by ashanbrown** [comment]
I've proposed this as an alternative: https://github.com/josevalim/inherited_resources/pull/387

**Comment by joallard** [comment]
Now it passes on Travis, I'm curious, is this 4-2 ready to be merged and released?

**Comment by ashanbrown** [comment]
I haven't been able to test/upgrade my app to rails 4.2 due to issues with other gems (paper_trail, specifically), so I can't personally comment on whether it works in a real application or not.

**Comment by cpence** [comment]
It _seems_ to be working for me on Rails 4.2, though I'm only using inherited_resources indirectly through ActiveAdmin, and I'm not sure how to test whether or not it's behaving as expected.

**Comment by joallard** [comment]
@dontfidget I see. Are you able to add some tests about what's failing in PaperTrail?

**Comment by ashanbrown** [comment]
The paper trail issues are unrelated to this gem.  They just keep me from
running my app on rails 4.2

**Comment by deivid-rodriguez** [comment]
I just tried this through activeadmin and my test suite fails to start with the following error:

```
/home/davidr/.rvm/gems/ruby-2.2.0/bundler/gems/inherited_resources-ff1c991307ff/lib/inherited_resources/responder.rb:2:in `<module:InheritedResources>': uninitialized constant ActionController::Responder (NameError)
    from /home/davidr/.rvm/gems/ruby-2.2.0/bundler/gems/inherited_resources-ff1c991307ff/lib/inherited_resources/responder.rb:1:in `<top (required)>'
    from /home/davidr/.rvm/gems/ruby-2.2.0/bundler/gems/inherited_resources-ff1c991307ff/lib/inherited_resources.rb:4:in `<top (required)>'
    from /home/davidr/.rvm/gems/ruby-2.2.0/bundler/gems/activeadmin-7aef260921d4/lib/active_admin.rb:10:in `<top (required)>'
    from /home/davidr/.rvm/gems/ruby-2.2.0/bundler/gems/activeadmin-7aef260921d4/lib/activeadmin.rb:1:in `<top (required)>'
    from /home/davidr/.rvm/gems/ruby-2.2.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:76:in `require'
    from /home/davidr/.rvm/gems/ruby-2.2.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:76:in `block (2 levels) in require'
    from /home/davidr/.rvm/gems/ruby-2.2.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:72:in `each'
    from /home/davidr/.rvm/gems/ruby-2.2.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:72:in `block in require'
    from /home/davidr/.rvm/gems/ruby-2.2.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:61:in `each'
    from /home/davidr/.rvm/gems/ruby-2.2.0/gems/bundler-1.7.11/lib/bundler/runtime.rb:61:in `require'
    from /home/davidr/.rvm/gems/ruby-2.2.0/gems/bundler-1.7.11/lib/bundler.rb:134:in `require'
    from /home/davidr/Proyectos/nipanipa/config/application.rb:7:in `<top (required)>'
    ...
```

So it seems that it fails to require `inherited_resources`.

I just added 

```
gem 'activeadmin', github: 'activeadmin'
gem 'inherited_resources', github: 'josevalim/inherited_resources', branch: 'rails-4-2'
```

to my Gemfile, not sure if other changes are needed or it's just the support that's not ready.

Thanks to anybody working on this!

**Comment by PenguinGabe** [comment]
Hi @deivid-rodriguez did you manage to resolve the issue in the end? I'm having the exact same problem..

**Comment by deivid-rodriguez** [comment]
Nope, I didn't get to it yet.

**Comment by timoschilling** [comment]
From my point of view can this ticked be closed, after the 'rails-4-2' branch is merged into master and a new release is happened. @rafaelfranca what do you think?

**Comment by rafaelfranca** [comment]
1.6.0 released.

**Comment by romansklenar** [comment]
:+1:

**Comment by deivid-rodriguez** [comment]
:+1: It seems to be working fine actually.
