### ISSUE TITLE
Nested attributes with inherited resources

### ISSUE THREAD

**Issue by ldonnet** [activeadmin/inherited_resources#385]
Hi,

I use your great gem with my rails 4.1 application but when I want to create a new object with nested attributes it fails. Perhaps I misunderstood something?

Here is my controller : 

``` ruby
class StationsController < StationWaysController
  respond_to :html

  def create
    create! do |success, failure|      
      success.html{ redirect_to stations_path }
    end    
  end

  def update
    update! do |success, failure|      
      success.html { redirect_to stations_path }
    end    
  end

  def station_params
    params.require(:station).permit( :name, :wifi, :address, { levels_attributes: [ :id, :name, :floor, :station_id, :background_map, :width, :height, :done, :_destroy ] }  )
  end

end
```

And when I create a new station I have this log : 

``` shell
Started POST "/stations" for 127.0.0.1 at 2014-12-22 10:55:21 +0100
Processing by StationsController#create as HTML
  Parameters: {"utf8"=>"✓", "authenticity_token"=>"q5NkDtAzMpsJIgOp+Zi7Nf6u+0xZyLXDrVpTLhfNZo8=", "station"=>{"name"=>"t3", "wifi"=>"1", "address"=>"", "levels_attributes"=>{"1419242104015"=>{"floor"=>"1", "name"=>"n2", "width"=>"625", "height"=>"750", "background_map"=>#<ActionDispatch::Http::UploadedFile:0x00000005e2cac0 @tempfile=#<File:/tmp/RackMultipart20141222-4923-4y3w25>, @original_filename="GM_NewTux.svg", @content_type="image/svg+xml", @headers="Content-Disposition: form-data; name=\"station[levels_attributes][1419242104015][background_map]\"; filename=\"GM_NewTux.svg\"\r\nContent-Type: image/svg+xml\r\n">, "_destroy"=>"false"}}}, "commit"=>"Ajouter un(e) Station"}
   (0.2ms)  BEGIN
  Station Exists (0.6ms)  SELECT  1 AS one FROM "stations"  WHERE "stations"."name" = 't3' LIMIT 1
   (0.2ms)  ROLLBACK

```

And when I edit a station with levels and submit it works great.

Thanks for your help
Luc Donnet

**Comment by rafaelfranca** [comment]
When you say it fails which failure message you get? Looking at your report I could not see anything wrong.

**Comment by ldonnet** [comment]
Sorry I havn't explained well my problem. When I edit a station and submit my form it saves all datas station and nested attributes levels.  But when I'm on a new station form with nested attributes and submit  it returns to the new station form with no visible errors.    

Howerver the guilty is me and my code and not inherited resources. Because it fails when validation run on nested attributes station_id.

``` ruby
class Station < ActiveRecord::Base  
  has_many :levels, :dependent => :destroy

end
```

``` ruby
class Level < ActiveRecord::Base
  belongs_to :station
  **validates :station_id, presence: true** # When I comment this submit form with nested attributes works

end  
```

I should read some documentation about validation with nested attributes. 
I'm sorry to have disturbed you with this problem.

Luc Donnet

**Comment by ldonnet** [comment]
Must use inverse_of in my models like that : http://railsguides.net/belongs-to-association-and-validate-presence-with-nested-attributes/

**Comment by rafaelfranca** [comment]
No problem. Thank you for reporting back.
