### ISSUE TITLE
Should README contain deprecation notice?

### ISSUE THREAD

**Issue by ratdaddy** [activeadmin/inherited_resources#393]
Despite pointing to the responders gem and newer Rails controller features it seems that there is still a valid use case for inherited resources as a way to construct absolutely minimal controllers. This is useful for things like admin interfaces (ActiveAdmin continues to use this gem) where controllers for each model follow a very similar pattern with little need to modify the basic CRUD actions of a standard controller.

Inherited resources also deals with things the standard Rails controller generator doesn't - like introducing a namespaced controller to operate on a non-namespaced model and providing correct url helpers to deal with this.

Also, it appears that active development continues on the project with Rails 4.2 modifications being recently added. I think many developers (myself included) see something titled deprecation notice and think the gem is going away or headed towards end-of-life but that doesn't seem to be the case.

If this gem is going to be around for a while it may be that the language needs to change just a bit to remove the word "deprecation" which is usually a warning to anyone finding a new gem not to use it. Given there isn't a complete replacement available (that I could find) I think there is still a future for inherited resources.

**Comment by rafaelfranca** [comment]
> the gem is going away or headed towards end-of-life

This is exactly the case. The last work of this gem was to add support to Rails 4.2. Now no new development will be made and we are only update the code if there is a bug with the integration with Active Admin.

I made this compromise with Active Admin maintainers to keep Inherited resources maintained until the release of Rails 5.

We really don't believe inherit resource is a good choice for new projects and we don't want it to be used. Of course we can't leave our users alone, this is why we will keep maintaining the already released versions.

**Comment by TomK32** [comment]
Well, if there's no development for it, doesn't that mean it has reached a state of being finished? A strange concept I admit.

I have written a mere 2 `edit` methods in my 56 interited_resources controllers,`create` is the top scorer with 42, `update` is the runner up with 20, in total it is only 98 methods I had to override, ~25% of what I'd have to without it. I do have a need for this gem to stay alive.

**You will have to delete the repo or someone will make it compatible for Rails 5.**

**Comment by rafaelfranca** [comment]
> You will have to delete the repo or someone will make it compatible for Rails 5.

I'm fine with it. People can fork and release it if they want. This is open source after all.

We just don't want to be the people that will advocate about this gem usage. **We don't recommend it to be used in new applications.**
