### ISSUE TITLE
Permit nested hashes without explicitly setting it

### ISSUE THREAD

**Issue by rusikf** [activeadmin/inherited_resources#394]
Hello , this [solution](http://stackoverflow.com/questions/17810838/strong-parameters-permit-all-attributes-for-nested-attributes/26048034#26048034) doesn't work for inherited_resources, but works with usual params.

How to reproduce ?
For example i have UsesController like this:

``` ruby
class UsersController
  load_and_authorize_resource
  inherit_resources
  def update
  end
end
```

And i send PATCH request to update method with params :

``` ruby
params = { :user => [:field_1, :field_2, :nested_hashes => {'0' => [:filed_99, :field_101]}] }
```

So, i want to permit the whole `nested_hashes`(all included values/keys) without explicitly set in in permitted_params like this

``` ruby
 def permitted_params
     params.permit(:user => [:field_1, :field_2]).tap do |whitelisted|
       whitelisted[:nested_hashes] = params[:user][:nested_hashes] if params[:user][:nested_hashes]
     end
  end
```

But this doesn't work, it shows in rails 4 logs something like this:

``` ruby
Unpermitted params: nested_hashes
```

Without inherited resources( like in first link- solution above ), this hack works.

**Comment by rafaelfranca** [comment]
Can you please provide a sample application that reproduces the error?

**Comment by varyonic** [comment]
Closing this issue as it's been inactive for several months. Please feel free to open a new issue or reopen this issue. Thanks!
