### ISSUE TITLE
HABTM Duplicate Records

### ISSUE THREAD

**Issue by ccallebs** [activeadmin/inherited_resources#396]
This is a continuation of an ActiveAdmin issue documented here: https://github.com/activeadmin/activeadmin/issues/1311

When passing the ids of a HABTM relationship, inherited_resources interprets that as trying to create new entries rather than modifying existing ones. This can be mitigated by passing an `id` attribute in with the attributes for the HABTM relationship.

My setup:

``` RUBY
  permit_params :title, :sendgrid_key,
    template_attributes: [:name, :categories_raw],
    variations_ids: [],
    variations_attributes: [:name, :sendgrid_key, :_destroy] # You can add :id to this to mitigate the issue
```

The formtastic code if you're interested:

``` RUBY
f.inputs "Variations" do
  f.has_many :variations do |v|
    v.input :name
    v.input :sendgrid_key
  end
end
```

Sample console output:

```
From: /Users/chuck/.rvm/gems/ruby-2.1.4@email-warehouse/gems/inherited_resources-1.6.0/lib/inherited_resources/base_helpers.rb @ line 357 InheritedResources::BaseHelpers#build_resource_params:

    356: def build_resource_params
 => 357:   binding.pry
    358:
    359:   parameters = permitted_params || params
    360:   rparams = [parameters[resource_request_name] || parameters[resource_instance_name] || {}]
    361:   if without_protection_given?
    362:     rparams << without_protection
    363:   else
    364:     rparams << as_role if role_given?
    365:   end
    366:
    367:   rparams
    368: end

[1] pry(#<Admin::ExperimentsController>)> params
=> {"utf8"=>"✓",
 "_method"=>"patch",
 "authenticity_token"=>"tNNXm6Nsfle8i39ao8BE12BRedMuy16FV7GUQrUrgZbXvhCHQURwOfay8SO+BtjguWUD6WqNOe2sbWKCIPpsgg==",
 "experiment"=>
  {"title"=>"Brand New Experiment",
   "sendgrid_key"=>"brand_new_experiment",
   "template_attributes"=>{"name"=>"Yeah!", "categories_raw"=>"renter, listing suggestion, a", "id"=>"41"},
   "variations_attributes"=>
    {"0"=>{"name"=>"asdf", "sendgrid_key"=>"asdf", "id"=>"1079"},
     "1"=>{"name"=>"asdf", "sendgrid_key"=>"asdf", "id"=>"1080"},
     "2"=>{"name"=>"asdf", "sendgrid_key"=>"asdf", "id"=>"1081"},
     "3"=>{"name"=>"asdf", "sendgrid_key"=>"asdf", "id"=>"1082"}}},
 "commit"=>"Update Experiment",
 "controller"=>"admin/experiments",
 "action"=>"update",
 "id"=>"2"}
[2] pry(#<Admin::ExperimentsController>)> exit
Unpermitted parameter: id
Unpermitted parameter: id
Unpermitted parameter: id
Unpermitted parameter: id
Unpermitted parameter: id
```

I don't see an immediate fix for the problem (and honestly I'm not even convinced it's a bug). However, I think a note should be made somewhere in the documentation if no fix exists. If you see a conceptual way it can be done, let me know and I can do the leg work. If not, I can add the edge case to some documentation somewhere.

**Comment by rafaelfranca** [comment]
> When passing the ids of a HABTM relationship, inherited_resources interprets that as trying to create new entries rather than modifying existing ones. This can be mitigated by passing an id attribute in with the attributes for the HABTM relationship.

Yeah, this make a lot of sense. This is how nested attributes works. We are just matching the same behaviour.

From http://api.rubyonrails.org/classes/ActiveRecord/NestedAttributes/ClassMethods.html#method-i-accepts_nested_attributes_for.

> By default the :update_only option is false and the nested attributes are used to update the existing record only if they include the record's :id value. Otherwise a new record will be instantiated and used to replace the existing one. However if the :update_only option is true, the nested attributes are used to update the record's attributes always, regardless of whether the :id is present. The option is ignored for collection associations.
