### ISSUE TITLE
Ensure that dual blocks can not be given to destroy

### ISSUE THREAD

**Issue by josevalim** [activeadmin/inherited_resources#4]

**Comment by bloomper** [comment]
May I ask why this should not be allowed? In my case, the destroy method is invoked via AJAX and in order to distinguish a failed destroy from a successful one, I am setting a different status code in the failure block causing a different callback to be executed on client side.

**Comment by josevalim** [comment]
Agreed and fixed!

**Comment by bloomper** [comment]
Wow, that was fast! Thanks!
