### ISSUE TITLE
uninitialized constant Rails::Railtie using version 1.0 with Rails 2.3.5

### ISSUE THREAD

**Issue by fuzz** [activeadmin/inherited_resources#40]
Rails 2.3.5 application w/ "config.gem 'inherited_resources', :version => '1.0'" in environment.rb fails with the below error on 1.9.1 and 1.8.7 following a gem update today.

=> Rails 2.3.5 application starting on http://0.0.0.0:3000
/opt/local/lib/ruby1.9/gems/1.9.1/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:440:in `rescue in load_missing_constant': uninitialized constant Rails::Railtie (NameError)
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:436:in`load_missing_constant'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:80:in `const_missing_with_dependencies'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/responders-0.5.0/lib/responders.rb:5:in`module:Responders'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/responders-0.5.0/lib/responders.rb:1:in `<top (required)>'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in`require'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `block in require'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:521:in`new_constants_in'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/inherited_resources-1.0.0/lib/inherited_resources.rb:9:in`<top (required)>'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in`block in require'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:521:in `new_constants_in'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in`require'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/rails-2.3.5/lib/rails/gem_dependency.rb:208:in `load'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/rails-2.3.5/lib/initializer.rb:307:in`block in load_gems'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/rails-2.3.5/lib/initializer.rb:307:in `each'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/rails-2.3.5/lib/initializer.rb:307:in`load_gems'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/rails-2.3.5/lib/initializer.rb:164:in `process'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/rails-2.3.5/lib/initializer.rb:113:in`run'
    from /Users/fuzz/Projects/web/config/environment.rb:13:in `<top (required)>'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in`require'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `block in require'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:521:in`new_constants_in'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/activesupport-2.3.5/lib/active_support/dependencies.rb:156:in `require'
    from /opt/local/lib/ruby1.9/gems/1.9.1/gems/rails-2.3.5/lib/commands/server.rb:84:in`<top (required)>'
    from script/server:3:in `require'
    from script/server:3:in`<main>'

**Comment by josevalim** [comment]
Please install inherited resources 1.0.3.

**Comment by fuzz** [comment]
This fixes it.  Thank you.

**Comment by kevwil** [comment]
1.1.0 isn't backwards compatible, then? as is claimed in the readme?

**_edit**_ oops, read that as "backward compatible", sorry for jumping to conclusions.

**Comment by josevalim** [comment]
From the README:

Inherited Resources master branch is now supports Rails 3 and is backward incompatible.

Yes, it's backward incompatible.
