### ISSUE TITLE
"defaults :instance_name" in base controller doesn't work for descending controllers

### ISSUE THREAD

**Issue by jmuheim** [activeadmin/inherited_resources#402]
I have a `Boilerplate` model which has two descending models:
- `BoilerplateOriginal`
- `BoilerplateCopy`

I'm using single table inheritance for this, as both models share pretty the same attributes. And because they also look quite the same, I want to use the same views for them.

I tried setting `defaults instance_name: 'boilerplate'` in `BoilerplatesController`, but this doesn't seem to work: I have to put it in both `BoilerplateOriginalsController` and `BoilerplateCopiesController`. This isn't DRY afaik. Why's that?

**Comment by rafaelfranca** [comment]
This gem is deprecated and no future support will be given, sorry.
