### ISSUE TITLE
Incorrect resource_request_name in isolated engines

### ISSUE THREAD

**Issue by brianswko** [activeadmin/inherited_resources#403]
`resource_request_name` for models within isolated engines should not include the engine name.

See https://github.com/rails/rails/blob/master/activemodel/lib/active_model/naming.rb#L304

**Comment by alexkravets** [comment]
+1

**Comment by flyfy1** [comment]
+1. Got that issue from ActiveAdmin

**Comment by Turkish** [comment]
+1

**Comment by varyonic** [comment]
Closed by #404
