### ISSUE TITLE
New release with Rails 5 support on rubygems.org

### ISSUE THREAD

**Issue by MrMarvin** [activeadmin/inherited_resources#415]
Hi guys,

thank you for taking care of this project! We do use it with activeadmin in one of our Rails5 apps. Unfortunately there was no release of this gem to rubygems.org in quite some time and the last version available does not yet support Rails5. The missing commit seem to be ecd3a489889de0f9bfa78c5f27359964f33e9671.

Do you think it would be reasonable to publish a new release (maybe even as a .pre version)?

Thanks!

**Comment by rafaelfranca** [comment]
Sure, but seems that it is causing problem https://github.com/josevalim/inherited_resources/issues/414. I don't have time (neither motivation) to investigate it, could you check?

**Comment by rafaelfranca** [comment]
Never mind, found it. I'll release later.

**Comment by BenFenner** [comment]
We're using this too and would appreciate a release that supports Rails 5.
Thanks!

**Comment by MrMarvin** [comment]
Hi @rafaelfranca,
thanks again for taking care of this project!

Any news on this? Can we expect a release anytime soon?

Cheers

**Comment by wvteijlingen** [comment]
Any news @rafaelfranca? Would be a great help to have this released :).

**Comment by OlegSmelov** [comment]
@rafaelfranca Ping 😄

**Comment by rafaelfranca** [comment]
Hey thanks for the ping. Like it is already stated in the README for more than 4 years this gem is deprecated. While I know that many of you rely on it, you all should be aware that releases can take ages, since there is no motivation by any of the maintainers to work on this gem. Pinging me on issues will only remove any motivation that I may have to do a release.

**Comment by rafaelfranca** [comment]
BTW, I'd love some help to fix this issue since it is what is blocking the Rails 5 release and I don't want to work on it https://github.com/josevalim/inherited_resources/issues/417

**Comment by OlegSmelov** [comment]
Here's my take on it: #418

**Comment by OlegSmelov** [comment]
Is there anything left to do? Can I help with the release somehow?

**Comment by varyonic** [comment]
:shipit: `gem push` please.

**Comment by rafaelfranca** [comment]
Closed by the 1.7.0 release.
