### ISSUE TITLE
loading issue with Rails 5 in some cases

### ISSUE THREAD

**Issue by timoschilling** [activeadmin/inherited_resources#417]
There happens a strange error when Rails 5 is in use and a engine is used and a namespace which has no engine is used.

All this happens if you use Rails5, ActiveAdmin and the Knock or MailyHerald::Webui gem together.

Here is a App to reproduce the error: https://github.com/brentmulligan/aa-knock-issue
Stacktrace for the error: https://gist.github.com/brentmulligan/ad2ff32b27c3a20b0c9db8e5acd90ca7
(THX to @brentmulligan)

After some debugging I found out that this rescue don't capture the LoadError.

I have tried to fix it in #416, but it brings new problems.

related to: activeadmin/activeadmin#4532

**Comment by Frexuz** [comment]
Any progress on this (for activeadmin/activeadmin#4532)? Still stopping us from going live :/
The fix in #418 works, but since it's not merged, I'm not sure if its safe to use?
