### ISSUE TITLE
Gemfile lock has actionpack (>= 3.2, < 5), while current version of  actionpack needed is 5.0.1

### ISSUE THREAD

**Issue by devgoyal** [activeadmin/inherited_resources#419]
While the gemspec has the correct dependency: s.add_dependency("actionpack", ">= 3.2", "< 5.1"),  the gemfile lock has actionpack (>= 3.2, < 5), which is causing version conflict in Active Admin with rails 5.0, which requires actionpack 5.0.1. Can somebody rebuild the lock file?
Thanks

**Comment by devgoyal** [comment]
As per http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/, When developing a gem, do not check your Gemfile.lock into version control. Maybe this is the issue here that Gemfile.lock is checked in. If so, can the author remove this file? Thanks.

**Comment by rafaelfranca** [comment]
The gemfile lock is not a problem. Make sure your project is using the master branch of this project.
