### ISSUE TITLE
Dropping Ruby version support in minor versions

### ISSUE THREAD

**Issue by tf** [activeadmin/inherited_resources#423]
Depending on [`has_scope ~> 0.6` instead of `~> 0.6.0.rc`](https://github.com/activeadmin/inherited_resources/commit/d50b05f7e9e36dd45f065871e836a57a33ba4118) now allows for `has_scope 0.7` which [drops support for Ruby < 2.1.7](https://github.com/plataformatec/has_scope/blob/master/has_scope.gemspec#L25). I fully understand, that these Ruby versions are not maintained anymore. Still, I think dropping Ruby versions in a minor version update (1.6 to 1.7 in this case) is a SemVer violation. To avoid situations like this, it think it would be better to avoid optimistic version constraints for 0.x gems.

**Comment by rafaelfranca** [comment]
In this case it is not inherit resources that is dropping support. You are still able to use `has_scope` 0.6, so we can say that inherit resources still support Ruby < 2.1.7 and didn't dropped support to any version in a minor version update.

**Comment by tf** [comment]
Well it broke the build of my gem. I still think, depending on 0.x gems is an anti pattern. But this might be a matter of taste.

**Comment by rafaelfranca** [comment]
I understand it broke the build of your gem, but you still can in your gem to specify the version of has_scope that doesn't break the build. For the point of view of inherit resources not allowing users to use 0.7 because some users may be using a version that 0.7 doesn't support is also an anti-pattern. We still support 0.6 so users can chose which version they want to use.

**Comment by tf** [comment]
Yes, I see. I guess the core issue is that Bundler does not take Ruby version dependencies into consideration. In an ideal world, Bundler should be able to find out that it has to use `has_scope 0.6` instead of `0.7` if I am using Ruby 2.1.0. So, while from a strict SemVer perspective, I'd argue that `inherited_resource` would have only been allowed to permit `has_scope 0.7` in a major version update (since that's a potentially breaking change for people using certain Ruby versions), I see the pragmatic choice you made here. Might be worth a changelog entry though.

**Comment by rafaelfranca** [comment]
Done. Could you review the message? https://github.com/activeadmin/inherited_resources/pull/424
