### ISSUE TITLE
Rails test environment crashes: LocalJumpError w/ ruby 2.3.0

### ISSUE THREAD

**Issue by lnaia** [activeadmin/inherited_resources#428]
Recently this gem is crashing when ran under the test environment.
It was from a recent commit: 
https://github.com/activeadmin/inherited_resources/commit/4cc8ced1f7083d5f03c32777eb66333453da62d7

Meanwhile, I've just downgraded this gem to a previous stable release.

lnaia@delta ~/projects/shiba $ bundle exec rake db:migrate:reset --trace
** Invoke db:migrate:reset (first_time)
** Invoke db:drop (first_time)
** Invoke db:load_config (first_time)
** Execute db:load_config
** Invoke db:check_protected_environments (first_time)
** Invoke environment (first_time)
** Execute environment
rake aborted!
LocalJumpError: break from proc-closure
~/.bundler/ruby/2.3.0/inherited_resources-f04e0422213f/lib/inherited_resources.rb:30:in `block in <top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/lazy_load_hooks.rb:43:in `instance_eval'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/lazy_load_hooks.rb:43:in `execute_hook'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/lazy_load_hooks.rb:50:in `block in run_load_hooks'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/lazy_load_hooks.rb:49:in `each'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/lazy_load_hooks.rb:49:in `run_load_hooks'
/var/lib/gems/2.3.0/gems/actionpack-5.0.1/lib/action_controller/api.rb:145:in `<class:API>'
/var/lib/gems/2.3.0/gems/actionpack-5.0.1/lib/action_controller/api.rb:88:in `<module:ActionController>'
/var/lib/gems/2.3.0/gems/actionpack-5.0.1/lib/action_controller/api.rb:5:in `<top (required)>'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `block in require'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:259:in `load_dependency'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/dependencies.rb:293:in `require'
/var/lib/gems/2.3.0/gems/jbuilder-2.6.1/lib/jbuilder/railtie.rb:20:in `block (2 levels) in <class:Railtie>'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/lazy_load_hooks.rb:43:in `instance_eval'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/lazy_load_hooks.rb:43:in `execute_hook'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/lazy_load_hooks.rb:33:in `block in on_load'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/lazy_load_hooks.rb:32:in `each'
/var/lib/gems/2.3.0/gems/activesupport-5.0.1/lib/active_support/lazy_load_hooks.rb:32:in `on_load'
/var/lib/gems/2.3.0/gems/jbuilder-2.6.1/lib/jbuilder/railtie.rb:19:in `block in <class:Railtie>'
/var/lib/gems/2.3.0/gems/railties-5.0.1/lib/rails/initializable.rb:30:in `instance_exec'
/var/lib/gems/2.3.0/gems/railties-5.0.1/lib/rails/initializable.rb:30:in `run'
/var/lib/gems/2.3.0/gems/railties-5.0.1/lib/rails/initializable.rb:55:in `block in run_initializers'
/usr/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
/usr/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
/usr/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
/usr/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
/usr/lib/ruby/2.3.0/tsort.rb:347:in `each'
/usr/lib/ruby/2.3.0/tsort.rb:347:in `call'
/usr/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
/usr/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
/usr/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
/var/lib/gems/2.3.0/gems/railties-5.0.1/lib/rails/initializable.rb:54:in `run_initializers'
/var/lib/gems/2.3.0/gems/railties-5.0.1/lib/rails/application.rb:352:in `initialize!'

**Comment by varyonic** [comment]
See also http://stackoverflow.com/questions/42191475/rails-5-active-admin-installation-issue/

**Comment by deivid-rodriguez** [comment]
Quick question. Could you show the output of `ruby -v`? And if not running the latest patch level of your version, could you upgrade your ruby and try again?

**Comment by lnaia** [comment]
@deivid-rodriguez currently I'm using:
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]

I've installed nvm, w/ latest stable:
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-linux]

```
$ RAILS_ENV=test bundle exec rails test
/home/lnaia/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:51: warning: constant ::Fixnum is deprecated
/home/lnaia/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.1/lib/active_support/xml_mini.rb:52: warning: constant ::Bignum is deprecated
/home/lnaia/.rvm/gems/ruby-2.4.0/gems/activesupport-5.0.1/lib/active_support/core_ext/numeric/conversions.rb:138: warning: constant ::Fixnum is deprecated
/home/lnaia/.rvm/gems/ruby-2.4.0/bundler/gems/inherited_resources-f04e0422213f/lib/inherited_resources.rb:30:in `block in <top (required)>': break from proc-closure (LocalJumpError)
```

**Comment by deivid-rodriguez** [comment]
Thanks Rafael!

**Comment by lnaia** [comment]
Thank you for the update Rafael!
