### ISSUE TITLE
Rails 3: No routes matches

### ISSUE THREAD

**Issue by nordringrayhide** [activeadmin/inherited_resources#44]
Rails 3 beta, Ruby 1.87

class People < AplicationController
  inherited_resources
end

routes.rb
...
resources :people
...

view

link_to 'People', people_path

Error: No routes matches /people

**Comment by josevalim** [comment]
It needs to be PeopleController.

**Comment by nordringrayhide** [comment]
Sorry, it's my misprint
i have PeopleController & UserController but error remains

**Comment by josevalim** [comment]
It should be: "inherit_resources" and not "inherited_resources".

**Comment by nordringrayhide** [comment]
O. Yes. It's work.

But

class PeopleController < ApplicationController
  inherited_resources_blablala
end

should say something like 'unknown method `inherited_resources_blablala`' 

but  ActionController::RoutingError (No route matches "/people"):

only...

thanks!

**Comment by josevalim** [comment]
This is a Rails bug which was already fixed. :)
