### ISSUE TITLE
undefined method `stringify_keys' after upgrade Rails 3.2 -> 4.0

### ISSUE THREAD

**Issue by mbautista** [activeadmin/inherited_resources#441]
Hello,
We upgraded our Rails 3.2 app to Rails 4.0 and found that the create action does not work anymore in our controllers using inherited_resources 1.7.2, we have the following error : 

`undefined method `stringify_keys' for #<Array:0x9680d874>
at lib/active_record/mass_assignment_security/attribute_assignment.rb, line 51

      def assign_attributes(new_attributes, options = {})
        return if new_attributes.blank?

        attributes                  = new_attributes.stringify_keys <- HERE
        multi_parameter_attributes  = []
        nested_parameter_attributes = []
        previous_options            = @mass_assignment_options
        @mass_assignment_options    = options`

It seems that inherited_resources wraps the new_attributes Hash into an Array before passing it to assign_attributes, so the stringify_keys method is undefined.

We use protected_attributes 1.1.4 with attr_accessible defined in our models (we have lots of models/controllers so we would like to avoid refactoring our models/controllers if possible).

I found this bug [here](https://stackoverflow.com/questions/9421668/activeadmin-throws-undefined-method-stringify-keys), but I don't have enough reputation to participate.

For now we ended up overriding the assign_attributes method in our models :

` def assign_attributes(new_attributes, options = {})
    if new_attributes.is_a?(Array)
      new_attributes = new_attributes.first
    end
    super new_attributes, options
  end`

Does anybody have a better fix for this please ?

Thank you :)

**Comment by varyonic** [comment]
> It seems that inherited_resources wraps the new_attributes Hash into an Array

I would look into that some more, I think it is probably something else.

**Comment by varyonic** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.

**Comment by varyonic** [comment]
I’m going to close this since you haven’t responded. Please feel free to update this issue with additional information so it can be reconsidered.
