### ISSUE TITLE
resource_path unable to generate the correct path

### ISSUE THREAD

**Issue by lcdss** [activeadmin/inherited_resources#447]
Hi,
I have a controller that acts as a transparent layer between two models (A and B) using a model (C) that merges two other tables through a database view. The model C defines a polymorphic relationship (called related) to the models A and B. When the index view of my controller C is renderized, I pass the object.related to the resource_path and it returns an error because the method controller_c_path does not exist, while the expected is controller_a_path or controller_b_path, depending of the related model type. I would like to override his behavior to use the first param information (object.related) instead of the currently resource (controller c).

**Comment by varyonic** [comment]
Some sample code might help, I recommend posting on [StackOverflow](https://stackoverflow.com/questions/tagged/activeadmin) and adding a link here.

**Comment by lcdss** [comment]
Alright! I will add more info when I get at home. Maybe can be a detail to improve the gem or it's just a bad way to do something.
