### ISSUE TITLE
Rails 3 problem with class_inheritable_reader

### ISSUE THREAD

**Issue by faust45** [activeadmin/inherited_resources#45]
Hi!
I try use rails 

git 'git://github.com/rails/rails.git'
gem 'activesupport',     '~> 3.0.0.beta1', :require => 'active_support'

git 'git://github.com/josevalim/inherited_resources.git'
gem 'inherited_resources',  '~> 1.1.0'

and catch trouble 
class_inheritable_hash :resources_configuration

behaviour is fail in 
module InheritedResources
  module ClassMethods

self.resources_configuration ||= {}
is fail
self.resources_configuration.nil? == true
but resources_configuration ||= {}
resources_configuration.nil? == false
is work success.

Can any one explain this?

**Comment by josevalim** [comment]
I cannot reproduce. Can you please try adding a failing test case to IR? In order to run IR tests, you will need a Rails gem from master, which you can get by running `rake install` on rails git repository.
