### ISSUE TITLE
Maintaining has_scope and responders dependencies

### ISSUE THREAD

**Issue by javierjulio** [activeadmin/inherited_resources#462]
After doing some maintenance work here on InheritedResources, I realize we depend on some gems: has_scope and responders that like this one may not have much in terms of maintenance going on, although in general they seem to be active which is good. 👍🏻

@deivid-rodriguez I noticed you and other @activeadmin/maintainers have made reviews on has_scope. Do we have some access rights to that repository and responders? Not that I'm expecting merge capabilities, but do you think Rafael would help us get in PRs for has_scope and responders to continue to update them to make sure they are current with future Rails support, etc.?

Outside of what we own in the ActiveAdmin organization I'm not familiar with what we may have some access too (I am familiar with the responders code base but not has_scope though) so I figured I'd ask. Thanks!

**Comment by deivid-rodriguez** [comment]
I don't have access to any of those repositories, not sure if any other activeadmin maintainer has.

However, they don't seem to need many updates except for major Rails releases and in those cases usually the community takes care of the upgrade and Rafael takes good care of reviewing the PRs, so I think we should be good for now! :+1:

**Comment by rafaelfranca** [comment]
responders and has_scope are really stable. They are maintained and you don't see activity because they don't require any changes.

responders is a gem that always have support to the last version of rails because Shopify uses it an Shopify runs rails from master.

We don't use has_scope, but it usually don't require any change after a rails release.

**Comment by javierjulio** [comment]
@rafaelfranca that's great to know, appreciate all the info, thanks!
