### ISSUE TITLE
protected method for finders

### ISSUE THREAD

**Issue by croaky** [activeadmin/inherited_resources#5]
I've got a controller like this:

```
class BrandsController < InheritedResources::Base
  before_filter :authenticate, :ensure_brand_manager

  actions    :new, :create
  belongs_to :sponsor

  protected

  def ensure_brand_manager
    sponsor = Sponsor.find(params[:sponsor_id])
    unless sponsor.brand_managers.include?(current_user)
      flash[:failure] = "Permission denied"
      redirect_to root_path
    end
  end
end
```

The line I'd like to push off to Inherited Resources is:

```
sponsor = Sponsor.find(params[:sponsor_id])
```

On this controller, I'd like there to be protected methods available to me that do:

```
sponsor = Sponsor.find(params[:sponsor_id])
brand = Brand.find(params[:id])
```

and/or:

```
parent = Sponsor.find(params[:sponsor_id])
resource = Brand.find(params[:id])
```

Making these available in all Inherited Resources controllers would save me a line in about all of my controllers while maintaining readability.

What do you think?

**Comment by josevalim** [comment]
Dan,

Currently you can call "resource", that will set both the @sponsor and @brand instance variables.

But currently, there is no way to ask inherited resources to load one specific parent. With resource, your example could be rewritten as:

```
unless resource.sponsor.brand_managers.include?(@current_user)
```

If that does not solve your issue and you have to keep the filter, I would recommend to cache @sponsor in the instance variable, so Inherited Resources would check for it and do not query the database again:

```
@sponsor = Sponsor.find(params[:sponsor_id])
unless @sponsor.brand_managers.include?(current_user)
  flash[:failure] = "Permission denied"
  redirect_to root_path
end
```

Inherited Resources always check for the instance variable before querying the database.

**Comment by croaky** [comment]
Okay, that's a good call. Ran it by a couple of guys at work. They pointed out I should be using a finder to return 404.

```
class BrandsController < InheritedResources::Base
  before_filter :authenticate, :authorize_brand_manager_belongs_to_sponsor

  actions    :new, :create
  belongs_to :sponsor

  protected

  def authorize_brand_manager_belongs_to_sponsor
    @sponsor = Sponsor.find(params[:sponsor_id])
    @sponsor.brand_managers.find(current_user.id)
  end
end
```

This is looking better. I'd like to be able to use the resource.sponsor style but that's not available in before_filters, right?

I'd like to kill the before_filter if possible.

**Comment by croaky** [comment]
This would be an awesome option, too:

```
def begin_of_association_chain
  current_user
end
```

Looks like it tries to do current_user.sponsors, though, instead of current_user.sponsor.

I think that would be ideal, though:

```
current_user.sponsor.find(params[:sponsor_id])
```

Is this a potential improvement to IR? If so, any tips on where to patch?

**Comment by josevalim** [comment]
The resource is a controller method, that said, it's available in before_filter.

Good use of begin_of_association_chain. But wasn't it supposed to do:

```
current_user.sponsors.find(params[:sponsor_id])
```

If you are doing a find, you need _sponsors_ and not _sponsor_.

**Comment by croaky** [comment]
The relationship is:

User belongs_to :sponsor
Sponsor has_many :brand_managers, :class_name => "User"
Sponsor has_many :brands

So, in script console, I can do things like:

```
user.sponsor
user.sponsor.brands
```

I guess begin_of_association_chain isn't the right fit here?

**Comment by croaky** [comment]
Also, I think the problem with "resource" I was having in the before_filter was because I'm working with new and create actions where there is no resource established. In that case, I'll always get:

```
ActiveRecord::RecordNotFound: Couldn't find Brand without an ID
```

**Comment by josevalim** [comment]
If an user belongs to sponsor, I guess you don't need to send the sponsor_id. So you can you have routes like:

```
/sponsor/brands
```

And your controller:

```
class BrandsController < InheritedResources::Base

  protected
    def begin_of_association_chain
      current_user.sponsor
    end
end
```

With that kind of url, you ensure that a user cannot access other users resources.

**Comment by josevalim** [comment]
For new and create you can use build_resource, it's resource twin brother for new and create. :)

**Comment by croaky** [comment]
Jose,

Simplifying the routes into a flatter structure was exactly the right move. Great call!

I'm also now successfully using the begin_of_association_chain approach for access control on another controller that belongs_to :sponsor. Finding it to be very clean, very few lines of code, and easy to test. It also forced me into a nice delegation in the models, keeping my future Law of Demeter violations to a minimum!

**Comment by josevalim** [comment]
Awesome! Yes, after those months using Inherited Resources, I realized it helps a lot in the code design, including with the use of nested controllers, as you guys from Thoughtbot wrote about some time ago.

I keep the logic in the model, which is easy to test, and define well the responsibilities and routes.

And talking about testing, I do not test controllers anymore (rspec controller tests which are done with mocking), except those controllers that does not follow Inherited Resources pattern.

Controller and different conditions are very well tests in Inherited Resources and all changes we do through Inherited Resources API (like changing the redirection url) are verified in integration specs.

Can I close this ticket? :)

**Comment by croaky** [comment]
Absolutely! I tried clicking "Comment and Close" after my last one. I wrote up a blog post about this as well, promoting IR a bit. Queued it up, should go live sometime in the next few days.

**Comment by josevalim** [comment]
Awesome! Thanks Dan!
