### ISSUE TITLE
rails3 suddenly html-escapes inherited_resource html responses

### ISSUE THREAD

**Issue by argl** [activeadmin/inherited_resources#50]
as the subject says, all of a sudden (around april 21/22 2010), html responses from an inherited_resources controller escapes the html (yikes!). using edge rails3.

**Comment by josevalim** [comment]
I cannot reproduce it. Just created a new app from Rails source code using Inherited Resources and everything works.

I also doubt this is an Inherited Resources issues. Are you using Haml? Which Inherited Resources version? Please give me more information.

**Comment by argl** [comment]
i doubt it as well ;) yes, we're using haml for the html, latest git version as well. heres the relevant ections form the app's gemfile:

```
gem "rails", :git => "git://github.com/rails/rails.git"
gem 'haml', :git => 'git://github.com/nex3/haml.git'
gem 'inherited_resources', :git => "git://github.com/josevalim/inherited_resources.git"
```

i'll try to create a minimal test case to reproduce and report back.

thanks a 10^6 for the quick response.

**Comment by josevalim** [comment]
It works fine with ERB. I bet on Haml issue. :) Please let me know!

**Comment by argl** [comment]
i think we've found it, we were rendering a haml partial from an erb template (don't ask). switching over to using haml only seems to solve the issue. nothing wrong with inherited_resources.

**Comment by josevalim** [comment]
Ok, thanks for reporting back! Closing!
