### ISSUE TITLE
destroy!(options){} vs destroy!{}

### ISSUE THREAD

**Issue by grimen** [activeadmin/inherited_resources#51]
<pre>
class UserSessionsController < InheritedResources::Base
  respond_to :html

  actions :new, :create, :destroy

  def create
    create!(:notice => 'Successfully logged in.') { root_url }
  end

  # FAILS: "Missing template user_sessions/destroy.erb in view path app/views"
  def destroy
    destroy!(:notice => 'Successfully logged out.') { root_url }
  end

  # WORKS:
  # def destroy
  #   destroy! do |format|
  #     format.html do
  #       flash[:notice] = 'Successfully logged out.'
  #       redirect_to root_url
  #     end
  #   end
  # end

end
</pre>

Bug?

Gems: Rails 2.3.5 + InheritedResources 1.0.6, and my friend got the same issue

**Comment by josevalim** [comment]
Can you please try to reproduce in a smaller application or in IR test suite?

**Comment by josevalim** [comment]
I discussed with Grimen and the issue is that he was doing a GET request. Bear in mind that responders are sensible to the HTTP Verb, so the results change depending on the HTTP Verb.
