### ISSUE TITLE
cancan 

### ISSUE THREAD

**Issue by markmcdonald51** [activeadmin/inherited_resources#55]
Hey Jose, et. al,

Thanks for creating my new  gem. It works really great with one exception.

When I use cancan (http://github.com/ryanb/cancan) for rights/roles  to it seem to not set the belongs_to :assoc when creating a new record.  I am played around with this to know that this is the problem. Just wondering if you have encountered this problem.

Thanks in advance.

Keep up the great work!
Mark McDonald

**Comment by josevalim** [comment]
I am not familiar with any issue with cancan. Please try the mailing list, you may get mre feedback there.
