### ISSUE TITLE
Can't override Object#to_json: SystemStackError (stack level too deep)

### ISSUE THREAD

**Issue by sergio-fry** [activeadmin/inherited_resources#57]
When I redeclare to_json method, controller raises:
SystemStackError (stack level too deep): http://gist.github.com/439203

And I can't understand, why You do that vendor/gems/inherited_resources-1.0.6/lib/inherited_resources/legacy/responder.rb:  
    # Undefine :to_json and :to_yaml since it's defined on Object
    undef_method(:to_json) if method_defined?(:to_json)
    undef_method(:to_yaml) if method_defined?(:to_yaml)

**Comment by sergio-fry** [comment]
oops.. my fault!

**Comment by josevalim** [comment]
Could you please elaborate why it's your fault? I was already bitten by it myself and I was planning to change this API.

**Comment by sergio-fry** [comment]
My AR#to_json was private and I always had "Missing template error". I've looked at source code of your plugin and found these undefs and commented them. After restaring server I've noticed, that my AR#to_json is private. I've changed this method to public and got SystemStackError. After uncommenting undefs I've forgotten to restart server. After restarting it works just fine.

So, there is no problem to redeclare model to_json method.

But I still can't  understand, why we need these lines vendor/gems/inherited_resources-1.0.6/lib/inherited_resources/legacy/responder.rb:
    # Undefine :to_json and :to_yaml since it's defined on Object
    undef_method(:to_json) if method_defined?(:to_json)
    undef_method(:to_yaml) if method_defined?(:to_yaml)

**Comment by josevalim** [comment]
If we don't undefine them, the responder would call the Object#to_json implemented in the Object, which is definitely not what we want, raising the SystemStackError you got!

**Comment by sergio-fry** [comment]
I'll try to dig it :) later.
