### ISSUE TITLE
Method missing crash due to duck typing in UrlHelper

### ISSUE THREAD

**Issue by ce07c3** [activeadmin/inherited_resources#573]
```rb
arg.respond_to?(:permitted?) ? arg.to_h : arg
```

https://github.com/activeadmin/inherited_resources/blob/master/lib/inherited_resources/url_helpers.rb#L200

If resource passed in has `permitted?` but not `to_h` method, this will crash.

**Comment by javierjulio** [comment]
I would accept a PR for this change. Thank you.
