### ISSUE TITLE
Make parent method a helper method so we can use it on the views too

### ISSUE THREAD

**Issue by knoopx** [activeadmin/inherited_resources#59]
Why is not parent method available on the views just like collection on resource ones? Is there any reason or simply is not implemented?

Consider this example:

```
class VideosController < ...
  inherit_resources
  belongs_to :user
  helper_method :parent # this is the missing logic I *was expecting* from     inherited_resources
end
```

So I can write in my view:

```
%h1= "%s video's" % h(parent.username)  
%ul
  - collection.each do |resource|
      %li= h(resource.title)
```

**Comment by josevalim** [comment]
Patch please! Or fork it and send me a pull request!

**Comment by knoopx** [comment]
ok, i've been playing with it and found that :parent, :parent_type, :parent_class and :parent? helpers are only made available for polymorphic associations. I've patched it so they are now available for all types of belong_to's. However I don't know how to run the tests, i'm always getting missing dependencies/constants. I'm working with the v1.0.6 tag but I see test cases depend on rails3 (active_model, railities...), is that correct?

**Comment by josevalim** [comment]
On 1.0.6, you need to use Rails 2.3. If you have Rails 3 installed, it may cause conflicts. (I recommend you to use RVM with a Rails 2.3 gemset).

**Comment by contentfree** [comment]
Have you figured out how to send a patch to Jose, knoopx? This is exactly what I'm looking for.

**Comment by knoopx** [comment]
not me but lucasmazza, don't know if he already contacted jose. he patched both versions: http://github.com/lucasmazza/inherited_resources/commit/143a464bd6dcff942aa6aff0df7c25c84edee536

**Comment by lucasmazza** [comment]
Applied, but only on master http://twitter.com/josevalim/status/22621928441
