### ISSUE TITLE
parent_url

### ISSUE THREAD

**Issue by josevalim** [activeadmin/inherited_resources#6]
Consider also adding child_url and sibling_url.

**Comment by josevalim** [comment]
Done, parent_url. Others will be added as needed.

**Comment by sobrinho** [comment]
I don't understand how the github votes works, i tryed to vote +1 but this get -1, damn!

I guess the child_url are a great option to add to inherited resources. Like that:

<pre><code>class MyController < InheritedResources::Base
  belongs_to :model
end</code></pre>


<pre><code>child_url(:model)</code></pre>


Can you do this? :)

**Comment by sobrinho** [comment]
Sorry, my suggestion in really are:

<pre><code>children_url(:model)</code></pre>


Or really is child_url? I don't know, but you understand the feature that I requested :)

**Comment by josevalim** [comment]
Please open a new ticket or even better, try to provide a patch! ;)
