### ISSUE TITLE
nested_belongs_to with a singleton resource

### ISSUE THREAD

**Issue by dfmonaco** [activeadmin/inherited_resources#60]
Hi José, I can't figure it out how can I represent the following situation in a controller:

Models:

```
Project < AR::Base
    has_one :measurement
end

Measurement < AR::Base
    belongs_to :project
    has_many :measurement_lines
end

MeasurementLines < AR::Base
    belongs_to :measurement
end
```

in config/routes.rb:

```
resources :projects do
    resource :measurement do
        resources :measurement_lines
    end
end
```

I have tried the following in the Controller (among other things):

```
class MeasurementLinesController < InheritedResources::Base
    belongs_to :project, :singleton => true do
        belongs_to :measurement
    end
end
```

But it's not working, Am I doing it well?, could you tell me the right way of doing it?
Thank you for your time.

**Comment by josevalim** [comment]
At the moment you specify a singleton resource, Inherited Resources cannot build the chain anymore, so you need to overwrite begin_of_association_chain or define @project in a before filter.
