### ISSUE TITLE
Should respect return value of ActiveRecord::Base#destroy

### ISSUE THREAD

**Issue by jonleighton** [activeadmin/inherited_resources#63]
ActiveRecord::Base#destroy might return false if one of the callback prevents the record from being destroyed. i_r should check this value and make a "failure" response in this case.

**Comment by josevalim** [comment]
The way IR works is by checking if you added an error. So basically, you need to ensure errors.empty? return false. We cannot check for #destroy result because the part that calls destroy and the responder (which chooses the behavior), are completely decoupled.

**Comment by jonleighton** [comment]
Interesting, I had not considered using errors when destroying an object before.

It still seems odd not to check the return value of destroy, but thanks for your help. Perhaps the responder could check record.destroyed?

**Comment by josevalim** [comment]
Not really, since record.destroyed? is not part of ActiveModel API so I cannot rely on it.
