### ISSUE TITLE
Incorrect behavior with namespaces in Rails 3 

### ISSUE THREAD

**Issue by kossnocorp** [activeadmin/inherited_resources#64]
To make Seminar::PeopleController work correctly I should type:

defaults \
  :resource_class  => Seminar::Person,
  :collection_name => 'seminar_people',
  :instance_name   => 'seminar_person'

Same for other namespaced controllers.

It's ok, but avoid from this is possible.

**Comment by josevalim** [comment]
IR supports another kind of namespace. Imagine you have a model User views from both UsersController and Admin::UsersController. This is the scenario IR handles by default. In your case, I suggest for you to have a method called namespace_defaults that will call defaults with the proper values.

**Comment by kossnocorp** [comment]
Thanks, I got it
