### ISSUE TITLE
Feature suggestion: default shared views

### ISSUE THREAD

**Issue by fredwu** [activeadmin/inherited_resources#65]
Using inherited_resources we effectively reduced the amount of duplication in our controllers, but our views still remain replicated (for the most part).

May I suggest that we use a set of default views, and if a 'normal' view file does not exist, the action automatically renders the default view file. We can also make a generator to generate the default views for modification (just like we do in Devise).

If this is something that can be incorporated into the project, I'm happy to start working on it in a fork. :-)

**Comment by nowhereman** [comment]
You should fork this plugin http://github.com/ianwhite/inherit_views

**Comment by josevalim** [comment]
Yeah, it can definitely be implemented apart from Inherited Resources.

**Comment by fredwu** [comment]
Thanks guys. Tada! http://github.com/fredwu/inherited_resources_views :-)
