### ISSUE TITLE
Breaking change in Rails 5.2.4.6

### ISSUE THREAD

**Issue by creddy** [activeadmin/inherited_resources#665]
Today I was attempting to update Rails to 5.2.4.6 to address these [CVEs](https://weblog.rubyonrails.org/2021/5/5/Rails-versions-6-1-3-2-6-0-3-7-5-2-4-6-and-5-2-6-have-been-released/)

And noticed an error in `activeadmin`

```
ActionView::Template::Error (Please use symbols for polymorphic route arguments.):
    1: insert_tag renderer_for(:index)
```

I'm not sure if this is the right fix, but I traced the issue back to https://github.com/activeadmin/inherited_resources/blob/64f1dfd05dec868f98cabba7f09e2835b4d348b5/lib/inherited_resources/url_helpers.rb#L57

If changed to:

```
        # Add route_prefix if any.
        unless resource_config[:route_prefix].blank?
          if polymorphic
            resource_ivars << resource_config[:route_prefix].to_sym
          else
            resource_segments << resource_config[:route_prefix]
          end
        end
```
I no longer see the exception. Please let me know if I can provide any more information or help in anyway. Thank you so much for the gem and maintaining it!

**Comment by ndbroadbent** [comment]
Thanks @creddy! I will try using a fork with this change. FWIW I believe this applies to all of the new Rails versions: 5.2.4.6, 5.2.6, 6.0.3.7, 6.1.3.2

**Comment by ndbroadbent** [comment]
I can confirm that this `to_sym` change is the only thing that was required to fix the crash and get my CI builds passing again: https://github.com/DocSpring/inherited_resources/commit/20d2eae2ee7b56c8a8494a6fb5fbc5afbb0bec7b

**Comment by deivid-rodriguez** [comment]
Yeah, same fix was already suggested at https://github.com/activeadmin/inherited_resources/pull/662#issuecomment-832980388.
