### ISSUE TITLE
Can't remove notice after actions

### ISSUE THREAD

**Issue by crystalneth** [activeadmin/inherited_resources#67]
Neither destroy!(:notice => "") or with nil works.  I don't want any notice after destroy....

**Comment by carlosantoniodasilva** [comment]
Did you try setting it to nil (or empty) inside the locale file?

**Comment by crystalneth** [comment]
I haven't tried that, although I really would like this on a case-by-case basis, not globally.

**Comment by josevalim** [comment]
Yes, you can add "" as empty string in your locale file on a case-by-case basis. Please check both Responders and InheritedResources README.
