### ISSUE TITLE
Include more responders

### ISSUE THREAD

**Issue by rafaelfranca** [activeadmin/inherited_resources#68]
I want to include more responders in InheritedResources such as Responders::CollectionResponder

**Comment by josevalim** [comment]
Just do in an initializer: InheritedResources::Base.responder = YourResponder. If this does not work, try adding inside a config.to_prepare {  } block.

**Comment by rafaelfranca** [comment]
both options did not work. Inherited Resources used your default responder

**Comment by rafaelfranca** [comment]
I'm using rails 3 with inherited_resources 1.1.2 and responders 0.6.2.

In my lib/application_responder.rb I have

```
class ApplicationResponder < ActionController::Responder
    include Responders::FlashResponder
    include Responders::HttpCacheResponder
    include Responders::CollectionResponder
end
```

and in config/initializers/responders.rb i tried

```
InheritedResources::Base.responder = ApplicationResponder
```

and

```
MyApp::Application.config.to_repare { InheritedResources::Base.responder = ApplicationResponder }
```

All the controllers that inherit for InheritedResources::Base only have the defaults responders.
The controllers that inherit for ApplicationController use the responder included in ApplicationResponder.
