### ISSUE TITLE
Namespaced resources does not working

### ISSUE THREAD

**Issue by alec-c4** [activeadmin/inherited_resources#70]
Hi,
There are a problem with namespaced resources with Inherited_resources. I have generated some scaffold with
     rails g scaffold Oauth/Client name:string client_id:string client_secret:string redirect_uri:string

and on attempt to /oauth/clients i've got NoMethodError

some logs:

Started GET "/oauth/clients" for 127.0.0.1 at 2010-08-31 02:18:47 +0400
  Processing by Oauth::ClientsController#index as HTML
Completed   in 1ms

NoMethodError (You have a nil object when you didn't expect it!
You might have expected an instance of Array.
The error occurred while evaluating nil.find):

Rendered /opt/local/lib/ruby1.9/gems/1.9.1/gems/actionpack-3.0.0/lib/action_dispatch/middleware/templates/rescues/_trace.erb (1.5ms)
Rendered /opt/local/lib/ruby1.9/gems/1.9.1/gems/actionpack-3.0.0/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (100.9ms)
Rendered /opt/local/lib/ruby1.9/gems/1.9.1/gems/actionpack-3.0.0/lib/action_dispatch/middleware/templates/rescues/diagnostics.erb within rescues/layout (107.9ms)

Rails - 3.0.0
inherited_resources (1.1.2)

**Comment by joerichsen** [comment]
I had a similar error ie. "The error occurred while evaluating nil.find" - and the problem was that I had forgot to add the model class to my app :-|
