### ISSUE TITLE
Release a gem that supports rails 7

### ISSUE THREAD

**Issue by thoughtless** [activeadmin/inherited_resources#710]
The master branch already supports Rails 7. Would you be willing to release a gem with the current master branch? Installing from github is pretty easy from a Gemfile, but not so easy from a `gemspec` file.

Thanks!

P.S. Thank you for being so quick with supporting rails 7!

**Comment by rafaelfranca** [comment]
Done!

**Comment by andrewhampton** [comment]
Thank you!
