### ISSUE TITLE
Smarter Redirects

### ISSUE THREAD

**Issue by ryanb** [activeadmin/inherited_resources#72]
If one has `actions :index, :new, :create` it will still try to redirect to the show action by default when creating an item. It should be possible to know that there's no show action and redirect to the index action instead. If there's no index either, maybe it can redirect to the `root_url`.

**Comment by andriytyurnikov** [comment]
having some parameter for default redirect action sounds nice, indeed

**Comment by josevalim** [comment]
Great suggestions! Patches are welcome! :)
