### ISSUE TITLE
rails 3 > new_resource_url for Moduled Controller doesn't work

### ISSUE THREAD

**Issue by quorak** [activeadmin/inherited_resources#74]
class Configuration::ConfigurationsController < AdminController
  inherit_resources
  defaults :resource_class => Customer::Customer
  nested_belongs_to :customer_order, :parent_class => Customer::Order
end

gives me

undefined method `new_configuration_customer_order_configuration_url' for #Configuration::ConfigurationsController:0x0000010698ba00
Extracted source (around line #7):
4:      <h2><%=I18n.t "activecontroller.controllers.#{controller.controller_name}"%></h2>
6:      <ul>
7:          <li><%=link_to "neu", new_resource_url%></li>
8:      </ul>
10:         <form action="" method="post">

**Comment by josevalim** [comment]
The URL it tries to guess is correct. You rather have a different schema. Please check belongs to and defaults documentation to see the options you can pass in.
