### ISSUE TITLE
Question: Add action and define shared template

### ISSUE THREAD

**Issue by sdillard** [activeadmin/inherited_resources#75]
I am trying to figure out how to add an action to the list of defaults so I can extend the pattern you are using.  The reason is that I want to create a delete action that is a fall-back when javascript is disabled.  This uses a simple template that all resources will re-use.  I have created the action by mixing in the method in the InheritedResources::Actions module, which is working fine.  But there are two things I can't seem to do (not possible?  and sorry for having two issues in one ticket):
1. Specify a template to render by default in the action, instead of rendering the template with the same name as the view.  In this case, I want to render shared/delete unless the controller overrides this to specify another template
2. Create routes for this action so I could do delete_resource_url 

Any suggestions on how (if?) to go about doing this?  Thanks in advance

**Comment by josevalim** [comment]
1) can be done by adding another action to InheritedResources::Actions (I believe). But we have no API for 2). Patches are welcome!

**Comment by josevalim** [comment]
Any news here or I can mark this as stale?
