### ISSUE TITLE
nested belongs_to does not handle singletons

### ISSUE THREAD

**Issue by jostheim** [activeadmin/inherited_resources#76]
hiearchy is box > tab (polymorphic) > feed

in the feed:

polymorphic_belongs_to :all_tab, :chatter_tab, :friends_tab, :featured_tab, :custom_tab, :singleton => true do
    belongs_to :box, :singleton => true
  end

Try to create a feed:

undefined method `boxes' for #AllTab:0x2ff8258

It is not recognizing the singleton in the nested belongs_to...

**Comment by josevalim** [comment]
Patch please!

**Comment by jostheim** [comment]
I'll try to get to it, I just reverted back to not using inherited_resources, because I have deadlines.

**Comment by AsymmetricParabola** [comment]
Was this ever resolved somehow?

**My code:**

``` ruby
    class BlogPostsController < InheritedResources::Base
      belongs_to :user, :singleton => true, :finder => :find_by_username!, :param => :user_id do
        belongs_to :blog
      end
    end
```

**Output:**

```
undefined method `blogs' for #<User:0x000000034b80b8>
```

Is there a simple workaround?
