### ISSUE TITLE
Can't use resource in flash notice

### ISSUE THREAD

**Issue by chadoh** [activeadmin/inherited_resources#77]
```
def create
    create!(:notice => "#{@attendance.person.first_name} was there") { meeting_url @attendance.meeting}
end
```

The redirect works just fine, because the inherited resources `create` action is completed prior to the block being called. However, inherited resources attempts to create the flash notice _before_ completing the `create` action, so `@attendance` is nil and I get an error.

I tried combatting this by using Inherited Resources' wonderful helpers:

```
def create
    create!(:notice => "#{resource.person.first_name} was there") { meeting_url resource.meeting}
end
```

But this lead to a similar problem with trying to access the resource before it was created. "Couldn't find Attendance without an ID", I was told. So I suppose this method will work for the `update` action, but of course it shan't work for `create`.

**Comment by chadoh** [comment]
I am able to get around this by using

```
create! do |format|
    format.html do
        flash[:notice] = "#{resource.person.first_name} was there"
        redirect_to meeting_url resource.meeting
    end
end
```

**Comment by carlosantoniodasilva** [comment]
It's not an IR issue, what happens is that you're passing the :notice as param to the create method. It's executed before IR takes care of it, so you don't have @attendance variable. And as it's a create method, you're supposed to user build_resource instead of resource. The best way to handle that is how you've done, creating a format block, where you'd have access to all IR helpers.

**Comment by chadoh** [comment]
```
def create
    create!(:notice => "#{build_resource.person.first_name} was there") { meeting_url resource.meeting}
end
```

works! And I like how it looks better than the workaround I posted. Why did you say that my workaround was the best way to handle it?

Thanks for the feedback!

**Comment by carlosantoniodasilva** [comment]
Actually, it depends on the way you build the application, for instance, you might not have access to the person instance while building the resource or sth like that.. Or I just feel more comfortable with that anyway =).
