### ISSUE TITLE
:include?

### ISSUE THREAD

**Issue by lanetrain** [activeadmin/inherited_resources#78]
Hey guys
I'm probably missing something obvious.. but how would I override the collection to include a nested model?

ie; Post.all.includes(:comments)

Would I use the collection override like so?: (i'm not sure of the effect of end_of_association, so haven't tried this)
protected
        def collection
          @posts ||= end_of_association_chain.includes(:comments)
        end

**Comment by carlosantoniodasilva** [comment]
Your example should work properly. `end_of_association_chain` in a normal PostsController (without belongs_to or scopes) would return the model Post, so it'd be kinda same of `Post.includes(:comments)`. 
ps.: notice `Post.all.includes(:comments)` is wrong, you're not supposed to use `all`.
