### ISSUE TITLE
polymorphic belongs_to from a different angle

### ISSUE THREAD

**Issue by janlimpens** [activeadmin/inherited_resources#79]
Hello,

I have a Node which has many documents, all inheritors of the Document class, for instance a very generic Page class.

Now, assume, I have a

class Admin::PagesController < ApplicationController
  belongs_to :node

  def edit
    @page     = Page.find(params[:id])
    @node     = Node.find(params[:node_id])
  end

end

It seems necessary to be verbose about the edit (and every other) action or I'll get this exception:

undefined method `pages' for #Node:0x00000103098ab8

Is there a way, to tell i_r, that instead of :pages to take :documents for all of this crud stuff? It would work, if I used a documents_controller for this, but then, I'd probably receive documents and not pages from all form submissions...

**Comment by josevalim** [comment]
No, there is no way. I recommend to simple don't use Inherited Resources or be verbose in such cases.

**Comment by carlosantoniodasilva** [comment]
I believe it's possible to give :collection_name as a param to `belongs_to`, so you could call sth like:
    belongs_to :node, :collection_name => :documents
Take a look at the docs inside class_methods to see what's possible to do.

**Comment by janlimpens** [comment]
Very cool. Didn't work as above, but

  class Admin::PagesController < ApplicationController
    belongs_to :node
    defaults :collection_name => 'documents'
  end  
did.

Thanks!
