### ISSUE TITLE
polymorphic_symbols is undefined

### ISSUE THREAD

**Issue by rrouse** [activeadmin/inherited_resources#8]
When the exception is raised because no polymorphic association is found, the exception text contains #{polymorphic_symbols.inspect}. It throws another error because polymorphic_symbols doesn't exist.

 if key.nil?
              raise ScriptError, "Could not find param for polymorphic association.
                                  The request params keys are #{params.keys.inspect}
                                  and the polymorphic associations are
                                  #{polymorphic_symbols.inspect}." unless polymorphic_config[:optional]

```
          nil
```

**Comment by grimen** [comment]
I'm getting this also even with a basic sample similar to the one in the README.

**Comment by grimen** [comment]
I get the same error with 0.9.0 still... Did I miss something?

**Comment by rrouse** [comment]
Have you restarted your server? I no longer get that error after the update.

**Comment by grimen** [comment]
OK, Passenger failed on me. Correct error message shows up now. =)
