### ISSUE TITLE
respond_to defaults to html, even if not specified

### ISSUE THREAD

**Issue by mediavrog** [activeadmin/inherited_resources#80]
I configured my controller like so:

  inherit_resources
  respond_to :xml, :atom
  actions :index, :show

Thats fine as long as i make calls to
domain.com/api/things.xml

BUT when it's called without a format, it tries to render html, which i didn't specify in respond_to
(domain.com/api/things >>> Rails Error: Template is missing)

I think there should be a way to specify the default respond_to, or ir should use the first type defined in respond_to.

Or is there another way to solve this issue?

Thanks in advance

**Comment by josevalim** [comment]
You need to call clear_respond_to to undefine the previously defined formats.

**Comment by mediavrog** [comment]
thanks for this blazing fast answer. I'd like to see this documented somewhere, or did i miss it?

**Comment by josevalim** [comment]
Documented in Rails. It is a public API.

**Comment by mediavrog** [comment]
Thanks again. Didn't know about that.
