### ISSUE TITLE
Helper methods are not reloaded in development mode

### ISSUE THREAD

**Issue by bmihelac** [activeadmin/inherited_resources#81]
I notice that helper methods in ApplicationHelper they do not get reloaded in inherited resource controller unless explicitly included with helper ApplicationHelper:

class ItemsController < InheritedResources::Base
  #helper ApplicationHelper
end

This happens in development mode using ruby-1.9.2 and Rails3.

**Comment by danigb** [comment]
My helper methods aren't reloading too (using ruby1.8.7 and Rails3) ... I don't know exactly why, but i'm using inherited_resources...

**Comment by RobinBrouwer** [comment]
Had the same problem (Ruby 1.8.7 and Rails 3.0.1), but solved it by including the following to the ApplicationController: helper :all

EDIT: Sorry about that. Somehow it worked a few minutes ago, but now it doesn't work with helper :all. :(

**Comment by RobinBrouwer** [comment]
When I call inherit_resources inside the Controller instead of inheriting from InheritedResources::Base this problem doesn't occur anymore. I don't need to restart the server to reload the helpers. Just a temporary fix for the ones having the same issue. :)

**Comment by contentfree** [comment]
I'm curious why this issue has been closed. Was it fixed?

**Comment by jcarlson** [comment]
Linking to https://github.com/activeadmin/activeadmin/issues/697 since this might be the root cause?
