### ISSUE TITLE
Polymorphic belongs_to disregards the given :route_name option

### ISSUE THREAD

**Issue by contentfree** [activeadmin/inherited_resources#84]
We have an plans_controller for a Plan resource that belongs_to a (polymorphic) :owner. However, the owner is an instance of our User class. We need the edit_resource_path to use edit_owner_plan_path and so have given the belongs_to call in plans_controller the :route_name => 'owner' option (though IR's codebase shows that that is the default value already). 

But IR uses Rails' polymorphic_url and, because @owner is actually an instance of a User, Rails (& IR) try to go to edit_user_plan_path -- which doesn't exist.

If I specify a :route_name option, it seems like it really should use it...

**Comment by josevalim** [comment]
Patch please?

**Comment by josevalim** [comment]
Ok, closing this. If you can provide a patch, I will happily accept it.

**Comment by aaronchi** [comment]
ran into this today :(
