### ISSUE TITLE
Can't have an optional deep nesting, i.e A/B/C and B/C

### ISSUE THREAD

**Issue by sfenig** [activeadmin/inherited_resources#89]
This may be a known issue cause it's kind of weird scenario.  But since marking something optional just puts it into the polymorphic stack, the only way to get a symbol into parent symbols is if it's not optional.

**Comment by josevalim** [comment]
Inherited Resources code is really modular and well tested. Why don't you try out a patch? :)

**Comment by sfenig** [comment]
I'd like to do that.  I just wanted to get this out there first in case somebody else runs into it.

**Comment by romanenko** [comment]
I ran into it and I don't know how to fix it with a patch.. And I really would like to make an optional nesting..
