### ISSUE TITLE
Subclasses of Namespaced Controllers don't work properly with Polymorphic BelongsTo

### ISSUE THREAD

**Issue by lancejpollard** [activeadmin/inherited_resources#90]
My application has namespaced `Admin` controllers, which inherit `InheritedResources::Base`.  So I have:
- `Admin::AdminController < InheritedResources::Base`
  - `Admin::UsersController < Admin::AdminController`
  - `Admin::PostsController < Admin::AdminController`
  - ...

Some of my admin controllers have polymorphic `belongs_to` declarations:

```
class Admin::UsersController < Admin::AdminController
  belongs_to :group, :place, :polymorphic => true, :optional => true
end
```

When I run this in development, it works fine, when I go in production, it breaks (unloading?).  Anyways, I get this error:

```
NoMethodError (undefined method `[]' for nil:NilClass):
  /.../inherited_resources-1.0.6/lib/inherited_resources/polymorphic_helpers.rb:136:in `symbols_for_association_chain'
  /.../declarative_authorization-0.4.1/lib/declarative_authorization/reader.rb:60:in `find'
  /.../inherited_resources-1.0.6/lib/inherited_resources/polymorphic_helpers.rb:135:in `each'
  /.../inherited_resources-1.0.6/lib/inherited_resources/polymorphic_helpers.rb:135:in `find'
  /.../inherited_resources-1.0.6/lib/inherited_resources/polymorphic_helpers.rb:135:in `symbols_for_association_chain'
  /.../inherited_resources-1.0.6/lib/inherited_resources/polymorphic_helpers.rb:131:in `map'
  /.../inherited_resources-1.0.6/lib/inherited_resources/polymorphic_helpers.rb:131:in `symbols_for_association_chain'
  /.../inherited_resources-1.0.6/lib/inherited_resources/base_helpers.rb:127:in `association_chain'
  /.../inherited_resources-1.0.6/lib/inherited_resources/base_helpers.rb:143:in `with_chain'
  /.../inherited_resources-1.0.6/lib/inherited_resources/actions.rb:13:in `show'
```

Reason being... because for some reason `resources_configuration[:polymorphic][:symbols]` has all of the symbols from all `Admin::X` subclasses!

Tracing in the first line of `InheritedResources::ClassMethods.belongs_to`, the `self.resources_configuration[:polymorphic][:symbols]` for the `Admin::UsersController` class already has `[:item, :post, :task, ...]` from other controllers in it.  That doesn't seem right.

A quick fix is to change line ~135 from:

```
params_keys.include? resources_configuration[poly][:param].to_s
```

...to

```
resources_configuration.has_key?(poly) && params_keys.include?(resources_configuration[poly][:param].to_s)
```

like this:    

```
def symbols_for_association_chain #:nodoc:
  polymorphic_config = resources_configuration[:polymorphic]

  parents_symbols.map do |symbol|
    if symbol == :polymorphic
      params_keys = params.keys

      key = polymorphic_config[:symbols].find do |poly|
        resources_configuration.has_key?(poly) && params_keys.include?(resources_configuration[poly][:param].to_s)
      end

      if key.nil?
        raise ScriptError, "Could not find param for polymorphic association. The request" <<
                           "parameters are #{params.keys.inspect} and the polymorphic " <<
                           "associations are #{polymorphic_config[:symbols].inspect}." unless polymorphic_config[:optional]

        nil
      else
        @parent_type = key.to_sym
      end
    else
      symbol
    end
  end.compact
end
```

Not sure why it's doing that, probably some core thing.  Anyway, how should this be fixed?  Going to have this patch in my initializers until there's a better way.  Thanks!

[Rails 2.3.8]

**Comment by nilclass** [comment]
I'm having the same problem. Thanks for your workaround, will use it, but would love to see this fixed as well. If I find time, will look into it :)

**Comment by jfirebaugh** [comment]
This is a problem for me too.

The issue is this line in `initialize_resources_class_accessors!`:
    self.resources_configuration[:polymorphic] ||= { :symbols => [], :optional => false }

After the base Admin::AdminController gets this initialized, all the derived classes receive the same :symbols array rather than getting their own. resources_configuration is a class_inheritable attribute, but class_inheritable attributes are not deep copied.

**Comment by josevalim** [comment]
Yeah, that is it. Maybe you guys can provide a patch?

**Comment by josevalim** [comment]
Any news here? Can you guys please work on a patch? :)

**Comment by josevalim** [comment]
Fixed in master. If you need that in 2.3.x, I recommend you to send a pull request backporting it to Inherited Resources v1.0 branch.

**Comment by nilclass** [comment]
great, thanks josevalim!
