### ISSUE TITLE
find_by_sql produces error when using inherited_resources

### ISSUE THREAD

**Issue by inherited-klaus** [activeadmin/inherited_resources#91]
when using inherited resources and a custom sql statement by find_by_sql,
the test never reaches the action using the find_by_sql

error backtrace and debugger show, that 
an error is thrown, before even hitting the action like here: http://pastebin.com/WN2NrvQU

is there any other possibility than rewriting the statement as normal find or named scope? i think the problem is related to before filters in inherited_resources (i deactivated all before filters in my controller for this testing)

**Comment by josevalim** [comment]
From the backtrace, it seems that cancan is forcing the resource to be loaded, which fails since you don't have an id. You need to disable cancan before_filter. This is not an inherited resources bug.

**Comment by inherited-klaus** [comment]
but why does it work when i replace InheritedResources::Base with ApplicationController (so just disabling inherited_resources)
cancan is still turned on then and not causing problems?! the test controller and further testing shows, that everything's fine then, makes no sense to me at the moment

**Comment by josevalim** [comment]
Because cancan is calling Inherited Resources `resource` method. Take a look at the backtrace and see who is calling `resource`. It is cancan internals.
