### ISSUE TITLE
IR using parent class name rather than specific class name of STI'ed model

### ISSUE THREAD

**Issue by robguthrie** [activeadmin/inherited_resources#96]
Hi,
I'm having a problem with IR not using the most specific model name on a polymorphic association.

a brief description of my setup with filename and relevant snippets of the content

models/person.rb
class Person < ActiveRecord::Base
  has_many :notes, :as => :resource 
end

models/resident.rb
class Resident < Person  
end

I also have other similar subclasses of person as you'll see below

models/note.rb
class Note
  belongs_to :resource, :polymorphic => true 
end

controllers/notes_controller.rb
class NotesController < ApplicationController
  inherit_resources 
  belongs_to :resident, :doctor, :staff, :nurse, :social_worker, :person, :optional => true 
end

config/routes.rb
resources :residents do
  resources :notes 
end

The problem is:
when I GET "/residents/949273910/notes"

I'm seeing the following query
SELECT `notes`.\* FROM `notes` WHERE (`notes`.resource_id = 1 AND `notes`.resource_type = 'Person')

when i expect to see:
SELECT `notes`.\* FROM `notes` WHERE (`notes`.resource_id = 1 AND `notes`.resource_type = 'Resident')

Can someone explain why this is happening?

**Comment by josevalim** [comment]
I have no idea. Maybe you can try out a patch or a test case to IR?
