### ISSUE TITLE
In rails 3.0.3 you always get readonly records when begin_of_association_chain is used

### ISSUE THREAD

**Issue by alhafoudh** [activeadmin/inherited_resources#99]
In rails 3.0.3 you always get readonly records when begin_of_association_chain is used, so when you have just something like following code in your controller, you will get ActiveRecord::ReadOnlyRecord exception when you execute update action.

```
class NotificationsController < InheritedResources::Base

... 

protected

def begin_of_association_chain
  current_user
end

...

end
```

You need to hack it by creating custom update action like this:

```
def update
  @notification = current_user.notifications.find(params[:id], :readonly => false)
  update!
end
```

**Comment by kolo** [comment]
Not only in 3.0.3, also appears in 3.0.5
